In [1]:
%pip install pandas requests beautifulsoup4 playwright nest_asyncio

Collecting pandas
  Downloading pandas-3.1.0-cp313-cp313-win_amd64.whl.metadata (18 kB)
Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting playwright
  Downloading playwright-1.64.1-py3-none-win_amd64.whl.metadata (3.3 kB)
Collecting nest_asyncio
  Using cached nest_asyncio-1.6.0-py3-none-any.whl.metadata (2.8 kB)
Collecting numpy>=2.0.2 (from pandas)
  Downloading numpy-2.5.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.9.0 in d:\data downloads\crawler_putusan_ma_final\.venv\lib\site-packages (from pandas) (3.0.0)
Requirement already satisfied: tzdata in d:\data downloads\crawler_putusan_ma_final\.venv\lib\site-packages (from pandas) (2026.6)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.5.2-cp313-cp313-win_amd64.whl.metadata (47 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.8.0-py3-none-any.whl.metadata (7.4 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.10.23-py3-none-any.whl.metadata (2.5 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-3.0.4-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in d:\data downloads\crawler_putusan_ma_final\.venv\lib\site-packages (from beautifulsoup4) (4.16.0)
Collecting pyee<15,>=13 (from playwright)
  Downloading pyee-14.0.0-py3-none-any.whl.metadata (1.8 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright)
  Downloading greenlet-3.5.6-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: six>=1.6 in d:\data downloads\crawler_putusan_ma_final\.venv\lib\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Downloading pandas-3.1.0-cp313-cp313-win_amd64.whl (10.7 MB)
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ------- -------------------------------- 2.1/10.7 MB 13.2 MB/s eta 0:00:01
   -------------------- ------------------- 5.5/10.7 MB 14.5 MB/s eta 0:00:01
   ------------------------------- -------- 8.4/10.7 MB 14.1 MB/s eta 0:00:01
   ----------------------------------- ---- 9.4/10.7 MB 12.5 MB/s eta 0:00:01
   ---------------------------------------- 10.7/10.7 MB 11.0 MB/s eta 0:00:00
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading playwright-1.64.1-py3-none-win_amd64.whl (38.8 MB)
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   - -------------------------------------- 1.8/38.8 MB 8.5 MB/s eta 0:00:05
   --- ------------------------------------ 3.7/38.8 MB 8.6 MB/s eta 0:00:05
   ----- ---------------------------------- 5.5/38.8 MB 8.8 MB/s eta 0:00:04
   ------- -------------------------------- 6.8/38.8 MB 8.0 MB/s eta 0:00:05
   --------- ------------------------------ 8.9/38.8 MB 8.5 MB/s eta 0:00:04
   ----------- ---------------------------- 11.0/38.8 MB 8.7 MB/s eta 0:00:04
   ------------- -------------------------- 13.1/38.8 MB 8.7 MB/s eta 0:00:03
   --------------- ------------------------ 14.7/38.8 MB 8.6 MB/s eta 0:00:03
   ----------------- ---------------------- 16.8/38.8 MB 8.7 MB/s eta 0:00:03
   ------------------- -------------------- 19.1/38.8 MB 8.9 MB/s eta 0:00:03
   --------------------- ------------------ 21.0/38.8 MB 9.0 MB/s eta 0:00:02
   ------------------------ --------------- 23.6/38.8 MB 9.2 MB/s eta 0:00:02
   -------------------------- ------------- 26.0/38.8 MB 9.4 MB/s eta 0:00:02
   --------------------------- ------------ 27.0/38.8 MB 9.2 MB/s eta 0:00:02
   ----------------------------- ---------- 28.3/38.8 MB 8.9 MB/s eta 0:00:02
   ------------------------------ --------- 29.9/38.8 MB 8.8 MB/s eta 0:00:02
   -------------------------------- ------- 31.5/38.8 MB 8.7 MB/s eta 0:00:01
   ---------------------------------- ----- 33.6/38.8 MB 8.7 MB/s eta 0:00:01
   ------------------------------------- -- 36.2/38.8 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------  38.5/38.8 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------- 38.8/38.8 MB 8.7 MB/s eta 0:00:00
Using cached nest_asyncio-1.6.0-py3-none-any.whl (5.2 kB)
Downloading certifi-2026.10.23-py3-none-any.whl (135 kB)
Downloading charset_normalizer-3.5.2-cp313-cp313-win_amd64.whl (206 kB)
Downloading greenlet-3.5.6-cp313-cp313-win_amd64.whl (324 kB)
Downloading idna-3.20-py3-none-any.whl (69 kB)
Downloading numpy-2.5.4-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/12.6 MB 8.7 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.6 MB 9.3 MB/s eta 0:00:01
   --------------- ------------------------ 5.0/12.6 MB 7.6 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.6 MB 8.0 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 8.4 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 8.2 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 7.6 MB/s eta 0:00:00
Downloading pyee-14.0.0-py3-none-any.whl (15 kB)
Downloading soupsieve-3.0.4-py3-none-any.whl (42 kB)
Downloading urllib3-2.8.0-py3-none-any.whl (135 kB)
Installing collected packages: urllib3, soupsieve, pyee, numpy, nest_asyncio, idna, greenlet, charset_normalizer, certifi, requests, playwright, pandas, beautifulsoup4
Successfully installed beautifulsoup4-4.15.0 certifi-2026.10.23 charset_normalizer-3.5.2 greenlet-3.5.6 idna-3.20 nest_asyncio-1.6.0 numpy-2.5.4 pandas-3.1.0 playwright-1.64.1 pyee-14.0.0 requests-2.34.2 soupsieve-3.0.4 urllib3-2.8.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import asyncio
import nest_asyncio
import pandas as pd
import requests
import re
import os
import time

from bs4 import BeautifulSoup
from pathlib import Path
from urllib.parse import urljoin

nest_asyncio.apply()

print("Library berhasil diimpor!")

Library berhasil diimpor!

In [3]:
BASE_URL = "https://putusan3.mahkamahagung.go.id"

URL_TAHUN = {
    2023: f"{BASE_URL}/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2023.html",

    2024: f"{BASE_URL}/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2024.html",

    2025: f"{BASE_URL}/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2025.html"
}

TARGET_PDF = 50

FOLDER_DATA = Path("data")
FOLDER_PDF = Path("PDF_Putusan")
FOLDER_TXT = Path("TXT_Putusan")

for folder in [
    FOLDER_DATA,
    FOLDER_PDF / "2023",
    FOLDER_PDF / "2024",
    FOLDER_PDF / "2025",
    FOLDER_TXT / "2023",
    FOLDER_TXT / "2024",
    FOLDER_TXT / "2025"
]:
    folder.mkdir(parents=True, exist_ok=True)

print("Konfigurasi selesai!")

Konfigurasi selesai!

In [4]:
for tahun, url in URL_TAHUN.items():

    print("=" * 60)
    print("TAHUN:", tahun)

    try:
        response = requests.get(
            url,
            timeout=30,
            headers={
                "User-Agent": "Mozilla/5.0"
            }
        )

        print("HTTP:", response.status_code)

        if response.status_code == 200:
            soup = BeautifulSoup(
                response.text,
                "html.parser"
            )

            print("Judul:", soup.title.text.strip())
            print("Halaman berhasil dibaca.")

        else:
            print("Akses belum berhasil.")

    except Exception as e:
        print("ERROR:", e)

============================================================
TAHUN: 2023
HTTP: 403
Akses belum berhasil.
============================================================
TAHUN: 2024
HTTP: 403
Akses belum berhasil.
============================================================
TAHUN: 2025
HTTP: 403
Akses belum berhasil.

In [5]:

from playwright.async_api import async_playwright

async def test_browser_access():

    async with async_playwright() as p:

        browser = await p.chromium.connect_over_cdp(
            "http://127.0.0.1:9222"
        )

        context = browser.contexts[0]

        page = (
            context.pages[0]
            if context.pages
            else await context.new_page()
        )

        url = URL_TAHUN[2023]

        print("Menguji akses halaman tahun 2023...")
        
        response = await page.goto(
            url,
            wait_until="domcontentloaded",
            timeout=60000
        )

        print("HTTP:", response.status if response else None)
        print("URL akhir:", page.url)
        print("Judul:", await page.title())

        text = await page.locator("body").inner_text()
        print("\nCUPLIKAN HALAMAN:")
        print(text[:2000])

        await browser.close()

await test_browser_access()

Menguji akses halaman tahun 2023...
HTTP: 200
URL akhir: https://putusan3.mahkamahagung.go.id/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2023.html
Judul: Direktori Putusan

CUPLIKAN HALAMAN:
BERANDA
PENCARIAN
DIREKTORI
PENGADILAN
PERATURAN
TENTANG
Beranda
Pengadilan
PN SURABAYA
Pidana Khusus
Narkotika dan Psikotropika
Putus
2023
PUTUSAN PN SURABAYA
NARKOTIKA DAN PSIKOTROPIKA
PUTUS TAHUN 2023
Direktori

Semua Direktori

Perdata 4202

Pidana Umum 2492

Pidana Khusus 1538

Perdata Agama 526

Perdata Khusus 345

Pidana Militer 1

Klasifikasi

Narkotika dan Psikotropika 1054

Pengadilan

PN SURABAYA 1054

Tahun
Putus	Register	Upload


2026 460


2025 822


2024 715


2023 1054


2022 1185


selengkapnya

2026 324


2025 761


2024 814


2023 930


2022 1242


selengkapnya

2026 803


2025 759


2024 654


2023 1123


2022 1182


selengkapnya
Bulan

Januari 136

Februari 102

Maret 93

April 59

Mei 99

Juni 93

Juli 106

Agustus 91

September 64

Oktober 75

Nopember 69

Desember 67

Putusan
Penting
Terpopuler
Pengadilan  PN SURABAYA  Pidana Khusus  Narkotika dan Psikotropika
 Putus : 18-09-2023 — Upload : 12-02-2024
Putusan PN SURABAYA Nomor 1512/Pid.Sus/2023/PN Sby

Tanggal 18 September 2023 — Penuntut Umum:
PUTU SUDARSANA, S.H.
Terdakwa:
BAGUS IRYANTO als BAGUS Bin WIDYAN MULYADI.
140 — 84
Pengadilan  PN SURABAYA  Pidana Khusus  Narkotika dan Psikotropika
 Register : 25-10-2023 — Putus : 28-12-2023 — Upload : 15-01-2024
Putusan PN SURABAYA Nomor 2256/Pid.Sus/2023/PN Sby

Tanggal 28 Desember 2023 — Penuntut Umum:
DARWIS,SH.,MH
Terdakwa:
MOHAMMAD FANI FATURROHMAN Bin SUTIKNO
110 — 0
Pengadilan  PN SURABAYA  Pidana Khusus  Narkotika dan Psikotropika
 Register : 25-10-2023 — Putus : 28-12-2023 — Upload : 15-01-2024
Putusan PN SURABAYA Nomor 2257/Pid.Sus/2023/PN Sby

Tanggal 28 Desember 2023 — Penuntut Umum:
ARIE ZAKY PRASETYA, S.H.
Terdakwa:
MULYONO Bin REMAN
82 — 0
Pengadilan  PN SURABAYA  Pidana Khusus  Narkotika dan Psikotropika
 Register : 14-11-2023 — Putus : 28-12-2023 — Upload : 15-01-2024
Putusan PN SURABAYA Nomor 2389/Pid.Sus/2023/PN Sby

Tanggal 28 Desember 2023 — Penuntut Umum:
ANGGRAINI SH
Terdakwa:
VICKY HARIS C

In [6]:
async def inspect_decision_links():

    async with async_playwright() as p:

        browser = await p.chromium.connect_over_cdp(
            "http://127.0.0.1:9222"
        )

        context = browser.contexts[0]
        page = context.pages[0]

        await page.goto(
            URL_TAHUN[2023],
            wait_until="domcontentloaded"
        )

        links = await page.locator("a[href]").evaluate_all("""
            elements => elements.map(a => ({
                text: (a.innerText || a.textContent || '').trim(),
                href: a.href
            })).filter(a =>
                a.href.includes('/direktori/putusan/')
            )
        """)

        print("Total link putusan:", len(links))

        for link in links[:10]:
            print("\\nJudul:", link["text"])
            print("URL:", link["href"])

        await browser.close()

await inspect_decision_links()

Total link putusan: 43
\nJudul: Putusan PN SURABAYA Nomor 1512/Pid.Sus/2023/PN Sby
URL: https://putusan3.mahkamahagung.go.id/direktori/putusan/zaeec95fd2b30f568e96313133333038.html
\nJudul: Putusan PN SURABAYA Nomor 2256/Pid.Sus/2023/PN Sby
URL: https://putusan3.mahkamahagung.go.id/direktori/putusan/zaeeb3b51b0ea8349cc2323134383131.html
\nJudul: Putusan PN SURABAYA Nomor 2257/Pid.Sus/2023/PN Sby
URL: https://putusan3.mahkamahagung.go.id/direktori/putusan/zaeeb3b50c0e21debfde323134373436.html
\nJudul: Putusan PN SURABAYA Nomor 2389/Pid.Sus/2023/PN Sby
URL: https://putusan3.mahkamahagung.go.id/direktori/putusan/zaeeb3b4b16da786b453323134353134.html
\nJudul: Putusan PN SURABAYA Nomor 2282/Pid.Sus/2023/PN Sby
URL: https://putusan3.mahkamahagung.go.id/direktori/putusan/zaeeb3b4954d60968798323134343237.html
\nJudul: Putusan PN SURABAYA Nomor 2395/Pid.Sus/2023/PN Sby
URL: https://putusan3.mahkamahagung.go.id/direktori/putusan/zaeea0695601b9e0b718303832373537.html
\nJudul: Putusan PN SURABAYA Nomor 2216/Pid.Sus/2023/PN Sby
URL: https://putusan3.mahkamahagung.go.id/direktori/putusan/zaee9feef5d62238874e313735313537.html
\nJudul: Putusan PN SURABAYA Nomor 2052/Pid.Sus/2023/PN Sby
URL: https://putusan3.mahkamahagung.go.id/direktori/putusan/zaee9fed44e01e9e90e8313733393530.html
\nJudul: Putusan PN SURABAYA Nomor 2317/Pid.Sus/2023/PN Sby
URL: https://putusan3.mahkamahagung.go.id/direktori/putusan/zaee9fea26a2fbc0a384313731373331.html
\nJudul: Putusan PN SURABAYA Nomor 2053/Pid.Sus/2023/PN Sby
URL: https://putusan3.mahkamahagung.go.id/direktori/putusan/zaee9fe62ddd4962b15d313634393035.html

In [7]:
async def inspect_pagination():

    async with async_playwright() as p:

        browser = await p.chromium.connect_over_cdp(
            "http://127.0.0.1:9222"
        )

        page = browser.contexts[0].pages[0]

        await page.goto(
            URL_TAHUN[2023],
            wait_until="domcontentloaded"
        )

        # Ambil seluruh link putusan
        decision_links = await page.locator("a[href]").evaluate_all("""
            elements => elements
                .filter(a => a.href.includes('/direktori/putusan/'))
                .map(a => ({
                    title: (a.innerText || a.textContent || '').trim(),
                    url: a.href
                }))
        """)

        unique_links = {
            item["url"]: item for item in decision_links
        }

        print("Total link:", len(decision_links))
        print("Link unik:", len(unique_links))

        # Periksa link pagination
        pagination = await page.locator("a[href]").evaluate_all("""
            elements => elements.map(a => ({
                text: (a.innerText || a.textContent || '').trim(),
                href: a.href
            })).filter(a =>
                /page\\//i.test(a.href)
                || /berikutnya|next|selanjutnya/i.test(a.text)
            )
        """)

        print("\\nLINK PAGINATION:")

        for item in pagination:
            print(item)

        await browser.close()


await inspect_pagination()

Total link: 43
Link unik: 37
\nLINK PAGINATION:
{'text': '2', 'href': 'https://putusan3.mahkamahagung.go.id/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2023/page/2.html'}
{'text': '3', 'href': 'https://putusan3.mahkamahagung.go.id/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2023/page/3.html'}
{'text': '4', 'href': 'https://putusan3.mahkamahagung.go.id/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2023/page/4.html'}
{'text': 'Next', 'href': 'https://putusan3.mahkamahagung.go.id/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2023/page/2.html'}
{'text': 'Last', 'href': 'https://putusan3.mahkamahagung.go.id/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2023/page/53.html'}

In [8]:

async def test_page_2():

    async with async_playwright() as p:

        browser = await p.chromium.connect_over_cdp(
            "http://127.0.0.1:9222"
        )

        context = browser.contexts[0]
        page = context.pages[0]

        url = (
            "https://putusan3.mahkamahagung.go.id/"
            "direktori/index/pengadilan/pn-surabaya/"
            "kategori/narkotika-dan-psikotropika-1/"
            "tahunjenis/putus/tahun/2023/page/2.html"
        )

        print("Menguji halaman 2 tahun 2023...")

        response = await page.goto(
            url,
            wait_until="domcontentloaded",
            timeout=60000
        )

        print("HTTP:", response.status if response else None)
        print("URL akhir:", page.url)
        print("Judul:", await page.title())

        links = await page.locator("a[href]").evaluate_all("""
            elements => elements
                .filter(a => a.href.includes('/direktori/putusan/'))
                .map(a => ({
                    title: (a.innerText || a.textContent || '').trim(),
                    url: a.href
                }))
        """)

        unique = {
            item["url"]: item for item in links
        }

        print("Total link:", len(links))
        print("Link unik:", len(unique))

        for item in list(unique.values())[:5]:
            print(item["title"])
            print(item["url"])

        await browser.close()


await test_page_2()

Menguji halaman 2 tahun 2023...
HTTP: 200
URL akhir: https://putusan3.mahkamahagung.go.id/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2023/page/2.html
Judul: Direktori Putusan
Total link: 43
Link unik: 42
Putusan PN SURABAYA Nomor 2219/Pid.Sus/2023/PN Sby
https://putusan3.mahkamahagung.go.id/direktori/putusan/zaee9d96f3af8a58ae24313831363535.html
Putusan PN SURABAYA Nomor 2417/Pid.Sus/2023/PN Sby
https://putusan3.mahkamahagung.go.id/direktori/putusan/zaee9d805ac7e562ad8e313533353039.html
Putusan PN SURABAYA Nomor 2258/Pid.Sus/2023/PN Sby
https://putusan3.mahkamahagung.go.id/direktori/putusan/zaee9d7fc537bb9ebb33313533303539.html
Putusan PN SURABAYA Nomor 1918/Pid.Sus/2023/PN Sby
https://putusan3.mahkamahagung.go.id/direktori/putusan/zaee9a726f86f36eba5a313831373538.html
Putusan PN SURABAYA Nomor 2090/Pid.Sus/2023/PN Sby
https://putusan3.mahkamahagung.go.id/direktori/putusan/zaee9a6cd224ba0cbdb8313733373436.html

In [10]:

import csv
import re
import asyncio
import pandas as pd
from pathlib import Path
from playwright.async_api import async_playwright

# ==========================================
# KONFIGURASI
# ==========================================

MAX_HALAMAN = 5
DELAY = 5

OUTPUT = Path("data/metadata_putusan.csv")
OUTPUT.parent.mkdir(parents=True, exist_ok=True)

BASE_URL = "https://putusan3.mahkamahagung.go.id"

URL_TAHUN = {
    2023: f"{BASE_URL}/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2023.html",
    2024: f"{BASE_URL}/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2024.html",
    2025: f"{BASE_URL}/direktori/index/pengadilan/pn-surabaya/kategori/narkotika-dan-psikotropika-1/tahunjenis/putus/tahun/2025.html"
}

# ==========================================
# FUNGSI EKSTRAKSI LINK
# ==========================================


async def extract_metadata(page, tahun):

    links = await page.locator("a[href]").evaluate_all("""
        elements => elements.map(a => ({
            title: (a.innerText || a.textContent || '').trim(),
            url: a.href
        })).filter(a =>
            a.url.includes('/direktori/putusan/')
        )
    """)

    results = []

    for item in links:

        title = re.sub(r"\s+", " ", item["title"]).strip()

        match = re.search(
            r"Nomor\s+(.+)$",
            title,
            re.IGNORECASE
        )

        if not match:
            continue

        nomor = match.group(1).strip()

        results.append({
            "No Putusan": nomor,
            "Tahun Filter": tahun,
            "Lembaga Peradilan": "Pengadilan Negeri Surabaya",
            "Judul Putusan": title,
            "URL Detail": item["url"]
        })

    return results



# ==========================================
# FUNGSI SIMPAN PROGRES
# ==========================================

def save_metadata(data):

    df = pd.DataFrame(data)

    if not df.empty:
        df = df.drop_duplicates(
            subset=["URL Detail"]
        )

        df = df.reset_index(drop=True)
        df.insert(0, "No", range(1, len(df) + 1))

    df.to_csv(
        OUTPUT,
        index=False,
        encoding="utf-8-sig"
    )

    return df


# ==========================================
# CRAWLING UTAMA
# ==========================================

async def crawling_metadata():

    all_data = []
    visited_urls = set()

    async with async_playwright() as p:

        browser = await p.chromium.connect_over_cdp(
            "http://127.0.0.1:9222"
        )

        context = browser.contexts[0]

        page = (
            context.pages[0]
            if context.pages
            else await context.new_page()
        )

        stop_all = False

        for tahun, base_url in URL_TAHUN.items():

            if stop_all:
                break

            print("\\n" + "=" * 60)
            print("CRAWLING TAHUN:", tahun)
            print("=" * 60)

            for nomor_halaman in range(1, MAX_HALAMAN + 1):

                if nomor_halaman == 1:
                    url = base_url
                else:
                    url = (
                        base_url.replace(
                            ".html",
                            f"/page/{nomor_halaman}.html"
                        )
                    )

                if url in visited_urls:
                    continue

                visited_urls.add(url)

                print(
                    f"\\nTahun {tahun} | "
                    f"Halaman {nomor_halaman}"
                )

                try:

                    response = await page.goto(
                        url,
                        wait_until="domcontentloaded",
                        timeout=60000
                    )

                    if response is None:
                        print("Tidak ada respons.")
                        continue

                    print("HTTP:", response.status)

                    if response.status in (403, 429):

                        print(
                            "Pembatasan akses terdeteksi. "
                            "Crawler dihentikan."
                        )

                        stop_all = True
                        break

                    if response.status != 200:
                        print("Halaman dilewati.")
                        continue

                    hasil = await extract_metadata(
                        page,
                        tahun
                    )

                    jumlah_sebelum = len(all_data)

                    for item in hasil:
                        if item["URL Detail"] not in {
                            x["URL Detail"] for x in all_data
                        }:
                            all_data.append(item)

                    tambahan = len(all_data) - jumlah_sebelum

                    print("Link ditemukan:", len(hasil))
                    print("Data baru:", tambahan)
                    print("Total unik:", len(all_data))

                    save_metadata(all_data)

                    await asyncio.sleep(DELAY)

                except Exception as error:

                    print("Error:", repr(error))
                    stop_all = True
                    break

        await browser.close()

    # ======================================
    # REKAP
    # ======================================

    df = save_metadata(all_data)

    print("\\n" + "=" * 60)
    print("CRAWLING SELESAI")
    print("=" * 60)

    print("Total metadata unik:", len(df))

    if not df.empty:
        print("\\nJumlah per tahun:")
        print(df["Tahun Filter"].value_counts().sort_index())

    print("\\nFile tersimpan:", OUTPUT.resolve())

    return df


df_metadata = await crawling_metadata()

display(df_metadata.head(10))

\n============================================================
CRAWLING TAHUN: 2023
============================================================
\nTahun 2023 | Halaman 1
HTTP: 200
Link ditemukan: 43
Data baru: 37
Total unik: 37
\nTahun 2023 | Halaman 2
HTTP: 200
Link ditemukan: 43
Data baru: 22
Total unik: 59
\nTahun 2023 | Halaman 3
HTTP: 200
Link ditemukan: 43
Data baru: 23
Total unik: 82
\nTahun 2023 | Halaman 4
HTTP: 200
Link ditemukan: 43
Data baru: 20
Total unik: 102
\nTahun 2023 | Halaman 5
HTTP: 200
Link ditemukan: 43
Data baru: 20
Total unik: 122
\n============================================================
CRAWLING TAHUN: 2024
============================================================
\nTahun 2024 | Halaman 1
HTTP: 200
Link ditemukan: 43
Data baru: 43
Total unik: 165
\nTahun 2024 | Halaman 2
HTTP: 200
Link ditemukan: 43
Data baru: 20
Total unik: 185
\nTahun 2024 | Halaman 3
HTTP: 200
Link ditemukan: 43
Data baru: 20
Total unik: 205
\nTahun 2024 | Halaman 4
HTTP: 200
Link ditemukan: 43
Data baru: 18
Total unik: 223
\nTahun 2024 | Halaman 5
HTTP: 200
Link ditemukan: 43
Data baru: 19
Total unik: 242
\n============================================================
CRAWLING TAHUN: 2025
============================================================
\nTahun 2025 | Halaman 1
HTTP: 200
Link ditemukan: 43
Data baru: 40
Total unik: 282
\nTahun 2025 | Halaman 2
HTTP: 200
Link ditemukan: 43
Data baru: 20
Total unik: 302
\nTahun 2025 | Halaman 3
HTTP: 200
Link ditemukan: 43
Data baru: 20
Total unik: 322
\nTahun 2025 | Halaman 4
HTTP: 200
Link ditemukan: 43
Data baru: 20
Total unik: 342
\nTahun 2025 | Halaman 5
HTTP: 200
Link ditemukan: 43
Data baru: 20
Total unik: 362
\n============================================================
CRAWLING SELESAI
============================================================
Total metadata unik: 362
\nJumlah per tahun:
Tahun Filter
2023    122
2024    120
2025    120
Name: count, dtype: int64
\nFile tersimpan: D:\Data Downloads\Crawler_Putusan_MA_FINAL\data\metadata_putusan.csv

,No,No Putusan,Tahun Filter,Lembaga Peradilan,Judul Putusan,URL Detail
0,1,1512/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 1512/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
1,2,2256/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2256/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
2,3,2257/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2257/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
3,4,2389/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2389/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
4,5,2282/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2282/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
5,6,2395/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2395/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
6,7,2216/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2216/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
7,8,2052/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2052/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
8,9,2317/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2317/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
9,10,2053/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2053/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...

In [11]:
df_metadata = pd.read_csv("data/metadata_putusan.csv")

print("Total data:", len(df_metadata))

print("\nDistribusi tahun:")
print(df_metadata["Tahun Filter"].value_counts().sort_index())

display(df_metadata.head(10))

Total data: 362

Distribusi tahun:
Tahun Filter
2023    122
2024    120
2025    120
Name: count, dtype: int64

,No,No Putusan,Tahun Filter,Lembaga Peradilan,Judul Putusan,URL Detail
0,1,1512/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 1512/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
1,2,2256/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2256/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
2,3,2257/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2257/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
3,4,2389/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2389/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
4,5,2282/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2282/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
5,6,2395/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2395/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
6,7,2216/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2216/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
7,8,2052/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2052/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
8,9,2317/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2317/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...
9,10,2053/Pid.Sus/2023/PN Sby,2023,Pengadilan Negeri Surabaya,Putusan PN SURABAYA Nomor 2053/Pid.Sus/2023/PN...,https://putusan3.mahkamahagung.go.id/direktori...

AUDIT PDF

In [12]:

import asyncio
import pandas as pd
from pathlib import Path
from playwright.async_api import async_playwright

INPUT = Path("data/metadata_putusan.csv")
OUTPUT = Path("data/hasil_audit_pdf.csv")

df = pd.read_csv(INPUT)

async def audit_pdf():

    hasil = []

    async with async_playwright() as p:

        browser = await p.chromium.connect_over_cdp(
            "http://127.0.0.1:9222"
        )

        context = browser.contexts[0]
        page = context.pages[0]

        for i, row in df.iterrows():

            nomor = row["No Putusan"]
            url = row["URL Detail"]

            print(
                f"\n[{i+1}/{len(df)}] {nomor}"
            )

            status_pdf = ""
            url_pdf = ""
            keterangan = ""

            try:

                response = await page.goto(
                    url,
                    wait_until="domcontentloaded",
                    timeout=60000
                )

                if response is None:
                    status_pdf = "ERROR_HALAMAN"
                    keterangan = "Tidak ada respons"

                elif response.status in (403, 429):
                    status_pdf = "AKSES_DITOLAK"
                    keterangan = f"HTTP {response.status}"

                elif response.status != 200:
                    status_pdf = "ERROR_HALAMAN"
                    keterangan = f"HTTP {response.status}"

                else:

                    links = await page.locator(
                        "a[href]"
                    ).evaluate_all("""
                        elements => elements.map(a => ({
                            text: (a.innerText || a.textContent || '').trim(),
                            href: a.href
                        }))
                    """)

                    pdf_links = [
                        x for x in links
                        if "/pdf/" in x["href"].lower()
                        and "/zip/" not in x["href"].lower()
                    ]

                    if pdf_links:
                        status_pdf = "PDF_TERSEDIA"
                        url_pdf = pdf_links[0]["href"]
                        keterangan = "Tautan PDF ditemukan"

                    else:
                        status_pdf = "TIDAK_ADA_PDF"
                        keterangan = "Tautan PDF tidak ditemukan"

            except Exception as e:
                status_pdf = "ERROR_HALAMAN"
                keterangan = str(e)[:200]

            hasil.append({
                **row.to_dict(),
                "URL PDF": url_pdf,
                "Status PDF": status_pdf,
                "Keterangan": keterangan
            })

            # Simpan progres setiap putusan.
            pd.DataFrame(hasil).to_csv(
                OUTPUT,
                index=False,
                encoding="utf-8-sig"
            )

            print("Status:", status_pdf)

            # Berhenti jika server membatasi akses.
            if status_pdf == "AKSES_DITOLAK":
                print("Akses dibatasi. Audit dihentikan.")
                break

            await asyncio.sleep(3)

        await browser.close()

    return pd.DataFrame(hasil)


df_audit = await audit_pdf()

[1/362] 1512/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[2/362] 2256/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[3/362] 2257/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[4/362] 2389/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[5/362] 2282/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[6/362] 2395/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[7/362] 2216/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[8/362] 2052/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[9/362] 2317/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[10/362] 2053/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[11/362] 1948/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[12/362] 2129/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[13/362] 1997/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[14/362] 2438/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[15/362] 2255/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[16/362] 2330/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[17/362] 2325/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[18/362] 2327/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[19/362] 2349/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[20/362] 2345/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[21/362] 1513/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[22/362] 2675/Pid.Sus/2022/PN Sby
Status: TIDAK_ADA_PDF

[23/362] 890/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[24/362] 2610/Pid.Sus/2022/PN Sby
Status: ERROR_HALAMAN

[25/362] 140/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[26/362] 2409/Pid.Sus/2022/PN Sby
Status: ERROR_HALAMAN

[27/362] 2130/Pid.Sus/2022/PN Sby
Status: ERROR_HALAMAN

[28/362] 1595/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[29/362] 2796/Pid.Sus/2022/PN Sby
Status: PDF_TERSEDIA

[30/362] 270/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[31/362] 164/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[32/362] 2471/Pid.Sus/2022/PN Sby
Status: PDF_TERSEDIA

[33/362] 2764/Pid.Sus/2022/PN Sby
Status: TIDAK_ADA_PDF

[34/362] 1918/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[35/362] 842 B/PDT.SUS-ARBT/2026
Status: PDF_TERSEDIA

[36/362] 8457 K/PID.SUS/2026
Status: PDF_TERSEDIA

[37/362] 1049 K/PDT.SUS-BPSK/2026
Status: PDF_TERSEDIA

[38/362] 2219/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[39/362] 2417/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[40/362] 2258/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[41/362] 2090/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[42/362] 2337/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[43/362] 2264/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[44/362] 2232/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[45/362] 2139/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[46/362] 2145/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[47/362] 2320/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[48/362] 2166/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[49/362] 2062/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[50/362] 2174/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[51/362] 2254/Pid.Sus/2023/PN Sby
Status: ERROR_HALAMAN

[52/362] 2182/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[53/362] 2260/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[54/362] 2193/Pid.Sus/2023/PN Sby
Status: ERROR_HALAMAN

[55/362] 2169/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[56/362] 2190/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[57/362] 403 PK/PDT/2026
Status: PDF_TERSEDIA

[58/362] 4012 K/PDT/2026
Status: PDF_TERSEDIA

[59/362] 3162 K/PDT/2026
Status: PDF_TERSEDIA

[60/362] 2069/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[61/362] 2359/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[62/362] 2221/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[63/362] 2155/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[64/362] 1928/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[65/362] 1946/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[66/362] 2292/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[67/362] 2246/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[68/362] 2063/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[69/362] 2141/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[70/362] 2123/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[71/362] 2241/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[72/362] 2152/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[73/362] 2290/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[74/362] 2297/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[75/362] 2240/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[76/362] 2187/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[77/362] 2335/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[78/362] 2185/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[79/362] 2151/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[80/362] 2853 K/PDT/2026
Status: PDF_TERSEDIA

[81/362] 1061 K/PDT.SUS-PHI/2026
Status: PDF_TERSEDIA

[82/362] 1089 K/PDT.SUS-PHI/2026
Status: PDF_TERSEDIA

[83/362] 2287/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[84/362] 2224/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[85/362] 2128/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[86/362] 1967/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[87/362] 2041/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[88/362] 2263/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[89/362] 2111/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[90/362] 1998/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[91/362] 2192/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[92/362] 2273/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[93/362] 2162/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[94/362] 2274/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[95/362] 1880/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[96/362] 2186/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[97/362] 1982/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[98/362] 2043/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[99/362] 2269/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[100/362] 1915/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[101/362] 1968/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[102/362] 2159/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[103/362] 2072/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[104/362] 2071/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[105/362] 1923/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[106/362] 2042/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[107/362] 2068/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[108/362] 2031/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[109/362] 2188/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[110/362] 2215/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[111/362] 2194/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[112/362] 2308/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[113/362] 2189/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[114/362] 2020/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[115/362] 2239/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[116/362] 2010/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[117/362] 1024/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[118/362] 2047/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[119/362] 2177/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[120/362] 1922/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[121/362] 1992/Pid.Sus/2023/PN Sby
Status: TIDAK_ADA_PDF

[122/362] 2081/Pid.Sus/2023/PN Sby
Status: PDF_TERSEDIA

[123/362] 758/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[124/362] 1079/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[125/362] 1079/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[126/362] 943/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[127/362] 943/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[128/362] 666/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[129/362] 666/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[130/362] 886/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[131/362] 961/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[132/362] 961/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[133/362] 837/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[134/362] 890/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[135/362] 514/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[136/362] 697/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[137/362] 697/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[138/362] 394/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[139/362] 694/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[140/362] 694/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[141/362] 636/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[142/362] 636/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[143/362] 1068/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[144/362] 898/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[145/362] 802/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[146/362] 1483/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[147/362] 625/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[148/362] 1276/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[149/362] 1275/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[150/362] 938/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[151/362] 1109/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[152/362] 842/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[153/362] 519/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[154/362] 1128/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[155/362] 891/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[156/362] 1189/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[157/362] 2071/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[158/362] 417/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[159/362] 1808/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[160/362] 1852/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[161/362] 1711/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[162/362] 1278/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[163/362] 9777 K/PID.SUS/2026
Status: PDF_TERSEDIA

[164/362] 219 K/MIL/2026
Status: PDF_TERSEDIA

[165/362] 708 K/PDT.SUS-PHI/2026
Status: PDF_TERSEDIA

[166/362] 636/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[167/362] 486/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[168/362] 486/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[169/362] 486/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[170/362] 1807/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[171/362] 1947/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[172/362] 2017/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[173/362] 1950/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[174/362] 1966/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[175/362] 1814/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[176/362] 2050/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[177/362] 1794/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[178/362] 2197/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[179/362] 1921/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[180/362] 1998/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[181/362] 1878/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[182/362] 1984/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[183/362] 2104/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[184/362] 2170/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[185/362] 1629/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[186/362] 2014/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[187/362] 2032/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[188/362] 1926/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[189/362] 2127/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[190/362] 2054/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[191/362] 2025/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[192/362] 1855/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[193/362] 2122/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[194/362] 1901/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[195/362] 1760/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[196/362] 2118/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[197/362] 1915/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[198/362] 2051/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[199/362] 2157/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[200/362] 2020/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[201/362] 1795/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[202/362] 1856/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[203/362] 2068/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[204/362] 2027/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[205/362] 1751/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[206/362] 2302/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[207/362] 2167/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[208/362] 2009/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[209/362] 1810/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[210/362] 1980/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[211/362] 1986/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[212/362] 1917/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[213/362] 1902/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[214/362] 1854/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[215/362] 1846/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[216/362] 1764/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[217/362] 1853/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[218/362] 1779/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[219/362] 1746/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[220/362] 1904/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[221/362] 1996/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[222/362] 1817/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[223/362] 1872/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[224/362] 2016/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[225/362] 2034/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[226/362] 2008/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[227/362] 2090/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[228/362] 1799/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[229/362] 1729/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[230/362] 1995/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[231/362] 1741/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[232/362] 2065/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[233/362] 1979/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[234/362] 2129/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[235/362] 1961/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[236/362] 1968/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[237/362] 2052/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[238/362] 1931/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[239/362] 1893/Pid.Sus/2024/PN Sby
Status: ERROR_HALAMAN

[240/362] 2085/Pid.Sus/2024/PN Sby
Status: ERROR_HALAMAN

[241/362] 1861/Pid.Sus/2024/PN Sby
Status: ERROR_HALAMAN

[242/362] 1884/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[243/362] 1989/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[244/362] 1731/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[245/362] 1895/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[246/362] 1999/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[247/362] 1912/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[248/362] 2156/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[249/362] 1911/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[250/362] 2022/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[251/362] 2024/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[252/362] 2040/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[253/362] 1977/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[254/362] 1974/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[255/362] 1246/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[256/362] 1773/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[257/362] 1038/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[258/362] 222/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[259/362] 2224/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[260/362] 2144/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[261/362] 2029/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[262/362] 2108/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[263/362] 609/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[264/362] 1492/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[265/362] 2010/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[266/362] 566/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[267/362] 2385/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[268/362] 2296/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[269/362] 2335/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[270/362] 2454/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[271/362] 482/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[272/362] 1801/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[273/362] 2243/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[274/362] 551/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[275/362] 1257/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[276/362] 579/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[277/362] 1982/Pid.Sus/2024/PN Sby
Status: ERROR_HALAMAN

[278/362] 2113/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[279/362] 2247/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[280/362] 772/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[281/362] 279/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[282/362] 2364/Pid.Sus/2024/PN Sby
Status: PDF_TERSEDIA

[283/362] 2108/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[284/362] 1972/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[285/362] 2229/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[286/362] 1941/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[287/362] 2101/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[288/362] 2109/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[289/362] 1991/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[290/362] 2008/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[291/362] 1949/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[292/362] 1930/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[293/362] 1838/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[294/362] 2004/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[295/362] 1965/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[296/362] 1829/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[297/362] 1632/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[298/362] 1774/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[299/362] 1558/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[300/362] 2027/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[301/362] 2028/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[302/362] 1649/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[303/362] 1860/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[304/362] 1852/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[305/362] 2017/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[306/362] 1880/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[307/362] 1943/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[308/362] 1789/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[309/362] 2014/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[310/362] 1939/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[311/362] 1924/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[312/362] 1857/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[313/362] 1957/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[314/362] 1992/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[315/362] 1796/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[316/362] 1668/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[317/362] 1836/Pid.Sus/2025/PN Sby
Status: PDF_TERSEDIA

[318/362] 1808/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[319/362] 1854/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[320/362] 855/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[321/362] 526/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[322/362] 526/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[323/362] 476/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[324/362] 476/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[325/362] 2417/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[326/362] 2417/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[327/362] 2366/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[328/362] 2366/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[329/362] 2460/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[330/362] 2449/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[331/362] 2449/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[332/362] 18/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[333/362] 18/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[334/362] 2063/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[335/362] 2063/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[336/362] 172/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[337/362] 2445/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[338/362] 2421/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[339/362] 2421/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[340/362] 2421/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[341/362] 2491/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[342/362] 2491/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[343/362] 2439/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[344/362] 2439/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[345/362] 2439/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[346/362] 2439/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[347/362] 3/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[348/362] 3/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[349/362] 3/Pid.Sus/2025/PN Sby
Status: TIDAK_ADA_PDF

[350/362] 2518/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[351/362] 2518/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[352/362] 2211/Pid.Sus/2024/PN Sby
Status: TIDAK_ADA_PDF

[353/362] 2242/Pid.Sus/2024/PN Sby

In [13]:
import pandas as pd

# Membaca hasil audit lengkap
df_audit = pd.read_csv("data/hasil_audit_pdf.csv")

print("TOTAL DATA DIAUDIT:", len(df_audit))

print("\nREKAP STATUS PDF:")
print(df_audit["Status PDF"].value_counts())

print("\nREKAP BERDASARKAN TAHUN:")
display(
    pd.crosstab(
        df_audit["Tahun Filter"],
        df_audit["Status PDF"]
    )
)

TOTAL DATA DIAUDIT: 362

REKAP STATUS PDF:
Status PDF
PDF_TERSEDIA     234
TIDAK_ADA_PDF    119
ERROR_HALAMAN      9
Name: count, dtype: int64

REKAP BERDASARKAN TAHUN:

Status PDF    ERROR_HALAMAN  PDF_TERSEDIA  TIDAK_ADA_PDF
Tahun Filter
2023                      5            87             30
2024                      3            90             27
2025                      1            57             62

In [16]:
df_kandidat = df_audit[
    (df_audit["Status PDF"] == "PDF_TERSEDIA") &
    (df_audit["URL PDF"].notna())
].copy()

print("Total kandidat PDF:", len(df_kandidat))

Total kandidat PDF: 234

In [17]:
df_kandidat.to_csv(
    "data/kandidat_pdf.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Daftar kandidat berhasil disimpan!")

Daftar kandidat berhasil disimpan!

SELEKSI 50 PUTUSAN

In [18]:
# Membaca daftar kandidat PDF
df_kandidat = pd.read_csv("data/kandidat_pdf.csv")

# Memastikan hanya PDF yang memiliki URL
df_kandidat = df_kandidat[
    (df_kandidat["Status PDF"] == "PDF_TERSEDIA") &
    (df_kandidat["URL PDF"].notna())
].copy()

# Seleksi berdasarkan tahun
sampel_2023 = df_kandidat[
    df_kandidat["Tahun Filter"] == 2023
].sample(n=17, random_state=42)

sampel_2024 = df_kandidat[
    df_kandidat["Tahun Filter"] == 2024
].sample(n=17, random_state=42)

sampel_2025 = df_kandidat[
    df_kandidat["Tahun Filter"] == 2025
].sample(n=16, random_state=42)

# Gabungkan seluruh sampel
df_50 = pd.concat(
    [sampel_2023, sampel_2024, sampel_2025],
    ignore_index=True
)

# Simpan daftar 50 putusan
df_50.to_csv(
    "data/kandidat_50_putusan.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Total kandidat:", len(df_50))
print("\nDistribusi tahun:")
print(df_50["Tahun Filter"].value_counts().sort_index())

display(
    df_50[["No Putusan", "Tahun Filter", "URL PDF"]]
)

Total kandidat: 50

Distribusi tahun:
Tahun Filter
2023    17
2024    17
2025    16
Name: count, dtype: int64

,No Putusan,Tahun Filter,URL PDF
0,2031/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
1,1512/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
2,2260/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
3,2166/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
4,270/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
5,1982/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
6,140/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
7,2258/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
8,2325/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
9,2043/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
10,2047/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
11,1880/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
12,1061 K/PDT.SUS-PHI/2026,2023,https://putusan3.mahkamahagung.go.id/direktori...
13,2189/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
14,1024/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
15,2274/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
16,2359/Pid.Sus/2023/PN Sby,2023,https://putusan3.mahkamahagung.go.id/direktori...
17,2054/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
18,2017/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
19,1751/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
20,1904/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
21,1068/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
22,2050/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
23,2127/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
24,1846/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
25,891/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
26,1901/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
27,1741/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
28,1629/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
29,2302/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
30,1968/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
31,2071/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
32,1276/Pid.Sus/2024/PN Sby,2024,https://putusan3.mahkamahagung.go.id/direktori...
33,219 K/MIL/2026,2024,https://putusan3.mahkamahagung.go.id/direktori...
34,1895/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
35,222/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
36,1949/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
37,482/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
38,1965/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
39,1668/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
40,2109/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
41,1930/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
42,1880/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
43,2454/Pid.Sus/2024/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
44,1789/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
45,1773/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
46,1852/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
47,2101/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
48,2010/Pid.Sus/2024/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...
49,579/Pid.Sus/2025/PN Sby,2025,https://putusan3.mahkamahagung.go.id/direktori...

In [19]:
from playwright.async_api import async_playwright
from pathlib import Path
import pandas as pd
import asyncio
import os

# Membaca 50 kandidat
df_50 = pd.read_csv("data/kandidat_50_putusan.csv")

# Folder penyimpanan PDF
FOLDER_PDF = Path("PDF_Putusan")
FOLDER_PDF.mkdir(exist_ok=True)

print("Jumlah kandidat:", len(df_50))

Jumlah kandidat: 50

In [20]:
async def test_download_pdf():

    async with async_playwright() as p:

        browser = await p.chromium.connect_over_cdp(
            "http://127.0.0.1:9222"
        )

        context = browser.contexts[0]
        page = await context.new_page()

        hasil = []

        # Uji 5 kandidat pertama
        for i, row in df_50.head(5).iterrows():

            url_detail = row["URL Detail"]
            no_putusan = str(row["No Putusan"])

            print(f"\n[{i+1}/5] Menguji:", no_putusan)

            try:
                response = await page.goto(
                    url_detail,
                    wait_until="domcontentloaded",
                    timeout=60000
                )

                await page.wait_for_timeout(2000)

                if response is None or response.status != 200:
                    print("Halaman tidak berhasil diakses.")

                    hasil.append({
                        "No Putusan": no_putusan,
                        "Status": "GAGAL_AKSES"
                    })
                    continue

                # Cari tautan PDF aktif
                links = await page.locator("a[href]").evaluate_all("""
                    elements => elements.map(a => ({
                        href: a.href,
                        text: a.innerText
                    }))
                """)

                pdf_links = [
                    item["href"]
                    for item in links
                    if "/pdf/" in item["href"].lower()
                    and "/zip/" not in item["href"].lower()
                ]

                if not pdf_links:
                    print("Tautan PDF tidak ditemukan.")

                    hasil.append({
                        "No Putusan": no_putusan,
                        "Status": "PDF_TIDAK_DITEMUKAN"
                    })
                    continue

                print("Tautan PDF ditemukan:", pdf_links[0])

                hasil.append({
                    "No Putusan": no_putusan,
                    "Status": "LINK_PDF_DITEMUKAN",
                    "URL PDF": pdf_links[0]
                })

                await asyncio.sleep(3)

            except Exception as e:

                print("Error:", e)

                hasil.append({
                    "No Putusan": no_putusan,
                    "Status": "ERROR"
                })

        pd.DataFrame(hasil).to_csv(
            "data/hasil_uji_download.csv",
            index=False,
            encoding="utf-8-sig"
        )

        await page.close()

        print("\nPengujian selesai.")
        print(pd.DataFrame(hasil)["Status"].value_counts())


await test_download_pdf()

[1/5] Menguji: 2031/Pid.Sus/2023/PN Sby
Tautan PDF ditemukan: https://putusan3.mahkamahagung.go.id/direktori/download_file/973f154e3030ff8f89e30a706f6cd782/pdf/zaee8cec5a5e41babedf313331353235

[2/5] Menguji: 1512/Pid.Sus/2023/PN Sby
Tautan PDF ditemukan: https://putusan3.mahkamahagung.go.id/direktori/download_file/11eec962a67aa63a8ac2313135333233/pdf/zaeec95fd2b30f568e96313133333038

[3/5] Menguji: 2260/Pid.Sus/2023/PN Sby
Tautan PDF ditemukan: https://putusan3.mahkamahagung.go.id/direktori/download_file/a23f16004d4269086e7239d6e52bbb3b/pdf/zaee9a5d40c085f0acdc313534363230

[4/5] Menguji: 2166/Pid.Sus/2023/PN Sby
Tautan PDF ditemukan: https://putusan3.mahkamahagung.go.id/direktori/download_file/160f6f9feb1c4cf5d27a38063ef3ae41/pdf/zaee9a5ebe27b95eb03b313535373030

[5/5] Menguji: 270/Pid.Sus/2023/PN Sby
Tautan PDF ditemukan: https://putusan3.mahkamahagung.go.id/direktori/download_file/c7bd6a6fd498bed8e9e7661e10a36fdd/pdf/zaedb8d6c26339f482bd313534363434

Pengujian selesai.
Status
LINK_PDF_DITEMUKAN    5
Name: count, dtype: int64

In [21]:
async def download_satu_pdf():

    async with async_playwright() as p:

        browser = await p.chromium.connect_over_cdp(
            "http://127.0.0.1:9222"
        )

        context = browser.contexts[0]
        page = await context.new_page()

        row = df_50.iloc[0]

        no_putusan = str(row["No Putusan"])
        url_detail = row["URL Detail"]

        print("Menguji download:", no_putusan)

        try:
            response = await page.goto(
                url_detail,
                wait_until="domcontentloaded",
                timeout=60000
            )

            if response is None or response.status != 200:
                print("Halaman gagal diakses.")
                return

            await page.wait_for_timeout(2000)

            # Cari tautan PDF aktif
            pdf_links = await page.locator(
                'a[href*="/pdf/"]'
            ).evaluate_all("""
                elements => elements.map(a => a.href)
            """)

            pdf_links = [
                url for url in pdf_links
                if "/zip/" not in url.lower()
            ]

            if not pdf_links:
                print("Tautan PDF tidak ditemukan.")
                return

            pdf_url = pdf_links[0]

            print("URL PDF:", pdf_url)
            print("Memulai download...")

            # Klik tautan PDF dan tangkap file unduhan
            async with page.expect_download(
                timeout=60000
            ) as download_info:

                await page.evaluate("""
                    (url) => {
                        const link = [...document.querySelectorAll('a')]
                            .find(a => a.href === url);
                        if (link) link.click();
                    }
                """, pdf_url)

            download = await download_info.value

            nama_file = "uji_" + str(download.suggested_filename)

            lokasi_file = FOLDER_PDF / nama_file

            await download.save_as(str(lokasi_file))

            # Validasi file
            with open(lokasi_file, "rb") as f:
                header = f.read(5)

            ukuran = lokasi_file.stat().st_size

            if header == b"%PDF-" and ukuran > 0:
                print("\nBERHASIL! PDF valid.")
                print("Nama file:", nama_file)
                print("Ukuran:", ukuran, "bytes")
            else:
                print("\nFile terunduh tetapi bukan PDF valid.")

        except Exception as e:
            print("\nDownload gagal:", str(e))

        finally:
            await page.close()


await download_satu_pdf()

Menguji download: 2031/Pid.Sus/2023/PN Sby
URL PDF: https://putusan3.mahkamahagung.go.id/direktori/download_file/973f154e3030ff8f89e30a706f6cd782/pdf/zaee8cec5a5e41babedf313331353235
Memulai download...

BERHASIL! PDF valid.
Nama file: uji_putusan_2031_pid.sus_2023_pn_sby_20261030160527.pdf
Ukuran: 147004 bytes

In [22]:
from pathlib import Path

file_pdf = list(Path("PDF_Putusan").glob("*.pdf"))

print("Jumlah PDF:", len(file_pdf))

for file in file_pdf:
    print("Nama:", file.name)
    print("Ukuran:", round(file.stat().st_size / 1024, 2), "KB")

    with open(file, "rb") as f:
        header = f.read(5)

    print("Valid PDF:", header == b"%PDF-")

Jumlah PDF: 1
Nama: uji_putusan_2031_pid.sus_2023_pn_sby_20261030160527.pdf
Ukuran: 143.56 KB
Valid PDF: True