<a href="https://colab.research.google.com/github/shefiramarizcha62-sudo/Dataset-Narkotika_027_199/blob/crawling/04_Ekstraksi_Putusan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Clone repository GitHub

In [1]:
!git clone -b crawling https://github.com/shefiramarizcha62-sudo/Dataset-Narkotika_027_199.git

Cloning into 'Dataset-Narkotika_027_199'...
remote: Enumerating objects: 280, done.
remote: Counting objects: 100% (280/280), done.
remote: Compressing objects: 100% (238/238), done.
remote: Total 280 (delta 111), reused 172 (delta 32), pack-reused 0 (from 0)
Receiving objects: 100% (280/280), 11.36 MiB | 19.20 MiB/s, done.
Resolving deltas: 100% (111/111), done.

2. Periksa folder hasil clone

In [2]:
import os

REPO_DIR = '/content/Dataset-Narkotika_027_199'

for root, dirs, files in os.walk(REPO_DIR):
    level = root.replace(REPO_DIR, '').count(os.sep)

    if level <= 2:
        print('  ' * level + os.path.basename(root) + '/')

        for file in files[:5]:
            print('  ' * (level + 1) + file)

Dataset-Narkotika_027_199/
  04_ekstraksi_putusan.ipynb
  02_audit_pdf.ipynb
  03_download_pdf.ipynb
  01_crawling_metadata.ipynb
  05_validasi_dataset.ipynb
  TXT_Putusan/
    2024/
      putusan_898_Pid_Sus_2024_PN_Sby.txt
      putusan_1629_Pid_Sus_2024_PN_Sby.txt
      putusan_2010_Pid_Sus_2024_PN_Sby.txt
      putusan_2017_Pid_Sus_2024_PN_Sby.txt
      putusan_2071_Pid_Sus_2024_PN_Sby.txt
    2023/
      putusan_2166_Pid_Sus_2023_PN_Sby.txt
      putusan_1880_Pid_Sus_2023_PN_Sby.txt
      putusan_270_Pid_Sus_2023_PN_Sby.txt
      putusan_2031_Pid_Sus_2023_PN_Sby.txt
      putusan_2274_Pid_Sus_2023_PN_Sby.txt
    2025/
      putusan_2101_Pid_Sus_2025_PN_Sby.txt
      putusan_579_Pid_Sus_2025_PN_Sby.txt
      putusan_1895_Pid_Sus_2025_PN_Sby.txt
      putusan_2109_Pid_Sus_2025_PN_Sby.txt
      putusan_1668_Pid_Sus_2025_PN_Sby.txt
  data/
    hasil_uji_download.csv
    dua_kandidat_pengganti.csv
    kandidat_pdf.csv
    kandidat_50_putusan.csv
    hasil_download_pengganti.csv
  PDF_Putusan/
    uji_putusan_2031_pid.sus_2023_pn_sby_20261030160527.pdf
    2024/
      putusan_1751_Pid_Sus_2024_PN_Sby.pdf
      putusan_1741_Pid_Sus_2024_PN_Sby.pdf
      putusan_1901_Pid_Sus_2024_PN_Sby.pdf
      putusan_1276_Pid_Sus_2024_PN_Sby.pdf
      putusan_1629_Pid_Sus_2024_PN_Sby.pdf
    2023/
      putusan_2166_Pid_Sus_2023_PN_Sby.pdf
      putusan_270_Pid_Sus_2023_PN_Sby.pdf
      putusan_2274_Pid_Sus_2023_PN_Sby.pdf
      putusan_1512_Pid_Sus_2023_PN_Sby.pdf
      putusan_2260_Pid_Sus_2023_PN_Sby.pdf
    2025/
      putusan_579_Pid_Sus_2025_PN_Sby.pdf
      putusan_1852_Pid_Sus_2025_PN_Sby.pdf
      putusan_222_Pid_Sus_2025_PN_Sby.pdf
      putusan_1880_Pid_Sus_2025_PN_Sby.pdf
      putusan_1965_Pid_Sus_2025_PN_Sby.pdf
  .git/
    packed-refs
    config
    HEAD
    description
    index
    hooks/
      fsmonitor-watchman.sample
      push-to-checkout.sample
      pre-rebase.sample
      sendemail-validate.sample
      post-update.sample
    logs/
      HEAD
    info/
      exclude
    objects/
    branches/
    refs/

3. periksa jumlah pdf

In [ ]:
pdf_files = []

for root, dirs, files in os.walk(REPO_DIR):
    for file in files:
        if file.lower().endswith('.pdf'):
            pdf_files.append(os.path.join(root, file))

print("Total PDF:", len(pdf_files))

Total PDF: 51

4. filter 50 dokumen yang digunakan

In [ ]:
pdf_files = []

for root, dirs, files in os.walk(REPO_DIR):
    for file in files:
        if file.lower().endswith('.pdf'):

            # Mengecualikan file uji putusan
            if 'uji_putusan' in file.lower():
                continue

            pdf_files.append(os.path.join(root, file))

pdf_files = sorted(pdf_files)

print("Total PDF yang akan diproses:", len(pdf_files))

for file in pdf_files:
    print(os.path.basename(file))

Total PDF yang akan diproses: 50
putusan_1024_Pid_Sus_2023_PN_Sby.pdf
putusan_140_Pid_Sus_2023_PN_Sby.pdf
putusan_1512_Pid_Sus_2023_PN_Sby.pdf
putusan_1880_Pid_Sus_2023_PN_Sby.pdf
putusan_1982_Pid_Sus_2023_PN_Sby.pdf
putusan_2031_Pid_Sus_2023_PN_Sby.pdf
putusan_2043_Pid_Sus_2023_PN_Sby.pdf
putusan_2047_Pid_Sus_2023_PN_Sby.pdf
putusan_2166_Pid_Sus_2023_PN_Sby.pdf
putusan_2189_Pid_Sus_2023_PN_Sby.pdf
putusan_2258_Pid_Sus_2023_PN_Sby.pdf
putusan_2260_Pid_Sus_2023_PN_Sby.pdf
putusan_2274_Pid_Sus_2023_PN_Sby.pdf
putusan_2325_Pid_Sus_2023_PN_Sby.pdf
putusan_2359_Pid_Sus_2023_PN_Sby.pdf
putusan_2438_Pid_Sus_2023_PN_Sby.pdf
putusan_270_Pid_Sus_2023_PN_Sby.pdf
putusan_1068_Pid_Sus_2024_PN_Sby.pdf
putusan_1276_Pid_Sus_2024_PN_Sby.pdf
putusan_1629_Pid_Sus_2024_PN_Sby.pdf
putusan_1741_Pid_Sus_2024_PN_Sby.pdf
putusan_1751_Pid_Sus_2024_PN_Sby.pdf
putusan_1846_Pid_Sus_2024_PN_Sby.pdf
putusan_1901_Pid_Sus_2024_PN_Sby.pdf
putusan_1904_Pid_Sus_2024_PN_Sby.pdf
putusan_1968_Pid_Sus_2024_PN_Sby.pdf
putusan_2010_Pid_Sus_2024_PN_Sby.pdf
putusan_2017_Pid_Sus_2024_PN_Sby.pdf
putusan_2050_Pid_Sus_2024_PN_Sby.pdf
putusan_2054_Pid_Sus_2024_PN_Sby.pdf
putusan_2071_Pid_Sus_2024_PN_Sby.pdf
putusan_2127_Pid_Sus_2024_PN_Sby.pdf
putusan_2302_Pid_Sus_2024_PN_Sby.pdf
putusan_2454_Pid_Sus_2024_PN_Sby.pdf
putusan_891_Pid_Sus_2024_PN_Sby.pdf
putusan_898_Pid_Sus_2024_PN_Sby.pdf
putusan_1668_Pid_Sus_2025_PN_Sby.pdf
putusan_1773_Pid_Sus_2025_PN_Sby.pdf
putusan_1789_Pid_Sus_2025_PN_Sby.pdf
putusan_1852_Pid_Sus_2025_PN_Sby.pdf
putusan_1880_Pid_Sus_2025_PN_Sby.pdf
putusan_1895_Pid_Sus_2025_PN_Sby.pdf
putusan_1930_Pid_Sus_2025_PN_Sby.pdf
putusan_1949_Pid_Sus_2025_PN_Sby.pdf
putusan_1965_Pid_Sus_2025_PN_Sby.pdf
putusan_2101_Pid_Sus_2025_PN_Sby.pdf
putusan_2109_Pid_Sus_2025_PN_Sby.pdf
putusan_222_Pid_Sus_2025_PN_Sby.pdf
putusan_482_Pid_Sus_2025_PN_Sby.pdf
putusan_579_Pid_Sus_2025_PN_Sby.pdf

5. Hubungkan Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

6. Tentukan folder penyimpanan TXT

In [ ]:
import os

BASE_DIR = '/content/drive/MyDrive/Semester 7/Information Retrieval/UTS - KELOMPOK/CRAWLING'

TXT_DIR = os.path.join(BASE_DIR, 'TXT_Putusan')

for tahun in ['2023', '2024', '2025']:
    os.makedirs(os.path.join(TXT_DIR, tahun), exist_ok=True)

print("Folder TXT siap digunakan.")
print("Lokasi:", TXT_DIR)

Folder TXT siap digunakan.
Lokasi: /content/drive/MyDrive/Semester 7/Information Retrieval/UTS - KELOMPOK/CRAWLING/TXT_Putusan

7. Bersihkan file TXT lama

In [ ]:
for tahun in ['2023', '2024', '2025']:
    folder_txt = os.path.join(TXT_DIR, tahun)

    for file in os.listdir(folder_txt):
        if file.lower().endswith('.txt'):
            os.remove(os.path.join(folder_txt, file))

print("Seluruh TXT lama berhasil dibersihkan.")

Seluruh TXT lama berhasil dibersihkan.

8. Instal library PyMuPDF

In [ ]:
!pip install -q pymupdf

In [ ]:
import fitz
import pandas as pd

9. Ekstraksi PDF menjadi TXT

In [ ]:
hasil_ekstraksi = []

for path_pdf in pdf_files:

    # Mengambil tahun dari nama file
    nama_file = os.path.basename(path_pdf)

    tahun = next(
        (t for t in ['2023', '2024', '2025']
         if f'_{t}_' in nama_file),
        None
    )

    if tahun is None:
        print("Tahun tidak dikenali:", nama_file)
        continue

    nama_txt = os.path.splitext(nama_file)[0] + '.txt'

    folder_txt = os.path.join(TXT_DIR, tahun)
    path_txt = os.path.join(folder_txt, nama_txt)

    try:
        with fitz.open(path_pdf) as dokumen:

            jumlah_halaman = len(dokumen)

            teks = '\n'.join(
                halaman.get_text("text")
                for halaman in dokumen
            )

        with open(path_txt, 'w', encoding='utf-8') as file:
            file.write(teks)

        status = 'Berhasil' if teks.strip() else 'Teks Kosong'

        hasil_ekstraksi.append({
            'Tahun': tahun,
            'Nama PDF': nama_file,
            'Nama TXT': nama_txt,
            'Jumlah Halaman': jumlah_halaman,
            'Jumlah Karakter': len(teks),
            'Status': status
        })

    except Exception as e:

        hasil_ekstraksi.append({
            'Tahun': tahun,
            'Nama PDF': nama_file,
            'Nama TXT': nama_txt,
            'Jumlah Halaman': 0,
            'Jumlah Karakter': 0,
            'Status': f'Error: {e}'
        })

df_hasil = pd.DataFrame(hasil_ekstraksi)

display(df_hasil)

,Tahun,Nama PDF,Nama TXT,Jumlah Halaman,Jumlah Karakter,Status
0,2023,putusan_1024_Pid_Sus_2023_PN_Sby.pdf,putusan_1024_Pid_Sus_2023_PN_Sby.txt,60,190739,Berhasil
1,2023,putusan_140_Pid_Sus_2023_PN_Sby.pdf,putusan_140_Pid_Sus_2023_PN_Sby.txt,21,63029,Berhasil
2,2023,putusan_1512_Pid_Sus_2023_PN_Sby.pdf,putusan_1512_Pid_Sus_2023_PN_Sby.txt,18,59918,Berhasil
3,2023,putusan_1880_Pid_Sus_2023_PN_Sby.pdf,putusan_1880_Pid_Sus_2023_PN_Sby.txt,63,199841,Berhasil
4,2023,putusan_1982_Pid_Sus_2023_PN_Sby.pdf,putusan_1982_Pid_Sus_2023_PN_Sby.txt,15,45597,Berhasil
5,2023,putusan_2031_Pid_Sus_2023_PN_Sby.pdf,putusan_2031_Pid_Sus_2023_PN_Sby.txt,16,46655,Berhasil
6,2023,putusan_2043_Pid_Sus_2023_PN_Sby.pdf,putusan_2043_Pid_Sus_2023_PN_Sby.txt,22,64147,Berhasil
7,2023,putusan_2047_Pid_Sus_2023_PN_Sby.pdf,putusan_2047_Pid_Sus_2023_PN_Sby.txt,26,80603,Berhasil
8,2023,putusan_2166_Pid_Sus_2023_PN_Sby.pdf,putusan_2166_Pid_Sus_2023_PN_Sby.txt,25,78650,Berhasil
9,2023,putusan_2189_Pid_Sus_2023_PN_Sby.pdf,putusan_2189_Pid_Sus_2023_PN_Sby.txt,27,81695,Berhasil
10,2023,putusan_2258_Pid_Sus_2023_PN_Sby.pdf,putusan_2258_Pid_Sus_2023_PN_Sby.txt,21,63736,Berhasil
11,2023,putusan_2260_Pid_Sus_2023_PN_Sby.pdf,putusan_2260_Pid_Sus_2023_PN_Sby.txt,18,53834,Berhasil
12,2023,putusan_2274_Pid_Sus_2023_PN_Sby.pdf,putusan_2274_Pid_Sus_2023_PN_Sby.txt,18,55949,Berhasil
13,2023,putusan_2325_Pid_Sus_2023_PN_Sby.pdf,putusan_2325_Pid_Sus_2023_PN_Sby.txt,24,73741,Berhasil
14,2023,putusan_2359_Pid_Sus_2023_PN_Sby.pdf,putusan_2359_Pid_Sus_2023_PN_Sby.txt,24,69140,Berhasil
15,2023,putusan_2438_Pid_Sus_2023_PN_Sby.pdf,putusan_2438_Pid_Sus_2023_PN_Sby.txt,40,118953,Berhasil
16,2023,putusan_270_Pid_Sus_2023_PN_Sby.pdf,putusan_270_Pid_Sus_2023_PN_Sby.txt,17,52923,Berhasil
17,2024,putusan_1068_Pid_Sus_2024_PN_Sby.pdf,putusan_1068_Pid_Sus_2024_PN_Sby.txt,18,58155,Berhasil
18,2024,putusan_1276_Pid_Sus_2024_PN_Sby.pdf,putusan_1276_Pid_Sus_2024_PN_Sby.txt,19,56076,Berhasil
19,2024,putusan_1629_Pid_Sus_2024_PN_Sby.pdf,putusan_1629_Pid_Sus_2024_PN_Sby.txt,19,57806,Berhasil
20,2024,putusan_1741_Pid_Sus_2024_PN_Sby.pdf,putusan_1741_Pid_Sus_2024_PN_Sby.txt,16,49466,Berhasil
21,2024,putusan_1751_Pid_Sus_2024_PN_Sby.pdf,putusan_1751_Pid_Sus_2024_PN_Sby.txt,17,54044,Berhasil
22,2024,putusan_1846_Pid_Sus_2024_PN_Sby.pdf,putusan_1846_Pid_Sus_2024_PN_Sby.txt,19,60991,Berhasil
23,2024,putusan_1901_Pid_Sus_2024_PN_Sby.pdf,putusan_1901_Pid_Sus_2024_PN_Sby.txt,22,67918,Berhasil
24,2024,putusan_1904_Pid_Sus_2024_PN_Sby.pdf,putusan_1904_Pid_Sus_2024_PN_Sby.txt,24,73232,Berhasil
25,2024,putusan_1968_Pid_Sus_2024_PN_Sby.pdf,putusan_1968_Pid_Sus_2024_PN_Sby.txt,18,55935,Berhasil
26,2024,putusan_2010_Pid_Sus_2024_PN_Sby.pdf,putusan_2010_Pid_Sus_2024_PN_Sby.txt,35,111328,Berhasil
27,2024,putusan_2017_Pid_Sus_2024_PN_Sby.pdf,putusan_2017_Pid_Sus_2024_PN_Sby.txt,21,63676,Berhasil
28,2024,putusan_2050_Pid_Sus_2024_PN_Sby.pdf,putusan_2050_Pid_Sus_2024_PN_Sby.txt,22,68526,Berhasil
29,2024,putusan_2054_Pid_Sus_2024_PN_Sby.pdf,putusan_2054_Pid_Sus_2024_PN_Sby.txt,18,55140,Berhasil
30,2024,putusan_2071_Pid_Sus_2024_PN_Sby.pdf,putusan_2071_Pid_Sus_2024_PN_Sby.txt,19,56030,Berhasil
31,2024,putusan_2127_Pid_Sus_2024_PN_Sby.pdf,putusan_2127_Pid_Sus_2024_PN_Sby.txt,25,82317,Berhasil
32,2024,putusan_2302_Pid_Sus_2024_PN_Sby.pdf,putusan_2302_Pid_Sus_2024_PN_Sby.txt,20,60865,Berhasil
33,2024,putusan_2454_Pid_Sus_2024_PN_Sby.pdf,putusan_2454_Pid_Sus_2024_PN_Sby.txt,23,71251,Berhasil
34,2024,putusan_891_Pid_Sus_2024_PN_Sby.pdf,putusan_891_Pid_Sus_2024_PN_Sby.txt,16,51689,Berhasil
35,2024,putusan_898_Pid_Sus_2024_PN_Sby.pdf,putusan_898_Pid_Sus_2024_PN_Sby.txt,25,77127,Berhasil
36,2025,putusan_1668_Pid_Sus_2025_PN_Sby.pdf,putusan_1668_Pid_Sus_2025_PN_Sby.txt,26,76918,Berhasil
37,2025,putusan_1773_Pid_Sus_2025_PN_Sby.pdf,putusan_1773_Pid_Sus_2025_PN_Sby.txt,34,106051,Berhasil
38,2025,putusan_1789_Pid_Sus_2025_PN_Sby.pdf,putusan_1789_Pid_Sus_2025_PN_Sby.txt,23,69569,Berhasil
39,2025,putusan_1852_Pid_Sus_2025_PN_Sby.pdf,putusan_1852_Pid_Sus_2025_PN_Sby.txt,21,65014,Berhasil
40,2025,putusan_1880_Pid_Sus_2025_PN_Sby.pdf,putusan_1880_Pid_Sus_2025_PN_Sby.txt,27,82225,Berhasil
41,2025,putusan_1895_Pid_Sus_2025_PN_Sby.pdf,putusan_1895_Pid_Sus_2025_PN_Sby.txt,28,93550,Berhasil
42,2025,putusan_1930_Pid_Sus_2025_PN_Sby.pdf,putusan_1930_Pid_Sus_2025_PN_Sby.txt,44,142553,Berhasil
43,2025,putusan_1949_Pid_Sus_2025_PN_Sby.pdf,putusan_1949_Pid_Sus_2025_PN_Sby.txt,27,83086,Berhasil
44,2025,putusan_1965_Pid_Sus_2025_PN_Sby.pdf,putusan_1965_Pid_Sus_2025_PN_Sby.txt,18,54245,Berhasil
45,2025,putusan_2101_Pid_Sus_2025_PN_Sby.pdf,putusan_2101_Pid_Sus_2025_PN_Sby.txt,20,66374,Berhasil
46,2025,putusan_2109_Pid_Sus_2025_PN_Sby.pdf,putusan_2109_Pid_Sus_2025_PN_Sby.txt,15,44283,Berhasil
47,2025,putusan_222_Pid_Sus_2025_PN_Sby.pdf,putusan_222_Pid_Sus_2025_PN_Sby.txt,33,104482,Berhasil
48,2025,putusan_482_Pid_Sus_2025_PN_Sby.pdf,putusan_482_Pid_Sus_2025_PN_Sby.txt,50,160987,Berhasil
49,2025,putusan_579_Pid_Sus_2025_PN_Sby.pdf,putusan_579_Pid_Sus_2025_PN_Sby.txt,26,82325,Berhasil

10. Simpan laporan hasil ekstraksi

In [ ]:
laporan_path = os.path.join(
    BASE_DIR,
    'laporan_pdf_to_txt.csv'
)

df_hasil.to_csv(laporan_path, index=False)

print("Laporan berhasil disimpan!")
print("Lokasi:", laporan_path)

print("\nRingkasan:")
print("Total PDF diproses:", len(df_hasil))
print("TXT berhasil:", (df_hasil['Status'] == 'Berhasil').sum())
print("Teks kosong:", (df_hasil['Status'] == 'Teks Kosong').sum())
print("Error:", df_hasil['Status'].str.startswith('Error').sum())

Laporan berhasil disimpan!
Lokasi: /content/drive/MyDrive/Semester 7/Information Retrieval/UTS - KELOMPOK/CRAWLING/laporan_pdf_to_txt.csv

Ringkasan:
Total PDF diproses: 50
TXT berhasil: 50
Teks kosong: 0
Error: 0

11. periksa jumlah TXT

In [ ]:
for tahun in ['2023', '2024', '2025']:

    folder = os.path.join(TXT_DIR, tahun)

    jumlah_txt = len([
        f for f in os.listdir(folder)
        if f.lower().endswith('.txt')
    ])

    print(f'{tahun}: {jumlah_txt} TXT')

total_txt = sum(
    len([
        f for f in os.listdir(os.path.join(TXT_DIR, tahun))
        if f.lower().endswith('.txt')
    ])
    for tahun in ['2023', '2024', '2025']
)

print("\nTotal TXT:", total_txt)

2023: 17 TXT
2024: 19 TXT
2025: 14 TXT

Total TXT: 50

12. Periksa nama file TXT berdasarkan tahun

In [ ]:
for tahun in ['2023', '2024', '2025']:
    folder = os.path.join(TXT_DIR, tahun)

    print(f"\nFolder {tahun}")

    for file in sorted(os.listdir(folder)):
        if file.endswith('.txt'):
            print(file)

Folder 2023
putusan_1024_Pid_Sus_2023_PN_Sby.txt
putusan_140_Pid_Sus_2023_PN_Sby.txt
putusan_1512_Pid_Sus_2023_PN_Sby.txt
putusan_1880_Pid_Sus_2023_PN_Sby.txt
putusan_1982_Pid_Sus_2023_PN_Sby.txt
putusan_2031_Pid_Sus_2023_PN_Sby.txt
putusan_2043_Pid_Sus_2023_PN_Sby.txt
putusan_2047_Pid_Sus_2023_PN_Sby.txt
putusan_2166_Pid_Sus_2023_PN_Sby.txt
putusan_2189_Pid_Sus_2023_PN_Sby.txt
putusan_2258_Pid_Sus_2023_PN_Sby.txt
putusan_2260_Pid_Sus_2023_PN_Sby.txt
putusan_2274_Pid_Sus_2023_PN_Sby.txt
putusan_2325_Pid_Sus_2023_PN_Sby.txt
putusan_2359_Pid_Sus_2023_PN_Sby.txt
putusan_2438_Pid_Sus_2023_PN_Sby.txt
putusan_270_Pid_Sus_2023_PN_Sby.txt

Folder 2024
putusan_1068_Pid_Sus_2024_PN_Sby.txt
putusan_1276_Pid_Sus_2024_PN_Sby.txt
putusan_1629_Pid_Sus_2024_PN_Sby.txt
putusan_1741_Pid_Sus_2024_PN_Sby.txt
putusan_1751_Pid_Sus_2024_PN_Sby.txt
putusan_1846_Pid_Sus_2024_PN_Sby.txt
putusan_1901_Pid_Sus_2024_PN_Sby.txt
putusan_1904_Pid_Sus_2024_PN_Sby.txt
putusan_1968_Pid_Sus_2024_PN_Sby.txt
putusan_2010_Pid_Sus_2024_PN_Sby.txt
putusan_2017_Pid_Sus_2024_PN_Sby.txt
putusan_2050_Pid_Sus_2024_PN_Sby.txt
putusan_2054_Pid_Sus_2024_PN_Sby.txt
putusan_2071_Pid_Sus_2024_PN_Sby.txt
putusan_2127_Pid_Sus_2024_PN_Sby.txt
putusan_2302_Pid_Sus_2024_PN_Sby.txt
putusan_2454_Pid_Sus_2024_PN_Sby.txt
putusan_891_Pid_Sus_2024_PN_Sby.txt
putusan_898_Pid_Sus_2024_PN_Sby.txt

Folder 2025
putusan_1668_Pid_Sus_2025_PN_Sby.txt
putusan_1773_Pid_Sus_2025_PN_Sby.txt
putusan_1789_Pid_Sus_2025_PN_Sby.txt
putusan_1852_Pid_Sus_2025_PN_Sby.txt
putusan_1880_Pid_Sus_2025_PN_Sby.txt
putusan_1895_Pid_Sus_2025_PN_Sby.txt
putusan_1930_Pid_Sus_2025_PN_Sby.txt
putusan_1949_Pid_Sus_2025_PN_Sby.txt
putusan_1965_Pid_Sus_2025_PN_Sby.txt
putusan_2101_Pid_Sus_2025_PN_Sby.txt
putusan_2109_Pid_Sus_2025_PN_Sby.txt
putusan_222_Pid_Sus_2025_PN_Sby.txt
putusan_482_Pid_Sus_2025_PN_Sby.txt
putusan_579_Pid_Sus_2025_PN_Sby.txt

13. Periksa TXT kosong

In [ ]:
txt_kosong = []

for tahun in ['2023', '2024', '2025']:
    folder = os.path.join(TXT_DIR, tahun)

    for nama_file in os.listdir(folder):
        if nama_file.lower().endswith('.txt'):
            path = os.path.join(folder, nama_file)

            with open(path, 'r', encoding='utf-8') as f:
                teks = f.read()

            if not teks.strip():
                txt_kosong.append(nama_file)

print("Jumlah TXT kosong:", len(txt_kosong))
print("Daftar TXT kosong:", txt_kosong)

Jumlah TXT kosong: 0
Daftar TXT kosong: []

14. Periksa kesesuaian nama PDF dan TXT

In [ ]:
pdf_names = {
    os.path.splitext(os.path.basename(p))[0]
    for p in pdf_files
}

txt_names = set()

for tahun in ['2023', '2024', '2025']:
    folder = os.path.join(TXT_DIR, tahun)

    for file in os.listdir(folder):
        if file.lower().endswith('.txt'):
            txt_names.add(os.path.splitext(file)[0])

pdf_tanpa_txt = pdf_names - txt_names
txt_tanpa_pdf = txt_names - pdf_names

print("PDF tanpa TXT:", len(pdf_tanpa_txt))
print("TXT tanpa PDF:", len(txt_tanpa_pdf))

print("\nPDF tanpa pasangan TXT:", pdf_tanpa_txt)
print("TXT tanpa pasangan PDF:", txt_tanpa_pdf)

PDF tanpa TXT: 0
TXT tanpa PDF: 0

PDF tanpa pasangan TXT: set()
TXT tanpa pasangan PDF: set()

15. Periksa ringkasan akhir

In [ ]:
print("===== RINGKASAN DATASET =====")

print("Total PDF:", len(pdf_files))
print("Total TXT:", len(txt_names))

print("TXT berhasil:",
      (df_hasil['Status'] == 'Berhasil').sum())

print("TXT kosong:",
      (df_hasil['Status'] == 'Teks Kosong').sum())

print("Error:",
      df_hasil['Status'].str.startswith('Error').sum())

===== RINGKASAN DATASET =====
Total PDF: 50
Total TXT: 50
TXT berhasil: 50
TXT kosong: 0
Error: 0

16. Validasi sampel PDF dan TXT

In [ ]:
import random
import os
import fitz

# Ambil 5 PDF secara acak
sampel_pdf = random.sample(pdf_files, min(5, len(pdf_files)))

for path_pdf in sampel_pdf:
    nama_file = os.path.basename(path_pdf)
    tahun = next(
        (t for t in ['2023', '2024', '2025'] if f'_{t}_' in nama_file),
        None
    )

    nama_txt = os.path.splitext(nama_file)[0] + '.txt'
    path_txt = os.path.join(TXT_DIR, tahun, nama_txt)

    # Ekstraksi teks langsung dari PDF
    with fitz.open(path_pdf) as dokumen:
        teks_pdf = '\n'.join(
            halaman.get_text("text") for halaman in dokumen
        )

    # Membaca file TXT
    with open(path_txt, 'r', encoding='utf-8') as f:
        teks_txt = f.read()

    print("=" * 70)
    print("Nama file:", nama_file)
    print("PDF ditemukan:", os.path.exists(path_pdf))
    print("TXT ditemukan:", os.path.exists(path_txt))
    print("Panjang teks PDF:", len(teks_pdf))
    print("Panjang teks TXT:", len(teks_txt))
    print("\nContoh teks TXT:")
    print(teks_txt[:500])

======================================================================
Nama file: putusan_2127_Pid_Sus_2024_PN_Sby.pdf
PDF ditemukan: True
TXT ditemukan: True
Panjang teks PDF: 82317
Panjang teks TXT: 82317

Contoh teks TXT:
hkama
ahkamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 2127/Pid.Sus/2024/PN Sby
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Terdakwa :
1. Nama lengkap
: Indra Iswanto Bin Slamet
2. Tempa
======================================================================
Nama file: putusan_1901_Pid_Sus_2024_PN_Sby.pdf
PDF ditemukan: True
TXT ditemukan: True
Panjang teks PDF: 67918
Panjang teks TXT: 67918

Contoh teks TXT:
hkama
ahkamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 1901/Pid.Sus/2024/PN Sby
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Terdakwa :
Nama lengkap
:
Masduqi Zakaria Bin Alimun (Alm)
======================================================================
Nama file: putusan_1024_Pid_Sus_2023_PN_Sby.pdf
PDF ditemukan: True
TXT ditemukan: True
Panjang teks PDF: 190739
Panjang teks TXT: 190739

Contoh teks TXT:
hkama
ahkamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
Halaman 1 dari 60 Putusan Nomor 1024/Pid.Sus/2023/PN Sby

P U T U S A N
Nomor 1024/Pid.Sus/2023/PN Sby

DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA

Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam pe
======================================================================
Nama file: putusan_1904_Pid_Sus_2024_PN_Sby.pdf
PDF ditemukan: True
TXT ditemukan: True
Panjang teks PDF: 73232
Panjang teks TXT: 73232

Contoh teks TXT:
hkama
ahkamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 1904/Pid.Sus/2024/PN Sby
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Terdakwa :
Nama lengkap
: MIFTAHUL ROHMAN bin KOSIM;
Tem
======================================================================
Nama file: putusan_2260_Pid_Sus_2023_PN_Sby.pdf
PDF ditemukan: True
TXT ditemukan: True
Panjang teks PDF: 53834
Panjang teks TXT: 53834

Contoh teks TXT:
hkama
ahkamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 2260/Pid.Sus/2023/PN Sby
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Terdakwa :
Nama lengkap
: Moh. Arif Bin Moh. Slamed
Tempat lah

# 17. Audit dan Ekstraksi Metadata Putusan

## 17.1 Konfigurasi Direktori Repository

In [3]:
import os
import re
import pandas as pd
from pathlib import Path

BASE_DIR = "/content/Dataset-Narkotika_027_199"

PDF_DIR = os.path.join(BASE_DIR, "PDF_Putusan")
TXT_DIR = os.path.join(BASE_DIR, "TXT_Putusan")
DATA_DIR = os.path.join(BASE_DIR, "data")

print("===== KONFIGURASI DIREKTORI =====")
print("BASE_DIR :", BASE_DIR)
print("PDF_DIR  :", PDF_DIR)
print("TXT_DIR  :", TXT_DIR)
print("DATA_DIR :", DATA_DIR)

assert os.path.exists(BASE_DIR), "Repository tidak ditemukan."
assert os.path.exists(TXT_DIR), "Folder TXT_Putusan tidak ditemukan."

===== KONFIGURASI DIREKTORI =====
BASE_DIR : /content/Dataset-Narkotika_027_199
PDF_DIR  : /content/Dataset-Narkotika_027_199/PDF_Putusan
TXT_DIR  : /content/Dataset-Narkotika_027_199/TXT_Putusan
DATA_DIR : /content/Dataset-Narkotika_027_199/data

## 17.2 Audit Jumlah dan Kelengkapan File TXT

In [4]:
documents = []

for file_path in sorted(Path(TXT_DIR).rglob("*.txt")):

    with open(file_path, "r", encoding="utf-8", errors="replace") as f:
        isi_putusan = f.read()

    documents.append({
        "nama_file": file_path.name,
        "tahun_folder": file_path.parent.name,
        "jumlah_karakter": len(isi_putusan),
        "isi_putusan": isi_putusan
    })

df_audit = pd.DataFrame(documents)

print("===== HASIL AUDIT FILE TXT =====")
print("Total dokumen:", len(df_audit))

print("\nJumlah dokumen per tahun:")
print(df_audit["tahun_folder"].value_counts().sort_index())

print("\nDokumen kosong:")
print((df_audit["jumlah_karakter"] == 0).sum())

print("\nDokumen dengan kurang dari 1.000 karakter:")
print((df_audit["jumlah_karakter"] < 1000).sum())

===== HASIL AUDIT FILE TXT =====
Total dokumen: 50

Jumlah dokumen per tahun:
tahun_folder
2023    17
2024    19
2025    14
Name: count, dtype: int64

Dokumen kosong:
0

Dokumen dengan kurang dari 1.000 karakter:
0

## 17.3 Melihat Sampel Hasil Pembacaan TXT

In [5]:
for doc in documents[:2]:
    print("=" * 100)
    print("Nama file:", doc["nama_file"])
    print("Tahun:", doc["tahun_folder"])
    print("Jumlah karakter:", doc["jumlah_karakter"])
    print("\nIsi dokumen:")
    print(doc["isi_putusan"][:1500])

====================================================================================================
Nama file: putusan_1024_Pid_Sus_2023_PN_Sby.txt
Tahun: 2023
Jumlah karakter: 190739

Isi dokumen:
hkama
ahkamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
Halaman 1 dari 60 Putusan Nomor 1024/Pid.Sus/2023/PN Sby

P U T U S A N
Nomor 1024/Pid.Sus/2023/PN Sby

DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA

Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Para Terdakwa :
Terdakwa 1
1.  Nama lengkap
: Surya Aji Pratama Bin Darmawan
2.  Tempat lahir
: Mojokerto
3.  Umur/Tanggal lahir
: 31 Tahun / 24 Mei 1992
4.  Jenis kelamin
: Laki-laki
5.  Kebangsaan
: Indonesia
6.  Tempat tinggal
: Dsn. Kalijaring, RT 004 / RW 007, Ds. Mlirip, Kec.
Jetis,
Kab.
Mojokerto
(sesuai
NIK
3516162405920006) atau bertempat tinggal di Jl.
Kebraon Indah Permai, Kel. Kebraon, Kec. Karang
Pilang, Kota Surabaya
7.  Agama
: Islam
8.  Pekerjaan
: Tukang batu

Terdakwa Surya Aji Pratama Bin Darmawan ditahan dalam tahanan rutan oleh:
1.  Penyidik sejak tanggal 4 Februari 2023 sampai dengan tanggal 23 Februari
2023
2.  Penyidik Perpanjangan Oleh Penuntut Umum sejak tanggal 24 Februari 2023
sampai dengan tanggal 4 April 2023
3.  Penuntut Umum sejak tanggal 4 April 2023 sampai dengan tanggal 23 April
2023
4.  Penuntut Umum Perpanjangan Oleh Ketua Pengadilan Negeri (Pasal 25)
sejak tanggal 24 April 2023 sampai dengan tang
====================================================================================================
Nama file: putusan_140_Pid_Sus_2023_PN_Sby.txt
Tahun: 2023
Jumlah karakter: 63029

Isi dokumen:
hkama
ahkamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 140/Pid.Sus/2023/PN Sby
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Terdakwa :
Nama lengkap
: Andika Fajar Yulisetiawan Bin Abdul Choir;
Tempat lahir
: Surabaya;
Umur/tanggal lahir  : 28 Tahun / 21 Januari 1994;
Jenis Kelamin
: Laki-laki;
Kebangsaan
: Indonesia;
Tempat tinggal
: Jl.Arif Mahmud Gg.III A No.12 G Kec Gunung
Anyar Surabaya;
Agama
: Islam;
Pekerjaan
: Karyawan Swasta;
Terdakwa Andika Fajar Yulisetiawan Bin Abdul Choir ditahan dalam tahanan
rutan oleh:
1.
Penyidik sejak tanggal 03 November 2022 sampai dengan tanggal 22
November 2022;
2.
Penyidik Perpanjangan Oleh PU sejak tanggal 23 November 2022 sampai
dengan tanggal 01 Januari 2023;
3.
Penyidik Perpanjangan Pertama Oleh Ketua PN sejak tanggal 02 Januari
2023 sampai dengan tanggal 31 Januari 2023;
4.
Penuntut sejak tanggal 16 Januari 2023 sampai dengan tanggal 04 Februari
2023;
5.
Hakim Pengadilan Negeri sejak tanggal 19 Januari 2023 sampai dengan
tanggal 17 Pebruari 2023;
6.
Hakim Pengadilan Negeri Perpanjangan Pertama Oleh Ketua Pengadilan
Negeri sejak tanggal 18 Pebruari 2023 sampai deng

## 17.9 Pengujian Ekstraksi Amar Putusan dan Barang Bukti

In [80]:
def ekstrak_amar_dan_barang_bukti(teks):

    # 1. Ekstraksi amar putusan
    pola_amar = r"M\s*E\s*N\s*G\s*A\s*D\s*I\s*L\s*I"

    hasil_amar = list(
        re.finditer(pola_amar, teks, re.IGNORECASE)
    )

    bagian_amar = None

    if hasil_amar:
        posisi_awal = hasil_amar[-1].start()
        bagian_amar = teks[posisi_awal:]

        hasil_disclaimer = re.search(
            r"Disclaimer",
            bagian_amar,
            re.IGNORECASE
        )

        if hasil_disclaimer:
            bagian_amar = bagian_amar[:hasil_disclaimer.start()]

    # 2. Pola barang bukti
    pola_bb = (
        r"(?:"
        r"Menyatakan|Menetapkan|Memerintahkan"
        r")\s+barang(?:-barang)?\s+bukti\s+berupa"
        r"|"
        r"Penuntut\s+Umum\s+mengajukan\s+barang(?:-barang)?\s+bukti"
        r"\s+sebagai\s+berikut"
        r"|"
        r"ditemukan\s+(?:adanya\s+)?barang\s+bukti"
        r"\s+berupa"
    )

    hasil_bb = list(
        re.finditer(
            pola_bb,
            teks,
            re.IGNORECASE
        )
    )

    barang_bukti = None

    if hasil_bb:

        # Ambil pola terakhir agar mengutamakan bagian amar akhir
        hasil = hasil_bb[-1]

        awal_bb = hasil.start()
        bagian_bb = teks[hasil.end():]

        # 3. Membatasi bagian barang bukti
        akhir_bb = re.search(
            r"\n\s*(?:"
            r"Menimbang\s*,|"
            r"Memperhatikan\s*,|"
            r"MENGADILI\s*:?|"
            r"M\s*E\s*N\s*G\s*A\s*D\s*I\s*L\s*I|"
            r"Demikianlah?\s+(?:diputuskan|diucapkan)"
            r")",
            bagian_bb,
            re.IGNORECASE
        )

        if akhir_bb:
            bagian_bb = bagian_bb[:akhir_bb.start()]

        barang_bukti = (
            teks[awal_bb:hasil.end()] + bagian_bb
        ).strip()

    return {
        "amar_putusan": bagian_amar.strip() if bagian_amar else None,
        "barang_bukti": barang_bukti
    }



# 4. Pengujian pada tiga dokumen sampel

for doc in documents:

    if doc["nama_file"] in sampel_putusan:

        hasil = ekstrak_amar_dan_barang_bukti(
            doc["isi_putusan"]
        )

        print("\n" + "=" * 80)
        print("FILE:", doc["nama_file"])
        print("=" * 80)

        print("\n--- BARANG BUKTI ---")
        print(hasil["barang_bukti"])

        print("\n--- AMAR PUTUSAN ---")
        print(hasil["amar_putusan"])

================================================================================
FILE: putusan_1024_Pid_Sus_2023_PN_Sby.txt
================================================================================

--- BARANG BUKTI ---
Menetapkan barang bukti berupa :
-
1 (satu) bungkus plastik klip di duga berisi Narkotika jenis Sabu dengan
berat kotor seluruhnya 1,00 gram.
-
1 (satu) buah bungkus rokok merk Dji Sam Soe
-
1 (satu) unit Handphone merk Oppo warna hitam dengan no simcard
081284269551.
-
10 (sepuluh) bungkus plastik klip diduga berisi Narkotika jenis sabu
dengan berat kotor 7,02 (tujuh koma nol dua) gram.
-
4 (empat) buah bungkus rokok.
Disclaimer
Kepaniteraan Mahkamah Agung Republik Indonesia berusaha untuk selalu mencantumkan informasi paling kini dan akurat sebagai bentuk komitmen Mahkamah Agung untuk pelayanan publik, transparansi dan akuntabilitas
pelaksanaan fungsi peradilan. Namun dalam hal-hal tertentu masih dimungkinkan terjadi permasalahan teknis terkait dengan akurasi dan keterkinian informasi yang kami sajikan, hal mana akan terus kami perbaiki dari waktu kewaktu.
Dalam hal Anda menemukan inakurasi informasi yang termuat pada situs ini atau informasi yang seharusnya ada, namun belum tersedia, maka harap segera hubungi Kepaniteraan Mahkamah Agung RI melalui :
Email : kepaniteraan@mahkamahagung.go.id    Telp : 021-384 3348 (ext.318)
Halaman 59

hkama
ahkamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
Halaman 60 dari 60 Putusan Nomor 1024/Pid.Sus/2023/PN Sby

-
1 (satu) unit timbangan elektrik warna hitam
-
1 (satu) buah sekrop dari sedotan plastik warna hitam
-
1 (satu) bendel plastik klip kosong
dirampas untuk dimusnahkan
6. Membebankan kepada Para Terdakwa untuk membayar biaya perkara
masing-masing sebesar Rp. 5.000,- (lima ribu rupiah) ;

--- AMAR PUTUSAN ---
M E N G A D I L I
1. Menyatakan Terdakwa I SURYA AJI PRATAMA bin DARMAWAN dan
Terdakwa II SATRIYO WAHYUNING GUSTI als TIO bin EKO SUPRIYADI
telah terbukti secara sah dan meyakinkan bersalah melakukan tindak pidana,
“pemufakatan jahat untuk menerima, menjual dan menyerahkan
Narkotika Golongan I bukan tanaman yang beratnya melebihi dari 5
(lima) gram” ;
2. Menjatuhkan pidana kepada Terdakwa I dan Terdakwa tersebut diatas oleh
karena itu dengan pidana penjara masing-masing selama : 5 (lima) Tahun
6 (enam) bulan denda masing-masing sebesar Rp. 1.000.000.000,- (satu
milyar rupiah) dengan ketentuan apabila denda tidak dibayar akan diganti
dengan pidana penjara selama : 2 (dua) bulan;
3. Menetapkan masa penangkapan dan penahanan yang telah dijalani oleh
Para Terdakwa dikurangkan seluruhnya dari pidana yang dijatuhkan ;
4. Menetapkan Para Terdakwa tetap berada dalam tahanan ;
5. Menetapkan barang bukti berupa :
-
1 (satu) bungkus plastik klip di duga berisi Narkotika jenis Sabu dengan
berat kotor seluruhnya 1,00 gram.
-
1 (satu) buah bungkus rokok merk Dji Sam Soe
-
1 (satu) unit Handphone merk Oppo warna hitam dengan no simcard
081284269551.
-
10 (sepuluh) bungkus plastik klip diduga berisi Narkotika jenis sabu
dengan berat kotor 7,02 (tujuh koma nol dua) gram.
-
4 (empat) buah bungkus rokok.

================================================================================
FILE: putusan_2071_Pid_Sus_2024_PN_Sby.txt
================================================================================

--- BARANG BUKTI ---
Memerintahkan barang bukti berupa:
-
1 (satu) Klip Narkotika Jenis Sabu dengan Berat Kotor 34,95 (tiga puluh
empat koma sembilan puluh lima) gram ;
-
1 (satu) buah timbangan digital;
-
2 (dua) buah skrup dari sedotan;
-
2 (dua) plastik klip yang berisikan plastic klip kecil;
-
1 (satu) buah Hp Realme C21Y warna Hitam dengan no simcard
081332902339;
-
1 (satu) Box Hp Realme Warna Kuning;
-
Seperangkat alat hisab sabu;
Dirampas untuk dimusnahkan
6.
Membebankan kepada Terdakwa untuk membayar biaya perkara sebesar
Rp 5.000,00 (lima ribu rupiah);
Demikian diputuskan dalam Musyawarah Majelis Hakim Pengadilan
Negeri Surabaya, pada hari Selasa, tanggal 26 November 2024 oleh kami NI
PUTU SRI INDAYANI,S.H.,M.H., sebagai Hakim Ketua sidang didampingi oleh
EDI SAPUTRA PELAWI,S.H.,M.H. dan FERDINAND MARCUS LEANDER,
S.H.,M.H. masing-masing sebagai Hakim Anggota, yang ditunjuk berdasarkan
Halaman 18 Putusan Nomor  2071/Pid.Sus/2024/PN.Sby.

Disclaimer
Kepaniteraan Mahkamah Agung Republik Indonesia berusaha untuk selalu mencantumkan informasi paling kini dan akurat sebagai bentuk komitmen Mahkamah Agung untuk pelayanan publik, transparansi dan akuntabilitas
pelaksanaan fungsi peradilan. Namun dalam hal-hal tertentu masih dimungkinkan terjadi permasalahan teknis terkait dengan akurasi dan keterkinian informasi yang kami sajikan, hal mana akan terus kami perbaiki dari waktu kewaktu.
Dalam hal Anda menemukan inakurasi informasi yang termuat pada situs ini atau informasi yang seharusnya ada, namun belum tersedia, maka harap segera hubungi Kepaniteraan Mahkamah Agung RI melalui :
Email : kepaniteraan@mahkamahagung.go.id    Telp : 021-384 3348 (ext.318)
Halaman 18

hkama
ahkamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
Surat Penetapan Ketua Pengadilan Negeri
 Surabaya,
Nomor
2071/Pid.Sus/2024/PN.Sby. tanggal 23 Oktober 2024, Putusan tersebut
diucapkan dalam sidang yang terbuka untuk umum pada hari Selasa, tanggal 3
Desember 2024, oleh Hakim Ketua dengan didampingi oleh Hakim Anggota,
dibantu oleh ACHMAD FAJARISMAN,S.Kom.,SH.,MH., Panitera Pengganti
pada Pengadilan Negeri tersebut, dihadiri LUJENG ANDAYANI,S.H., Penuntut
Umum pada Kejaksaan Negeri Surabaya dan Terdakwa didampingi oleh
Penasihat Hukumnya;
               Hakim Anggota,                                               Hakim Ketua,
EDI SAPUTRA PELAWI,

 S  . H.,M.H

 .                 NI PUTU SRI INDAYANI,S.H.,M.H.
FERDINAND MARCUS LEANDER

 ,S
  . H.
  ,M.H


                                                                Panitera Pengganti,
                                              ACHMAD FAJARISMAN,S.Kom.,SH.,MH.
Halaman 19 Putusan Nomor  2071/Pid.Sus/2024/PN.Sby.

Disclaimer
Kepaniteraan Mahkamah Agung Republik Indonesia berusaha untuk selalu mencantumkan informasi paling kini dan akurat sebagai bentuk komitmen Mahkamah Agung untuk pelayanan publik, transparansi dan akuntabilitas
pelaksanaan fungsi peradilan. Namun dalam hal-hal tertentu masih dimungkinkan terjadi permasalahan teknis terkait dengan akurasi dan keterkinian informasi yang kami sajikan, hal mana akan terus kami perbaiki dari waktu kewaktu.
Dalam hal Anda menemukan inakurasi informasi yang termuat pada situs ini atau informasi yang seharusnya ada, namun belum tersedia, maka harap segera hubungi Kepaniteraan Mahkamah Agung RI melalui :
Email : kepaniteraan@mahkamahagung.go.id    Telp : 021-384 3348 (ext.318)
Halaman 19

--- AMAR PUTUSAN ---
M E N G A D I L I
1.
Menyatakan Terdakwa Prayogo Bayu Pamungkas Bin Bambang Prapto
Susilo, telah terbukti secara sah dan meyakinkan bersalah melakukan tindak
pidana “tanpa hak menawarkan untuk menerima,menjual atau menyerahkan
Narkotika Golongan I, yang beratnya lebih dari 5 gram ;
2.
Menjatuhkan pidana terhadap Terdakwa Prayogo Bayu Pamungkas Bin
Bambang Prapto Susilo, oleh karena itu dengan pidana penjara selama 10
(sepuluh) tahun  dan denda sejumlah Rp 1. 000.000.000,00 (satu milyar
rupiah), apabila denda tersebut tidak dibayar maka diganti dengan pidana
penjara selama 2 (dua) bulan ;
3.
Menetapkan masa penahanan yang telah dijalani Terdakwa dikurangkan
seluruhnya dari  pidana yang dijatuhkan;
4.
Menetapkan Terdakwa tetap berada dalam tahanan;
5.
Memerintahkan barang bukti berupa:
-
1 (satu) Klip Narkotika Jenis Sabu dengan Berat Kotor 34,95 (tiga puluh
empat koma sembilan puluh lima) gram ;
-
1 (satu) buah timbangan digital;
-
2 (dua) buah skrup dari sedotan;
-
2 (dua) plastik klip yang berisikan plastic klip kecil;
-
1 (satu) buah Hp Realme C21Y warna Hitam dengan no simcard
081332902339;
-
1 (satu) Box Hp Realme Warna Kuning;
-
Seperangkat alat hisab sabu;
Dirampas untuk dimusnahkan
6.
Membebankan kepada Terdakwa untuk membayar biaya perkara sebesar
Rp 5.000,00 (lima ribu rupiah);
Demikian diputuskan dalam Musyawarah Majelis Hakim Pengadilan
Negeri Surabaya, pada hari Selasa, tanggal 26 November 2024 oleh kami NI
PUTU SRI INDAYANI,S.H.,M.H., sebagai Hakim Ketua sidang didampingi oleh
EDI SAPUTRA PELAWI,S.H.,M.H. dan FERDINAND MARCUS LEANDER,
S.H.,M.H. masing-masing sebagai Hakim Anggota, yang ditunjuk berdasarkan
Halaman 18 Putusan Nomor  2071/Pid.Sus/2024/PN.Sby.

================================================================================
FILE: putusan_482_Pid_Sus_2025_PN_Sby.txt
================================================================================

--- BARANG BUKTI ---
Menetapkan barang bukti berupa :
-
1 (satu) buah handphone merk Oppo warna Hijau dengan nomor
082229528989;
-
1 (satu) buah handphone merk Oppo warna Hitam;
-
1 (satu) bungkus plastic klip berisi Narkotika jenis Sabu seberat ± 0,005
gram;
-
1 (satu) buah pipet kaca berisi sisa Narkotika jenis Sabu seberat ± 0,012
gram;
-
1 (satu) buah handphone merk Iphone XS Max warna Putih;
-
1 (satu) buah alat hisap Sabu;
Dirampas untuk dimusnahkan;
-
Uang tunai Rp. 40.000,-.
Disclaimer
Kepaniteraan Mahkamah Agung Republik Indonesia berusaha untuk selalu mencantumkan informasi paling kini dan akurat sebagai bentuk komitmen Mahkamah Agung untuk pelayanan publik, transparansi dan akuntabilitas
pelaksanaan fungsi peradilan. Namun dalam hal-hal tertentu masih dimungkinkan terjadi permasalahan teknis terkait dengan akurasi dan keterkinian informasi yang kami sajikan, hal mana akan terus kami perbaiki dari waktu kewaktu.
Dalam hal Anda menemukan inakurasi informasi yang termuat pada situs ini atau informasi yang seharusnya ada, namun belum tersedia, maka harap segera hubungi Kepaniteraan Mahkamah Agung RI melalui :
Email : kepaniteraan@mahkamahagung.go.id    Telp : 021-384 3348 (ext.318)
Halaman 49

hkama
ahkamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
Halaman 50 dari 50 Putusan No. 482/Pid.Sus/2025/PN.Cbd

Dirampas untuk negara;
6. Membebankan para terdakwa untuk membayar biaya perkara masing-
masing sebesar Rp 2.000,- (dua ribu rupiah);

--- AMAR PUTUSAN ---
M E N G A  D I L I :

1. Menyatakan Terdakwa I AISAH alias ICHA Binti JAMIL ROBI telah terbukti
secara sah dan meyakinkan bersalah melakukan tindak pidana :
“Permufakatan jahat untuk melakukan tindak pidana Narkotika dan Prekusor
Narkotika yang tanpa hak atau melawan hukum menjadi perantara dalam
jual beli Narkotika Golongan I“ dan menyatakan Terdakwa II ANANG
SUROTO alias EGOR Bin SUGITO dan Terdakwa III MOCH. TOYYEP Bin
MAT NASIR telah terbukti secara sah dan meyakinkan bersalah melakukan
tindak pidana : “Turut serta menyalahgunakan Narkotika Golongan I bagi diri
sendiri“;
2. Menjatuhkan pidana terhadap Terdakwa I AISAH alias ICHA Binti JAMIL
ROBI dengan pidana penjara selama 5 (lima) tahun dan denda sebesar Rp
1.000.000.000,- (satu milyar rupiah) dengan ketentuan apabila denda tidak
dibayar maka diganti dengan pidana penjara Selama 3 (tiga) bulan,
sedangkan terhadap Terdakwa II ANANG SUROTO alias EGOR Bin
SUGITO dan Terdakwa III MOCH. TOYYEP Bin MAT NASIR dengan pidana
penjara masing-masing selama 1 (satu) tahun;
3. Menetapkan masa penangkapan dan penahanan yang telah dijalani para
terdakwa dikurangkan seluruhnya dari pidana yang dijatuhkan;
4. Menetapkan agar para terdakwa tetap ditahan;
5. Menetapkan barang bukti berupa :
-
1 (satu) buah handphone merk Oppo warna Hijau dengan nomor
082229528989;
-
1 (satu) buah handphone merk Oppo warna Hitam;
-
1 (satu) bungkus plastic klip berisi Narkotika jenis Sabu seberat ± 0,005
gram;
-
1 (satu) buah pipet kaca berisi sisa Narkotika jenis Sabu seberat ± 0,012
gram;
-
1 (satu) buah handphone merk Iphone XS Max warna Putih;
-
1 (satu) buah alat hisap Sabu;
Dirampas untuk dimusnahkan;
-
Uang tunai Rp. 40.000,-.

## 17.10 — Pemeriksaan Kelengkapan Amar Putusan

In [81]:
for doc in documents:

    if doc["nama_file"] in sampel_putusan:

        teks = doc["isi_putusan"]

        hasil = ekstrak_amar_dan_barang_bukti(teks)

        print("\n" + "=" * 80)
        print("FILE:", doc["nama_file"])
        print("=" * 80)

        amar = hasil["amar_putusan"] or ""

        # Periksa status barang bukti
        pola_status = (
            r"Dirampas\s+untuk\s+dimusnahkan|"
            r"Dirampas\s+untuk\s+negara|"
            r"Dikembalikan\s+kepada|"
            r"Tetap\s+terlampir"
        )

        status = list(
            re.finditer(
                pola_status,
                amar,
                re.IGNORECASE
            )
        )

        print("\nJumlah status barang bukti:", len(status))

        for item in status:
            awal = max(0, item.start() - 250)
            akhir = min(len(amar), item.end() + 250)

            print("\n", amar[awal:akhir])

        # Periksa poin amar terakhir
        print("\n--- 1000 KARAKTER TERAKHIR AMAR ---")
        print(amar[-1000:])

================================================================================
FILE: putusan_1024_Pid_Sus_2023_PN_Sby.txt
================================================================================

Jumlah status barang bukti: 0

--- 1000 KARAKTER TERAKHIR AMAR ---
hi dari 5
(lima) gram” ;
2. Menjatuhkan pidana kepada Terdakwa I dan Terdakwa tersebut diatas oleh
karena itu dengan pidana penjara masing-masing selama : 5 (lima) Tahun
6 (enam) bulan denda masing-masing sebesar Rp. 1.000.000.000,- (satu
milyar rupiah) dengan ketentuan apabila denda tidak dibayar akan diganti
dengan pidana penjara selama : 2 (dua) bulan;
3. Menetapkan masa penangkapan dan penahanan yang telah dijalani oleh
Para Terdakwa dikurangkan seluruhnya dari pidana yang dijatuhkan ;
4. Menetapkan Para Terdakwa tetap berada dalam tahanan ;
5. Menetapkan barang bukti berupa :
-
1 (satu) bungkus plastik klip di duga berisi Narkotika jenis Sabu dengan
berat kotor seluruhnya 1,00 gram.
-
1 (satu) buah bungkus rokok merk Dji Sam Soe
-
1 (satu) unit Handphone merk Oppo warna hitam dengan no simcard
081284269551.
-
10 (sepuluh) bungkus plastik klip diduga berisi Narkotika jenis sabu
dengan berat kotor 7,02 (tujuh koma nol dua) gram.
-
4 (empat) buah bungkus rokok.

================================================================================
FILE: putusan_2071_Pid_Sus_2024_PN_Sby.txt
================================================================================

Jumlah status barang bukti: 1

 an digital;
-
2 (dua) buah skrup dari sedotan;
-
2 (dua) plastik klip yang berisikan plastic klip kecil;
-
1 (satu) buah Hp Realme C21Y warna Hitam dengan no simcard
081332902339;
-
1 (satu) Box Hp Realme Warna Kuning;
-
Seperangkat alat hisab sabu;
Dirampas untuk dimusnahkan
6.
Membebankan kepada Terdakwa untuk membayar biaya perkara sebesar
Rp 5.000,00 (lima ribu rupiah);
Demikian diputuskan dalam Musyawarah Majelis Hakim Pengadilan
Negeri Surabaya, pada hari Selasa, tanggal 26 November 2024 oleh kami NI
PUTU SRI INDA

--- 1000 KARAKTER TERAKHIR AMAR ---
hkan;
4.
Menetapkan Terdakwa tetap berada dalam tahanan;
5.
Memerintahkan barang bukti berupa:
-
1 (satu) Klip Narkotika Jenis Sabu dengan Berat Kotor 34,95 (tiga puluh
empat koma sembilan puluh lima) gram ;
-
1 (satu) buah timbangan digital;
-
2 (dua) buah skrup dari sedotan;
-
2 (dua) plastik klip yang berisikan plastic klip kecil;
-
1 (satu) buah Hp Realme C21Y warna Hitam dengan no simcard
081332902339;
-
1 (satu) Box Hp Realme Warna Kuning;
-
Seperangkat alat hisab sabu;
Dirampas untuk dimusnahkan
6.
Membebankan kepada Terdakwa untuk membayar biaya perkara sebesar
Rp 5.000,00 (lima ribu rupiah);
Demikian diputuskan dalam Musyawarah Majelis Hakim Pengadilan
Negeri Surabaya, pada hari Selasa, tanggal 26 November 2024 oleh kami NI
PUTU SRI INDAYANI,S.H.,M.H., sebagai Hakim Ketua sidang didampingi oleh
EDI SAPUTRA PELAWI,S.H.,M.H. dan FERDINAND MARCUS LEANDER,
S.H.,M.H. masing-masing sebagai Hakim Anggota, yang ditunjuk berdasarkan
Halaman 18 Putusan Nomor  2071/Pid.Sus/2024/PN.Sby.

================================================================================
FILE: putusan_482_Pid_Sus_2025_PN_Sby.txt
================================================================================

Jumlah status barang bukti: 1

 gkus plastic klip berisi Narkotika jenis Sabu seberat ± 0,005
gram;
-
1 (satu) buah pipet kaca berisi sisa Narkotika jenis Sabu seberat ± 0,012
gram;
-
1 (satu) buah handphone merk Iphone XS Max warna Putih;
-
1 (satu) buah alat hisap Sabu;
Dirampas untuk dimusnahkan;
-
Uang tunai Rp. 40.000,-.

--- 1000 KARAKTER TERAKHIR AMAR ---
nda sebesar Rp
1.000.000.000,- (satu milyar rupiah) dengan ketentuan apabila denda tidak
dibayar maka diganti dengan pidana penjara Selama 3 (tiga) bulan,
sedangkan terhadap Terdakwa II ANANG SUROTO alias EGOR Bin
SUGITO dan Terdakwa III MOCH. TOYYEP Bin MAT NASIR dengan pidana
penjara masing-masing selama 1 (satu) tahun;
3. Menetapkan masa penangkapan dan penahanan yang telah dijalani para
terdakwa dikurangkan seluruhnya dari pidana yang dijatuhkan;
4. Menetapkan agar para terdakwa tetap ditahan;
5. Menetapkan barang bukti berupa :
-
1 (satu) buah handphone merk Oppo warna Hijau dengan nomor
082229528989;
-
1 (satu) buah handphone merk Oppo warna Hitam;
-
1 (satu) bungkus plastic klip berisi Narkotika jenis Sabu seberat ± 0,005
gram;
-
1 (satu) buah pipet kaca berisi sisa Narkotika jenis Sabu seberat ± 0,012
gram;
-
1 (satu) buah handphone merk Iphone XS Max warna Putih;
-
1 (satu) buah alat hisap Sabu;
Dirampas untuk dimusnahkan;
-
Uang tunai Rp. 40.000,-.

## 17.11 Pemeriksaan Struktur Identitas Terdakwa dan Tanggal Putusan

In [82]:
pola_tanggal = (
    r"(?:diucapkan|diucapkan dalam sidang|"
    r"diucapkan dalam persidangan)"
)

for doc in documents:

    if doc["nama_file"] in sampel_putusan:

        teks = doc["isi_putusan"]

        print("\n" + "=" * 80)
        print("FILE:", doc["nama_file"])
        print("=" * 80)

        # 1. Pemeriksaan tanggal pengucapan
        print("\n--- TANGGAL PENGUCAPAN ---")

        matches = list(
            re.finditer(
                pola_tanggal,
                teks,
                re.IGNORECASE
            )
        )

        if matches:
            for match in matches[-3:]:
                awal = max(0, match.start() - 300)
                akhir = min(len(teks), match.end() + 700)
                print(teks[awal:akhir])
        else:
            print("Kata kunci pengucapan tidak ditemukan.")

        # 2. Pemeriksaan identitas terdakwa
        print("\n--- IDENTITAS TERDAKWA ---")

        bagian_awal = teks[:20000]

        pola_nama = (
            r"(?im)^\s*(?:Terdakwa\s+[IVX]+\s*)?"
            r"(?:\d+\.\s*)?"
            r"Nama(?:\s+Lengkap)?\s*:?"
        )

        nama_matches = list(
            re.finditer(
                pola_nama,
                bagian_awal
            )
        )

        print("Jumlah label identitas:", len(nama_matches))

        for i, match in enumerate(nama_matches, 1):
            awal = max(0, match.start() - 100)
            akhir = min(len(bagian_awal), match.end() + 350)

            print(f"\nIdentitas ke-{i}:")
            print(bagian_awal[awal:akhir])

================================================================================
FILE: putusan_1024_Pid_Sus_2023_PN_Sby.txt
================================================================================

--- TANGGAL PENGUCAPAN ---
rupiah) ;

Demikianlah diputuskan dalam sidang permusyawaratan Majelis Hakim
Pengadilan Negeri Surabaya, pada hari SENIN tanggal 10 JULI 2023 oleh kami,
Suswanti, S.H., M.Hum., sebagai Hakim Ketua, Sudar, S.H., M.Hum.,
Mochammad Djoenaidie, S.H., M.H. masing-masing sebagai Hakim Anggota,
yang diucapkan dalam sidang terbuka untuk umum pada hari itu juga oleh Hakim
Ketua dengan didampingi para Hakim Anggota tersebut, dibantu oleh Dhany Eko
Prasetyo, SE., SH., MM., M.Hum., Panitera Pengganti pada Pengadilan Negeri
Surabaya, serta dihadiri oleh Rista Erna Soelistiowati, S.H., Penuntut Umum,
Penasehat Hukum Terdakwa  dan Para Terdakwa;

Hakim Anggota,
Hakim Ketua,


Sudar, S.H., M.Hum.
                             Suswanti, S.H., M.Hum.


Mochammad Djoenaidie, S.H., M.H.

Panitera Pengganti,


Dhany Eko Prasetyo, SE., SH., MM., M.Hum.

Disclaimer
Kepaniteraan Mahkamah Agung Republik Indonesia berusaha untuk selalu mencantumkan informasi paling kini dan akurat sebagai ben

--- IDENTITAS TERDAKWA ---
Jumlah label identitas: 3

Identitas ke-1:
lam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Para Terdakwa :
Terdakwa 1
1.  Nama lengkap
: Surya Aji Pratama Bin Darmawan
2.  Tempat lahir
: Mojokerto
3.  Umur/Tanggal lahir
: 31 Tahun / 24 Mei 1992
4.  Jenis kelamin
: Laki-laki
5.  Kebangsaan
: Indonesia
6.  Tempat tinggal
: Dsn. Kalijaring, RT 004 / RW 007, Ds. Mlirip, Kec.
Jetis,
Kab.
Mojokerto
(sesuai
NIK
3516162405920006) atau bertempat tinggal di Jl.
Kebraon

Identitas ke-2:
Pengadilan Negeri sejak
tanggal 14 Juni 2023 sampai dengan tanggal 12 Agustus 2023

Terdakwa 2
1.  Nama lengkap
: Satriyo Wahyuning Gusti als Tio Bin Eko Supriyadi
          Pid.I.A.3
Disclaimer
Kepaniteraan Mahkamah Agung Republik Indonesia berusaha untuk selalu mencantumkan informasi paling kini dan akurat sebagai bentuk komitmen Mahkamah Agung untuk pelayanan publik, transparansi dan akuntabilitas
pelaksanaan fungsi peradilan. Namun dalam hal-hal tertent

Identitas ke-3:
engan cara transfer
kepada Sdr. BOKIR melalui aplikasi DANA dengan akun nomor
085852510952
atas
nama
YUSRIL IZA MAIHENDRA sebesar
Rp.300.000,-(tiga ratus ribu rupiah).
-
Bahwa pada sekitar pukul 09.00 wib Sdr. PAM PAM menelepon melalui
WA dengan Nomor +12178346956 ke HP terdakwa SURYA AJI
PRATAMA Bin DARMAWAN dan diterima oleh terdakwa SATRIO
WAHYUNING GUSTI als TIO Bin EKO SUPRIADI dimana Sdr. PAM
PAM menawarkan Narkotika jenis sabu sehar

================================================================================
FILE: putusan_2071_Pid_Sus_2024_PN_Sby.txt
================================================================================

--- TANGGAL PENGUCAPAN ---
kamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
Surat Penetapan Ketua Pengadilan Negeri
 Surabaya,
Nomor
2071/Pid.Sus/2024/PN.Sby. tanggal 23 Oktober 2024, Putusan tersebut
diucapkan dalam sidang yang terbuka untuk umum pada hari Selasa, tanggal 3
Desember 2024, oleh Hakim Ketua dengan didampingi oleh Hakim Anggota,
dibantu oleh ACHMAD FAJARISMAN,S.Kom.,SH.,MH., Panitera Pengganti
pada Pengadilan Negeri tersebut, dihadiri LUJENG ANDAYANI,S.H., Penuntut
Umum pada Kejaksaan Negeri Surabaya dan Terdakwa didampingi oleh
Penasihat Hukumnya;
               Hakim Anggota,                                               Hakim Ketua,
EDI SAPUTRA PELAWI,

 S  . H.,M.H

 .                 NI PUTU SRI INDAYANI,S.H.,M.H.
FERDINAND MARCUS LEANDER

 ,S
  . H.
  ,M.H


                                                                Panitera Pengganti,


--- IDENTITAS TERDAKWA ---
Jumlah label identitas: 1

Identitas ke-1:
pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara terdakwa:
1.
Nama                            :
PRAYOGO BAYU PAMUNGKAS Bin
BAMBANG PRAPTO SUSILO ;
2.
Tempat Lahir
:
Mojokerto ;
3.
Umur/Tanggal Lahir
:
25 tahun / 7 Desember 1998 ;
4.
Jenis Kelamin
:
Laki - laki ;
5.
Kebangsaan
:
Indonesia;
6.
Tempat tinggal
:
Kepuh Permai Jalan Merbabu Blok M-9,
Rt.007, Rw.009, Kelurahan Kepuh Kiriman,
Kecamatan Waru, Kabupaten Sidoarjo atau
domisili Jalan K

================================================================================
FILE: putusan_482_Pid_Sus_2025_PN_Sby.txt
================================================================================

--- TANGGAL PENGUCAPAN ---
anlah diputuskan dalam Rapat Permusyarawatan Majelis Hakim
Pengadilan Negeri Surabaya pada hari Kamis tanggal 10 April 2025 oleh Kami
MUHAMMAD
ZULQARNAIN,
SH.MH.
sebagai
Hakim
Ketua,
ERLY
SOELISTYARINI, SH.MHum. dan I MADE YULIADA, SH.MH., masing-masing
sebagai Hakim Anggota, putusan mana diucapkan pada hari Senin 05 Mei 2025
dalam sidang yang terbuka untuk umum, oleh Hakim Ketua tersebut dan
didampingi oleh Hakim-hakim Anggota dan dibantu oleh SUNARAH, SH.,
Panitera Pengganti pada Pengadilan Negeri Surabaya, dan dihadiri YUSTUS
ONE SIMUS PARLINDUNGAN, SH., Penuntut Umum pada Kejaksanaan Negeri
Tanjung Perak serta para terdakwa didampingi Para Penasehat Hukumnya.

     HAKIM-HAKIM ANGGOTA


   HAKIM KETUA

                   TTD.





 TTD.
ERLY SOELISTYARINI, SH., MHum.  MUHAMMAD ZULQARNAIN, SH., MH.


        TTD.
I MADE YULIADA, SH.,MH.

PANITERA PENGGANTI






      TTD.
SUNARAH, SH.
Disclaimer
Kepaniteraan Mahkamah Agung Republik Indonesia berus

--- IDENTITAS TERDAKWA ---
Jumlah label identitas: 0

## 17.12 Ekstraksi Nama Terdakwa, Jumlah Terdakwa, dan Tanggal Putusan

In [83]:
def ekstrak_nama_terdakwa(teks):

    # Ambil bagian awal dokumen sebelum Disclaimer
    bagian_awal = teks.split("Disclaimer")[0][:20000]

    # Cari pola Nama / Nama Lengkap
    pola = (
        r"(?im)^\s*(?:[IVX]+|\d+)?\s*[\.\)]?\s*"
        r"Nama(?:\s+Lengkap)?\s*:?\s*\n?\s*:?\s*"
        r"([^\n]+)"
    )

    hasil = re.findall(pola, bagian_awal)

    nama_terdakwa = []

    for nama in hasil:
        nama = re.sub(r"\s+", " ", nama).strip(" :;.-")

        if nama and nama not in nama_terdakwa:
            nama_terdakwa.append(nama)

    return nama_terdakwa


# Ekstraksi seluruh dokumen
for doc in documents:

    nama = ekstrak_nama_terdakwa(doc["isi_putusan"])

    print("\n", doc["nama_file"])
    print("Nama terdakwa:", nama)
    print("Jumlah terdakwa:", len(nama))

 putusan_1024_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Surya Aji Pratama Bin Darmawan', 'Satriyo Wahyuning Gusti als Tio Bin Eko Supriyadi']
Jumlah terdakwa: 2

 putusan_140_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Andika Fajar Yulisetiawan Bin Abdul Choir']
Jumlah terdakwa: 1

 putusan_1512_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['BAGUS']
Jumlah terdakwa: 1

 putusan_1880_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Ridwan Firmansyah Bin Rukman (Alm) Als']
Jumlah terdakwa: 1

 putusan_1982_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Eric Soesanto Prayitno Alias Eric Londo']
Jumlah terdakwa: 1

 putusan_2031_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Yan Haldiyansyah, SE Bin Budiono']
Jumlah terdakwa: 1

 putusan_2043_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['RAFI MAHARDIKA KURNIAWAN alias EPRET bin']
Jumlah terdakwa: 1

 putusan_2047_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Toni Wicaksono Bin Tri Tjahya Boedi Santoso']
Jumlah terdakwa: 1

 putusan_2166_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Hariyanto Als', 'Andi Susila Als']
Jumlah terdakwa: 2

 putusan_2189_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Muhamad Samsuri Bin Hatip (alm)', 'Dharma Tragahadi Sukma Cuk Sukmawan Bin Tjuk']
Jumlah terdakwa: 2

 putusan_2258_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Moch Sulam Bin Moch Zaini (alm)', 'Badrul Qomar Bin Umar']
Jumlah terdakwa: 2

 putusan_2260_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Moh. Arif Bin Moh. Slamed']
Jumlah terdakwa: 1

 putusan_2274_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Dewa Agira Panji Caroko Bin Dachlan Poernomo']
Jumlah terdakwa: 1

 putusan_2325_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Muhammad Choirul Hartono als Putra Bin']
Jumlah terdakwa: 1

 putusan_2359_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Sabdono Nurfiyanto Bin Alm.Bahrudin']
Jumlah terdakwa: 1

 putusan_2438_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['I.N. DWI ANTANA DUSAK Anak Dari NYOMAN', 'ERWIN DWI KURNIAWAN Bin. SAMSURI', 'AGUS WIBISONO Bin. DARMANTO']
Jumlah terdakwa: 3

 putusan_270_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Samsul Huda Bin Mudaim (alm)']
Jumlah terdakwa: 1

 putusan_1068_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['WIRANTO FAJAR WIBOWO BIN AGUNG BUDI', 'ADI WAHONO ALIAS OTONG BIN SUKAMTO']
Jumlah terdakwa: 2

 putusan_1276_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['GALU RINEKSO']
Jumlah terdakwa: 1

 putusan_1629_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['YAYAN MARDIANTO anak dari TOTOK SUWITO']
Jumlah terdakwa: 1

 putusan_1741_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['Budi Darmawan Bin Sudarmaji (alm)']
Jumlah terdakwa: 1

 putusan_1751_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['Toliful Ilmi Bin Doholil']
Jumlah terdakwa: 1

 putusan_1846_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['AMIRUL HAMZAH Bin MALIK']
Jumlah terdakwa: 1

 putusan_1901_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['Masduqi Zakaria Bin Alimun (Alm)']
Jumlah terdakwa: 1

 putusan_1904_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['MIFTAHUL ROHMAN bin KOSIM']
Jumlah terdakwa: 1

 putusan_1968_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['Supriono Bin Sukamdi']
Jumlah terdakwa: 1

 putusan_2010_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['MUHAMMAD YASIN Bin SAMSUDIN (Alm)']
Jumlah terdakwa: 1

 putusan_2017_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['Moch Zainul Imam Bin Anwar']
Jumlah terdakwa: 1

 putusan_2050_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['Amin Fauzi Primap Bin Sabirin']
Jumlah terdakwa: 1

 putusan_2054_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['Yoyok Sulistiyo Bin']
Jumlah terdakwa: 1

 putusan_2071_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['PRAYOGO BAYU PAMUNGKAS Bin']
Jumlah terdakwa: 1

 putusan_2127_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['Indra Iswanto Bin Slamet']
Jumlah terdakwa: 1

 putusan_2302_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['ACH. KARAFI PRATAMA Bin MAT JUHA']
Jumlah terdakwa: 1

 putusan_2454_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['SOEDJIANTO ALIAS ATAK BIN TOHIR (alm)']
Jumlah terdakwa: 1

 putusan_891_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['Ahmad Dani Bin (Alm) Mujasit', 'Lucky Wahyu Sanjaya Bin Jaharudin']
Jumlah terdakwa: 2

 putusan_898_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['Risqi Nur Junianto Bin Ambrin']
Jumlah terdakwa: 1

 putusan_1668_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['FERNANDA BAGUS SASONGKO BIN JARNO']
Jumlah terdakwa: 1

 putusan_1773_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['Yogas Ardinata Melarahmanda bin Supardi']
Jumlah terdakwa: 1

 putusan_1789_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['DESY RACHMA PUJI ASTUTI BINTI BAMBANG']
Jumlah terdakwa: 1

 putusan_1852_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['Henry Anak Dari Heni Darmanto']
Jumlah terdakwa: 1

 putusan_1880_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['CHAIRUL ANDRIANTO bin MOH SAPRANI', 'MOCH. RIZKY FAUZI bin SOEYANTO']
Jumlah terdakwa: 2

 putusan_1895_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['LUKMAN Bin MURSIDI', 'OKKY HERMANTO Bin MATALI']
Jumlah terdakwa: 2

 putusan_1930_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['NUR ISKANDARSAH', 'ERWIN HERAWAN']
Jumlah terdakwa: 2

 putusan_1949_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['FERLINDA SELVYA PUTRI NYUGIANTO Als']
Jumlah terdakwa: 1

 putusan_1965_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['Arga Surya Bimantara Bin Sartono']
Jumlah terdakwa: 1

 putusan_2101_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['Yudharta Sapta Prasetya bin Harry Koesnandar']
Jumlah terdakwa: 1

 putusan_2109_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['Syaiful Romli Bin Mat Hafi']
Jumlah terdakwa: 1

 putusan_222_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['MOCH ROCHMAN bin MOCH YUNUS']
Jumlah terdakwa: 1

 putusan_482_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['AISAH alias ICHA Binti JAMIL ROBI', 'ANANG SUROTO Als EGOR Bin SUGITO', 'MOCH. TOYYEP Bin MAT NASIR']
Jumlah terdakwa: 3

 putusan_579_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['Tempat Lahir']
Jumlah terdakwa: 1

## 17.13 — Identifikasi Nama Terdakwa yang Perlu Diperiksa

In [84]:
dokumen_perlu_perbaikan = [
    "putusan_1512_Pid_Sus_2023_PN_Sby.txt",
    "putusan_1880_Pid_Sus_2023_PN_Sby.txt",
    "putusan_2043_Pid_Sus_2023_PN_Sby.txt",
    "putusan_2166_Pid_Sus_2023_PN_Sby.txt",
    "putusan_2325_Pid_Sus_2023_PN_Sby.txt",
    "putusan_2054_Pid_Sus_2024_PN_Sby.txt",
    "putusan_2071_Pid_Sus_2024_PN_Sby.txt",
    "putusan_1949_Pid_Sus_2025_PN_Sby.txt",
    "putusan_579_Pid_Sus_2025_PN_Sby.txt"
]

for doc in documents:
    if doc["nama_file"] in dokumen_perlu_perbaikan:
        print("\n" + "=" * 70)
        print(doc["nama_file"])

        teks = doc["isi_putusan"]
        hasil = re.search(
            r"Nama(?:\s+Lengkap)?",
            teks[:20000],
            re.IGNORECASE
        )

        if hasil:
            awal = max(0, hasil.start() - 300)
            akhir = min(len(teks), hasil.start() + 1000)
            print(teks[awal:akhir])

======================================================================
putusan_1512_Pid_Sus_2023_PN_Sby.txt
Pid.Sus/2023/PN Sby

P U T U S A N
Nomor 1512/Pid.Sus/2023/PN Sby

DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan acara
pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai berikut
dalam perkara Terdakwa :
1. Nama lengkap
: BAGUS
IRYANTO
als
BAGUS
Bin
WIDYAN
MULYADI;
2. Tempat lahir
: Gresik;
3. Umur/Tanggal lahir
: 40 Tahun / 17 April 1983;
4. Jenis kelamin
: Laki-laki;
5. Kebangsaan
: Indonesia;
6. Tempat tinggal
: Tenggulunan Jaya RT. 014 RW. 005 Ds. Tenggulunan
Kec. Candi Kab. Sidoarjo dan/atau Jl. Indrapura Jaya
203 RT. 003 RW. 010 Kel. Perak Timur Kec. Pabean
Cantikan Kota Surabaya;
7. Agama
: Islam;
8. Pekerjaan
: Karyawan Swasta;
Terdakwa ditahan dalam Rumah Tahanan Kelas I Surabaya oleh :
1.
Penyidik sejak tanggal 09 Mei 2023 sampai dengan tanggal 28 Mei 2023;
2.
Penyidik Perpanjangan Oleh Penuntut Umum sejak tanggal 29 Mei 2023
sampai dengan tanggal 07 Juli 2023;
3.
Penuntut Umum sejak tanggal 04 Juli 2023 sampai dengan tanggal 23 Juli
2023;
4.
Hakim Pengadilan Negeri sejak tanggal 17 Juli 2023 sampai dengan tanggal 15
Agustus 2023;
5.
Hakim Pengadilan Negeri Perpanjangan Oleh Ketua Pengadilan Negeri sejak
t

======================================================================
putusan_1880_Pid_Sus_2023_PN_Sby.txt
onesia
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 1880/Pid.Sus/2023/PN Sby
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Terdakwa:
Nama lengkap
:
Ridwan Firmansyah Bin Rukman (Alm) Als
Revan;
Tempat lahir
:
Jakarta;
Umur/tanggal lahir
:
35 Tahun / 02 Maret 1988;
Jenis Kelamin
:
Laki-laki;
Kebangsaan
:
Indonesia;
Tempat tinggal
:
Jln. KS. Tubun 3 No. 32 RT. 008 RW. 007
Kelurahan Slipi Kecamatan Palmerah Kota
Jakarta Barat;
Agama
:
Islam;
Pekerjaan
:
Karyawan Swasta;
Terdakwa ditahan dalam perkara lain;
Terdakwa
 mengahadap dipersidangan dengan didamping Penasehat
hukumnya: Rindra Mutfianto, S.H., Ronni Bahmari, S.H., & Endang Suprawati,
S.H., M.H., Para Advokad dan Paralegal dari “Lembaga Bantuan Hukum Jaka
Samudra Indonesia” beralamat di Perumahan Golden East North Boulevard
Blok A No.36, Desa/Kel. Dahanrejo, Kec. Kebomas, Kab. Gresik, ditunjuk
berdasarkan penetapan Majelis Hakim Nomor 1880/Pid.Sus/2023/PN Sby.,
tertanggal 10 Oktober 2023, terlampir dalam berkas perkara;
Pengadilan Negeri tersebut;
Setelah membaca:
-
Penetapan
 Ketua Pengadilan Negeri
 Sur

======================================================================
putusan_2043_Pid_Sus_2023_PN_Sby.txt
ia
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 2043/Pid.Sus/2023/PN Sby
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan acara
pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai berikut
dalam perkara Terdakwa :
1. Nama lengkap
: RAFI MAHARDIKA KURNIAWAN alias EPRET bin
FREDDY
2. Tempat lahir
: Surabaya
3. Umur/Tanggal lahir : 26 Tahun/12 Mei 1997
4. Jenis kelamin
: Laki-laki
5. Kebangsaan
: Indonesia
6. Tempat tinggal
: Genting Gg VI No. 10 Kel. Genting Kec. Asemrowo
Surabaya.
7. Agama
: Islam
8. Pekerjaan
: Karyawan swasta
Terdakwa Rafi Mahardika Kurniawan alias Epret bin Freddy ditahan dalam
tahanan rutan masing-masing oleh:
1.
Penyidik sejak tanggal 29 Juli 2023 sampai dengan tanggal 17 Agustus 2023;
2.
Penyidik Perpanjangan Oleh Penuntut Umum sejak tanggal 18 Agustus 2023
sampai dengan tanggal 26 September 2023;
3.
Penuntut Umum sejak tanggal 20 September 2023 sampai dengan tanggal
9 Oktober 2023;
4.
Hakim Pengadilan Negeri sejak tanggal 25 September 2023 sampai dengan
tanggal 24 Oktober 2023;
5.
Hakim Pengadilan Negeri Perpanjangan Oleh Ketua Pengadilan Negeri sejak
tanggal 25 Oktober 2023 sampai dengan tanggal 23 Desember 2023;
Terdakwa didampingi oleh Penasihat Hukum Drs. Vict

======================================================================
putusan_2166_Pid_Sus_2023_PN_Sby.txt
sia
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 2166/Pid.Sus/2023/PN Sby
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Terdakwa:
I.
Nama lengkap
:
Hariyanto Als.
Mbah Di Bin Bari;
Tempat lahir
:
Surabaya;
Umur/tanggal lahirq:
47 tahun / 08 Januari 1977;
Jenis Kelamin
:
Laki-laki;
Kebangsaan
:
Indonesia;
Tempat tinggal
:
Jl. Sidoyoso Kali Utara No.93 RT.14 RW.07 kel.
Simokerto Kec. Simokerto kota Surabaya atau di Jl.
Sidoyoso Kali Wetan kel. Simokerto Kec. Simokerto
kota Surabaya (Kost);
Agama
:
Islam;
Pekerjaan
:
Swasta;
II.
Nama lengkap
:
Andi Susila Als.
Andik Bin Sumadi (Alm);
Tempat lahir
:
Surabaya;
Umur/tanggal lahir  :
42 tahun / 04 Juni 1981;
Jenis Kelamin
:
Laki-laki;
Kebangsaan
:
Indonesia;
Tempat tinggal
:
Jl. Sidoyoso Jaya Gang Buntu No.14 RT.06 RW. 012
kel. Simokerto Kec. Simokerto kota Surabaya atau di
Jl. Sidoyoso Kali Wetan kel. Simokerto Kec.
Simokerto kota Surabaya (Kost);
Agama
:
Islam;
Pekerjaan
:
Swasta;
Terdakwa  I. Hariyanto Als. Mbah Di Bin Bari ditangkap oleh Penyidik
berdasarkan



======================================================================
putusan_2325_Pid_Sus_2023_PN_Sby.txt
a
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 2325/Pid.Sus/2023/PN Sby
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Terdakwa :
1.
Nama lengkap
:
Muhammad Choirul Hartono als Putra Bin
Hartono
2.
Tempat lahir
:
Malang
3.
Umur/Tanggal lahir :
24/15 Februari 1999
4.
Jenis kelamin
:
Laki-laki
5.
Kebangsaan
:
 Indonesia
6.
Tempat tinggal
:
Jatiguwi RT 003 RW 001 Ds. Jatiguwi Kec.
Sumberpucung Kab. Malang (sesuai KTP NIK
3507121502990002) dan bertempat tinggal di
Jl. Lemah Duwur, Sitirejo, Kec. Wagir Kab.
Malang
7.
Agama
:
Islam
8.
Pekerjaan
:
Karyawan swasta
Terdakwa Muhammad Choirul Hartono als Putra Bin Hartono ditahan dalam
tahanan rutan oleh:
1.
Penyidik sejak tanggal 1 September 2023 sampai dengan tanggal 20
September 2023
2.
Penyidik Perpanjangan Oleh Penuntut Umum sejak tanggal 21 September
2023 sampai dengan tanggal 30 Oktober 2023;
3.
Penuntut Umum sejak tanggal 30 Oktober 2023 sampai dengan tanggal
18 November 2023;
4.
Hakim Pengadilan Negeri sejak tanggal 6 November 2023 sampai dengan
tanggal 5 Desember 2023;
5.
Hakim Pengadilan Negeri Perpanjangan Oleh Ketua Pengadilan Negeri
sejak t

======================================================================
putusan_2054_Pid_Sus_2024_PN_Sby.txt
ia
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 2054/Pid.Sus/2024/PN Sby
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Terdakwa :
1.
Nama lengkap
:
Yoyok Sulistiyo Bin
Muchamad;
2.
Tempat lahir
:
Surabaya;
3.
Umur/tanggal lahir  :
47 Tahun / 14
Maret 1977;
4.
Jenis Kelamin
:
Laki-laki;
5.
Kebangsaan
:
Indonesia;
6.
Tempat tinggal
:
Sesuai KTP Jl.
Jenggolo III/70 Rt. 012 Rw. 003 Kel. Pucang Kec.
Sidoarjo Kab. Sidoarjo;
7.
Agama         :
Islam;
8.
Pekerjaan
:
Belum/tidak
Bekerja;
Terdakwa ditangkap sejak tanggal 26 Agustus 2024 sampai dengan tanggal 29
Agustus 2024 berdasarkan surat perintah penangkapan Nomor SPRIN-
KAP/251/VIII/RES.4.2/2024/SATRESNARKOBA tertanggal 26 Agustus 2024;
Terdakwa Yoyok Sulistiyo Bin Muchamad ditahan dalam Rumah Tahanan
Negara oleh:
1. Penyidik sejak tanggal 29 Agustus 2024 sampai dengan tanggal 17
September 2024;
2. Penyidik Perpanjangan Oleh Penuntut Umum sejak tanggal 18 September
2024 sampai dengan tanggal 27 Oktober 2024;
3. Penuntut Umum sejak tanggal 15 Oktober 2024 sampai dengan tanggal 03
November 2024;
4. Hakim Pengadilan Neger

======================================================================
putusan_2071_Pid_Sus_2024_PN_Sby.txt
       P U T U S A N
                        Nomor 2071/Pid.Sus/2024/PN Sby.
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara terdakwa:
1.
Nama                            :
PRAYOGO BAYU PAMUNGKAS Bin
BAMBANG PRAPTO SUSILO ;
2.
Tempat Lahir
:
Mojokerto ;
3.
Umur/Tanggal Lahir
:
25 tahun / 7 Desember 1998 ;
4.
Jenis Kelamin
:
Laki - laki ;
5.
Kebangsaan
:
Indonesia;
6.
Tempat tinggal
:
Kepuh Permai Jalan Merbabu Blok M-9,
Rt.007, Rw.009, Kelurahan Kepuh Kiriman,
Kecamatan Waru, Kabupaten Sidoarjo atau
domisili Jalan Kendangsari Gg. 12 Nomor 1 A,
Kecamatan Tenggilis Mejoyo,Kota Surabaya;
7.
Agama
:
Islam ;
8.
Pekerjaan
:
Karyawan Swasta ;
Terdakwa ditahan berdasarkan Surat Perintah oleh :
1. Penyidik, sejak tanggal 13 Agustus 2024 sampai 1 September 2024;
2. Perpanjangan Penuntut Umum,  sejak tanggal 2 September 2024 sampai
tanggal 11 Oktober  2024 ;
3. Penuntut Umum, sejak tanggal 9 Oktober 2024 sampai tanggal 28 Oktober
2024 ;
4. Penahanan Hakim, sejak tanggal 23 Oktober 2024 sampai dengan tanggal
21 Nopember 2024 ;
5. Perpanjangan Ketua Pengadilan Negeri, sejak tanggal 22 Nopember 2024
sampai dengan tanggal 20 Januari 2

======================================================================
putusan_1949_Pid_Sus_2025_PN_Sby.txt
san.mahkamahagung.go.id
P U T U S A N
Nomor 1949/Pid.Sus/2025/PN.Sby.
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama telah menjatuhkan putusan
sebagai berikut dalam perkara Terdakwa :
1. Nama lengkap
: FERLINDA SELVYA PUTRI NYUGIANTO Als.
LINDA Binti NYUGIANTO;
2. Tempat lahir
: Sidoarjo;
3. Umur/Tanggal lahir
: 22 Th./5 Januari 2003;
4. Jenis kelamin
: Perempuan;
5. Kebangsaan
: Indonesia;
6. Tempat tinggal
: Dsn. Kedungrejo, Ds. Wedoroklurak No.18 RT/RW
001/001, Kec. Candi Kab.Sidoarjo;
7. Agama
: Islam;
8. Pekerjaan
: Ibu Rumah Tangga;
9.Pendididkan
: SMA (tamat);
Terdakwa   ditahan dalam Rumah Tahanan Negara, oleh:
1. Penyidik, sejak tanggal 13 Juni 2025 sampai dengan tanggal 2 Juli 2025;
2. Penyidik, Perpanjangan Oleh Penuntut Umum sejak tanggal 3 Juli 2025
sampai dengan tanggal 11 Agustus 2025;
3. Penuntut Umum, sejak tanggal 11 Agustus 2025 sampai dengan tanggal 30
Agustus 2025;
4. Hakim Pengadilan Negeri, sejak tanggal 22 Agustus 2025 sampai dengan
tanggal 20 September 2025;
6. Hakim Pengadilan Negeri Perpanjangan Pertama Oleh Ketua Pengadilan
Negeri sejak tanggal 21 September 2025 sampai dengan tanggal 19
November 2025;

Didepan sidang Terdakwa d

======================================================================
putusan_579_Pid_Sus_2025_PN_Sby.txt
onesia
putusan.mahkamahagung.go.id
P U T U S A N
Nomor 579/Pid.Sus/2025/PN Sby
DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA
Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Terdakwa :
Nama  Lengkap
Tempat Lahir
Umur/tanggal
lahir
Jenis kelamin
Kebangsaan
Tempat tinggal
Agama
Pekerjaan
:
ACHMAD NGGOPUR Bin SUIPUK KUSWANTO;
Surabaya;
36 tahun / 27 September 1988;
Laki-laki;
Indonesia;
Jl. Kedung Baruk Kec. Rungkut Surabaya atau kost di Jl.
Kedung Asem No.35 Kel. Kedung baruk Kec. Rungkut
Surabaya;
Islam;
Serabutan;
Terdakwa Achmad Nggopur Bin Suipuk Kuswanto ditahan dalam tahanan rutan
oleh:
1. Penyidik sejak tanggal 23 November 2024 sampai dengan tanggal 12
Desember 2024;
2. Penyidik Perpanjangan Oleh Penuntut Umum sejak tanggal 13
Desember 2024 sampai dengan tanggal 21 Januari 2025;
3. Penuntut Umum sejak tanggal 20 Januari 2025 sampai dengan tanggal 8
Februari 2025;
4. Penuntut Umum Perpanjangan Oleh Ketua Pengadilan Negeri sejak
tanggal 9 Februari 2025 sampai dengan tanggal 10 Maret 2025;
5. Hakim Pengadilan Negeri sejak tanggal 10 Maret 2025 sampai dengan
tanggal 8 April 2025;
6. Hakim Pengadilan Negeri Perpanjangan Oleh Ketua Pengadilan Negeri
sejak tangga

## 17.14 — Koreksi Nama Terdakwa

In [85]:
# Koreksi nama terdakwa berdasarkan pemeriksaan teks asli
koreksi_nama = {
    "putusan_1512_Pid_Sus_2023_PN_Sby.txt": [
        "BAGUS IRYANTO als BAGUS Bin WIDYAN MULYADI"
    ],

    "putusan_1880_Pid_Sus_2023_PN_Sby.txt": [
        "Ridwan Firmansyah Bin Rukman (Alm) Als Revan"
    ],

    "putusan_2043_Pid_Sus_2023_PN_Sby.txt": [
        "RAFI MAHARDIKA KURNIAWAN alias EPRET bin FREDDY"
    ],

    "putusan_2166_Pid_Sus_2023_PN_Sby.txt": [
        "Hariyanto Als. Mbah Di Bin Bari",
        "Andi Susila Als. Andik Bin Sumadi (Alm)"
    ],

    "putusan_2325_Pid_Sus_2023_PN_Sby.txt": [
        "Muhammad Choirul Hartono als Putra Bin Hartono"
    ],

    "putusan_2054_Pid_Sus_2024_PN_Sby.txt": [
        "Yoyok Sulistiyo Bin Muchamad"
    ],

    "putusan_2071_Pid_Sus_2024_PN_Sby.txt": [
        "PRAYOGO BAYU PAMUNGKAS Bin BAMBANG PRAPTO SUSILO"
    ],

    "putusan_1949_Pid_Sus_2025_PN_Sby.txt": [
        "FERLINDA SELVYA PUTRI NYUGIANTO Als. LINDA Binti NYUGIANTO"
    ],

    "putusan_579_Pid_Sus_2025_PN_Sby.txt": [
        "ACHMAD NGGOPUR Bin SUIPUK KUSWANTO"
    ]
}


# Terapkan hasil ekstraksi awal dan koreksi
for doc in documents:

    nama = ekstrak_nama_terdakwa(doc["isi_putusan"])

    if doc["nama_file"] in koreksi_nama:
        nama = koreksi_nama[doc["nama_file"]]

    doc["nama_terdakwa"] = nama
    doc["jumlah_terdakwa"] = len(nama)


# Tampilkan hasil koreksi
for doc in documents:

    if doc["nama_file"] in koreksi_nama:
        print("\n", doc["nama_file"])
        print("Nama terdakwa:", doc["nama_terdakwa"])
        print("Jumlah terdakwa:", doc["jumlah_terdakwa"])
        print("Status: Dikoreksi berdasarkan teks asli")

 putusan_1512_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['BAGUS IRYANTO als BAGUS Bin WIDYAN MULYADI']
Jumlah terdakwa: 1
Status: Dikoreksi berdasarkan teks asli

 putusan_1880_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Ridwan Firmansyah Bin Rukman (Alm) Als Revan']
Jumlah terdakwa: 1
Status: Dikoreksi berdasarkan teks asli

 putusan_2043_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['RAFI MAHARDIKA KURNIAWAN alias EPRET bin FREDDY']
Jumlah terdakwa: 1
Status: Dikoreksi berdasarkan teks asli

 putusan_2166_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Hariyanto Als. Mbah Di Bin Bari', 'Andi Susila Als. Andik Bin Sumadi (Alm)']
Jumlah terdakwa: 2
Status: Dikoreksi berdasarkan teks asli

 putusan_2325_Pid_Sus_2023_PN_Sby.txt
Nama terdakwa: ['Muhammad Choirul Hartono als Putra Bin Hartono']
Jumlah terdakwa: 1
Status: Dikoreksi berdasarkan teks asli

 putusan_2054_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['Yoyok Sulistiyo Bin Muchamad']
Jumlah terdakwa: 1
Status: Dikoreksi berdasarkan teks asli

 putusan_2071_Pid_Sus_2024_PN_Sby.txt
Nama terdakwa: ['PRAYOGO BAYU PAMUNGKAS Bin BAMBANG PRAPTO SUSILO']
Jumlah terdakwa: 1
Status: Dikoreksi berdasarkan teks asli

 putusan_1949_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['FERLINDA SELVYA PUTRI NYUGIANTO Als. LINDA Binti NYUGIANTO']
Jumlah terdakwa: 1
Status: Dikoreksi berdasarkan teks asli

 putusan_579_Pid_Sus_2025_PN_Sby.txt
Nama terdakwa: ['ACHMAD NGGOPUR Bin SUIPUK KUSWANTO']
Jumlah terdakwa: 1
Status: Dikoreksi berdasarkan teks asli

## 17.15 — Validasi Hasil Ekstraksi Nama Terdakwa

In [86]:
# Validasi hasil ekstraksi nama terdakwa
data_nama = []

for doc in documents:
    nama = doc.get("nama_terdakwa", ekstrak_nama_terdakwa(doc["isi_putusan"]))

    data_nama.append({
        "nama_file": doc["nama_file"],
        "nama_terdakwa": "; ".join(nama),
        "jumlah_terdakwa": len(nama),
        "status": "Perlu diperiksa" if len(nama) == 0 else "Terdeteksi"
    })

df_nama = pd.DataFrame(data_nama)

print("Total dokumen:", len(df_nama))
print("Dokumen terdeteksi:", (df_nama["jumlah_terdakwa"] > 0).sum())
print("Dokumen belum terdeteksi:", (df_nama["jumlah_terdakwa"] == 0).sum())

display(df_nama)

Total dokumen: 50
Dokumen terdeteksi: 50
Dokumen belum terdeteksi: 0

,nama_file,nama_terdakwa,jumlah_terdakwa,status
0,putusan_1024_Pid_Sus_2023_PN_Sby.txt,Surya Aji Pratama Bin Darmawan; Satriyo Wahyun...,2,Terdeteksi
1,putusan_140_Pid_Sus_2023_PN_Sby.txt,Andika Fajar Yulisetiawan Bin Abdul Choir,1,Terdeteksi
2,putusan_1512_Pid_Sus_2023_PN_Sby.txt,BAGUS IRYANTO als BAGUS Bin WIDYAN MULYADI,1,Terdeteksi
3,putusan_1880_Pid_Sus_2023_PN_Sby.txt,Ridwan Firmansyah Bin Rukman (Alm) Als Revan,1,Terdeteksi
4,putusan_1982_Pid_Sus_2023_PN_Sby.txt,Eric Soesanto Prayitno Alias Eric Londo,1,Terdeteksi
5,putusan_2031_Pid_Sus_2023_PN_Sby.txt,"Yan Haldiyansyah, SE Bin Budiono",1,Terdeteksi
6,putusan_2043_Pid_Sus_2023_PN_Sby.txt,RAFI MAHARDIKA KURNIAWAN alias EPRET bin FREDDY,1,Terdeteksi
7,putusan_2047_Pid_Sus_2023_PN_Sby.txt,Toni Wicaksono Bin Tri Tjahya Boedi Santoso,1,Terdeteksi
8,putusan_2166_Pid_Sus_2023_PN_Sby.txt,Hariyanto Als. Mbah Di Bin Bari; Andi Susila A...,2,Terdeteksi
9,putusan_2189_Pid_Sus_2023_PN_Sby.txt,Muhamad Samsuri Bin Hatip (alm); Dharma Tragah...,2,Terdeteksi
10,putusan_2258_Pid_Sus_2023_PN_Sby.txt,Moch Sulam Bin Moch Zaini (alm); Badrul Qomar ...,2,Terdeteksi
11,putusan_2260_Pid_Sus_2023_PN_Sby.txt,Moh. Arif Bin Moh. Slamed,1,Terdeteksi
12,putusan_2274_Pid_Sus_2023_PN_Sby.txt,Dewa Agira Panji Caroko Bin Dachlan Poernomo,1,Terdeteksi
13,putusan_2325_Pid_Sus_2023_PN_Sby.txt,Muhammad Choirul Hartono als Putra Bin Hartono,1,Terdeteksi
14,putusan_2359_Pid_Sus_2023_PN_Sby.txt,Sabdono Nurfiyanto Bin Alm.Bahrudin,1,Terdeteksi
15,putusan_2438_Pid_Sus_2023_PN_Sby.txt,I.N. DWI ANTANA DUSAK Anak Dari NYOMAN; ERWIN ...,3,Terdeteksi
16,putusan_270_Pid_Sus_2023_PN_Sby.txt,Samsul Huda Bin Mudaim (alm),1,Terdeteksi
17,putusan_1068_Pid_Sus_2024_PN_Sby.txt,WIRANTO FAJAR WIBOWO BIN AGUNG BUDI; ADI WAHON...,2,Terdeteksi
18,putusan_1276_Pid_Sus_2024_PN_Sby.txt,GALU RINEKSO,1,Terdeteksi
19,putusan_1629_Pid_Sus_2024_PN_Sby.txt,YAYAN MARDIANTO anak dari TOTOK SUWITO,1,Terdeteksi
20,putusan_1741_Pid_Sus_2024_PN_Sby.txt,Budi Darmawan Bin Sudarmaji (alm),1,Terdeteksi
21,putusan_1751_Pid_Sus_2024_PN_Sby.txt,Toliful Ilmi Bin Doholil,1,Terdeteksi
22,putusan_1846_Pid_Sus_2024_PN_Sby.txt,AMIRUL HAMZAH Bin MALIK,1,Terdeteksi
23,putusan_1901_Pid_Sus_2024_PN_Sby.txt,Masduqi Zakaria Bin Alimun (Alm),1,Terdeteksi
24,putusan_1904_Pid_Sus_2024_PN_Sby.txt,MIFTAHUL ROHMAN bin KOSIM,1,Terdeteksi
25,putusan_1968_Pid_Sus_2024_PN_Sby.txt,Supriono Bin Sukamdi,1,Terdeteksi
26,putusan_2010_Pid_Sus_2024_PN_Sby.txt,MUHAMMAD YASIN Bin SAMSUDIN (Alm),1,Terdeteksi
27,putusan_2017_Pid_Sus_2024_PN_Sby.txt,Moch Zainul Imam Bin Anwar,1,Terdeteksi
28,putusan_2050_Pid_Sus_2024_PN_Sby.txt,Amin Fauzi Primap Bin Sabirin,1,Terdeteksi
29,putusan_2054_Pid_Sus_2024_PN_Sby.txt,Yoyok Sulistiyo Bin Muchamad,1,Terdeteksi
30,putusan_2071_Pid_Sus_2024_PN_Sby.txt,PRAYOGO BAYU PAMUNGKAS Bin BAMBANG PRAPTO SUSILO,1,Terdeteksi
31,putusan_2127_Pid_Sus_2024_PN_Sby.txt,Indra Iswanto Bin Slamet,1,Terdeteksi
32,putusan_2302_Pid_Sus_2024_PN_Sby.txt,ACH. KARAFI PRATAMA Bin MAT JUHA,1,Terdeteksi
33,putusan_2454_Pid_Sus_2024_PN_Sby.txt,SOEDJIANTO ALIAS ATAK BIN TOHIR (alm),1,Terdeteksi
34,putusan_891_Pid_Sus_2024_PN_Sby.txt,Ahmad Dani Bin (Alm) Mujasit; Lucky Wahyu Sanj...,2,Terdeteksi
35,putusan_898_Pid_Sus_2024_PN_Sby.txt,Risqi Nur Junianto Bin Ambrin,1,Terdeteksi
36,putusan_1668_Pid_Sus_2025_PN_Sby.txt,FERNANDA BAGUS SASONGKO BIN JARNO,1,Terdeteksi
37,putusan_1773_Pid_Sus_2025_PN_Sby.txt,Yogas Ardinata Melarahmanda bin Supardi,1,Terdeteksi
38,putusan_1789_Pid_Sus_2025_PN_Sby.txt,DESY RACHMA PUJI ASTUTI BINTI BAMBANG,1,Terdeteksi
39,putusan_1852_Pid_Sus_2025_PN_Sby.txt,Henry Anak Dari Heni Darmanto,1,Terdeteksi
40,putusan_1880_Pid_Sus_2025_PN_Sby.txt,CHAIRUL ANDRIANTO bin MOH SAPRANI; MOCH. RIZKY...,2,Terdeteksi
41,putusan_1895_Pid_Sus_2025_PN_Sby.txt,LUKMAN Bin MURSIDI; OKKY HERMANTO Bin MATALI,2,Terdeteksi
42,putusan_1930_Pid_Sus_2025_PN_Sby.txt,NUR ISKANDARSAH; ERWIN HERAWAN,2,Terdeteksi
43,putusan_1949_Pid_Sus_2025_PN_Sby.txt,FERLINDA SELVYA PUTRI NYUGIANTO Als. LINDA Bin...,1,Terdeteksi
44,putusan_1965_Pid_Sus_2025_PN_Sby.txt,Arga Surya Bimantara Bin Sartono,1,Terdeteksi
45,putusan_2101_Pid_Sus_2025_PN_Sby.txt,Yudharta Sapta Prasetya bin Harry Koesnandar,1,Terdeteksi
46,putusan_2109_Pid_Sus_2025_PN_Sby.txt,Syaiful Romli Bin Mat Hafi,1,Terdeteksi
47,putusan_222_Pid_Sus_2025_PN_Sby.txt,MOCH ROCHMAN bin MOCH YUNUS,1,Terdeteksi
48,putusan_482_Pid_Sus_2025_PN_Sby.txt,AISAH alias ICHA Binti JAMIL ROBI; ANANG SUROT...,3,Terdeteksi
49,putusan_579_Pid_Sus_2025_PN_Sby.txt,ACHMAD NGGOPUR Bin SUIPUK KUSWANTO,1,Terdeteksi

## 17.16: Simpan hasil ekstraksi nama

In [39]:
# Simpan hasil ekstraksi nama terdakwa
output_nama = os.path.join(DATA_DIR, "hasil_ekstraksi_nama_terdakwa.csv")

df_nama.to_csv(output_nama, index=False, encoding="utf-8-sig")

print("File berhasil disimpan:", output_nama)

File berhasil disimpan: /content/Dataset-Narkotika_027_199/data/hasil_ekstraksi_nama_terdakwa.csv

## 17.17 — Ekstraksi metadata terintegrasi

In [87]:
# ==========================================
# 17.17 EKSTRAKSI METADATA TERINTEGRASI
# ==========================================

import os
import re
import pandas as pd

# Daftar bulan untuk ekstraksi tanggal
bulan = (
    r"Januari|Februari|Maret|April|Mei|Juni|"
    r"Juli|Agustus|September|Oktober|November|Desember"
)


# 1. Ekstraksi nomor perkara
def ekstrak_nomor_putusan(teks):

    bagian_awal = teks[:10000]

    pola = (
        r"Nomor\s*:?\s*"
        r"(\d+\s*/\s*Pid\.?\s*Sus\s*/\s*\d{4}\s*/\s*PN\.?\s*Sby\.?)"
    )

    hasil = re.search(pola, bagian_awal, re.IGNORECASE)

    if hasil:
        return re.sub(r"\s+", "", hasil.group(1))

    return None


# 2. Ekstraksi tanggal pengucapan putusan
def ekstrak_tanggal_putusan(teks):

    pola_pengucapan = (
        r"(?:diucapkan|diucapkanlah|diucapkan dalam)"
        r".{0,500}?"
        r"(\d{1,2}\s+(?:" + bulan + r")\s+\d{4})"
    )

    hasil = list(
        re.finditer(
            pola_pengucapan,
            teks,
            re.IGNORECASE | re.DOTALL
        )
    )

    if hasil:
        return hasil[-1].group(1)

    return None


# 3. Ekstraksi pasal
def ekstrak_pasal(teks):

    pola = r"Pasal\s+\d+[A-Za-z]?(?:\s+ayat\s*\(\d+\))?"

    hasil = re.findall(pola, teks, re.IGNORECASE)

    pasal_unik = []
    for item in hasil:
        item = re.sub(r"\s+", " ", item).strip()

        if item.lower() not in [p.lower() for p in pasal_unik]:
            pasal_unik.append(item)

    return pasal_unik


# 4. Ekstraksi seluruh metadata
hasil_final = []

for doc in documents:

    teks = doc["isi_putusan"]
    nama_file = doc["nama_file"]

    # Nomor perkara
    nomor = ekstrak_nomor_putusan(teks)

    # Tanggal pengucapan
    tanggal = ekstrak_tanggal_putusan(teks)

    # Nama terdakwa yang sudah dikoreksi
    nama = doc.get("nama_terdakwa", [])

    # Pasal
    pasal = ekstrak_pasal(teks)

    # Amar dan barang bukti
    hasil_amar = ekstrak_amar_dan_barang_bukti(teks)

    amar = hasil_amar["amar_putusan"]
    barang_bukti = hasil_amar["barang_bukti"]

    # Simpan hasil
    hasil_final.append({

        "case_id": os.path.splitext(nama_file)[0],

        "no_perkara": nomor,

        "tanggal": tanggal,

        "pasal": "; ".join(pasal) if pasal else None,

        "pihak": "; ".join(nama) if nama else None,

        "jumlah_terdakwa": len(nama),

        "ringkasan_fakta": None,

        "argumen_hukum": None,

        "text_full": teks,

        "solusi_text": amar,

        "barang_bukti": barang_bukti,

        "status_nomor": "Terdeteksi" if nomor else "Perlu diperiksa",

        "status_tanggal": "Terdeteksi" if tanggal else "Perlu diperiksa",

        "status_amar": "Terdeteksi" if amar else "Perlu diperiksa",

        "status_barang_bukti": (
            "Terdeteksi" if barang_bukti else "Perlu diperiksa"
        )
    })


# 5. Membuat DataFrame final
df_final = pd.DataFrame(hasil_final)

print("TOTAL DOKUMEN:", len(df_final))

print("\nHASIL DETEKSI METADATA")
for kolom in [
    "status_nomor",
    "status_tanggal",
    "status_amar",
    "status_barang_bukti"
]:
    print(
        kolom, ":",
        (df_final[kolom] == "Terdeteksi").sum(),
        "/", len(df_final)
    )

display(
    df_final[
        [
            "case_id",
            "no_perkara",
            "tanggal",
            "pasal",
            "pihak",
            "jumlah_terdakwa",
            "status_nomor",
            "status_tanggal",
            "status_amar",
            "status_barang_bukti"
        ]
    ]
)

TOTAL DOKUMEN: 50

HASIL DETEKSI METADATA
status_nomor : 50 / 50
status_tanggal : 26 / 50
status_amar : 50 / 50
status_barang_bukti : 50 / 50

,case_id,no_perkara,tanggal,pasal,pihak,jumlah_terdakwa,status_nomor,status_tanggal,status_amar,status_barang_bukti
0,putusan_1024_Pid_Sus_2023_PN_Sby,1024/Pid.Sus/2023/PNSby,None,Pasal 25; pasal 114 ayat (2); pasal 132 ayat (...,Surya Aji Pratama Bin Darmawan; Satriyo Wahyun...,2,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
1,putusan_140_Pid_Sus_2023_PN_Sby,140/Pid.Sus/2023/PNSby,None,pasal 112 ayat (1); pasal 114 ayat (1); Pasal ...,Andika Fajar Yulisetiawan Bin Abdul Choir,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
2,putusan_1512_Pid_Sus_2023_PN_Sby,1512/Pid.Sus/2023/PNSby,None,Pasal 112 ayat (1); pasal 114 ayat (1),BAGUS IRYANTO als BAGUS Bin WIDYAN MULYADI,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
3,putusan_1880_Pid_Sus_2023_PN_Sby,1880/Pid.Sus/2023/PNSby,None,pasal 114 ayat (2); pasal 132 ayat (1); Pasal ...,Ridwan Firmansyah Bin Rukman (Alm) Als Revan,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
4,putusan_1982_Pid_Sus_2023_PN_Sby,1982/Pid.Sus/2023/PNSby,28\nNovember 2023,Pasal 114 ayat (1); Pasal 112 ayat (1); Pasal ...,Eric Soesanto Prayitno Alias Eric Londo,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
5,putusan_2031_Pid_Sus_2023_PN_Sby,2031/Pid.Sus/2023/PNSby,None,Pasal 112 ayat (1); Pasal 114 ayat (1),"Yan Haldiyansyah, SE Bin Budiono",1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
6,putusan_2043_Pid_Sus_2023_PN_Sby,2043/Pid.Sus/2023/PNSby,None,Pasal 114 Ayat (1); Pasal 132 ayat (1); Pasal ...,RAFI MAHARDIKA KURNIAWAN alias EPRET bin FREDDY,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
7,putusan_2047_Pid_Sus_2023_PN_Sby,2047/Pid.Sus/2023/PNSby,None,Pasal 29; Pasal 112 ayat (2); pasal 114 ayat (...,Toni Wicaksono Bin Tri Tjahya Boedi Santoso,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
8,putusan_2166_Pid_Sus_2023_PN_Sby,2166/Pid.Sus/2023/PNSby,None,Pasal 114 ayat (1); Pasal 132 ayat (1); Pasal ...,Hariyanto Als. Mbah Di Bin Bari; Andi Susila A...,2,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
9,putusan_2189_Pid_Sus_2023_PN_Sby,2189/Pid.Sus/2023/PNSby,None,Pasal 112 ayat (1); Pasal 132 ayat (1); Pasal ...,Muhamad Samsuri Bin Hatip (alm); Dharma Tragah...,2,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
10,putusan_2258_Pid_Sus_2023_PN_Sby,2258/Pid.Sus/2023/PNSby,18\nDesember 2023,Pasal 114 Ayat (1); Pasal 132 ayat (1); Pasal ...,Moch Sulam Bin Moch Zaini (alm); Badrul Qomar ...,2,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
11,putusan_2260_Pid_Sus_2023_PN_Sby,2260/Pid.Sus/2023/PNSby,7\nDesember 2023,Pasal 112 ayat (1); Pasal 114 Ayat (1); Pasal 6,Moh. Arif Bin Moh. Slamed,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
12,putusan_2274_Pid_Sus_2023_PN_Sby,2274/Pid.Sus/2023/PNSby,None,Pasal 112 ayat (1); Pasal 114 ayat (1); Pasal ...,Dewa Agira Panji Caroko Bin Dachlan Poernomo,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
13,putusan_2325_Pid_Sus_2023_PN_Sby,2325/Pid.Sus/2023/PNSby,None,pasal 114 ayat (1); Pasal 111 ayat (1),Muhammad Choirul Hartono als Putra Bin Hartono,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
14,putusan_2359_Pid_Sus_2023_PN_Sby,2359/Pid.Sus/2023/PNSby,11 Desember 2023,Pasal 25; Pasal 114 ayat (1); Pasal 112 ayat (1),Sabdono Nurfiyanto Bin Alm.Bahrudin,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
15,putusan_2438_Pid_Sus_2023_PN_Sby,2438/Pid.Sus/2023/PNSby,None,Pasal 114 ayat (1); pasal 132 ayat (1); pasal ...,I.N. DWI ANTANA DUSAK Anak Dari NYOMAN; ERWIN ...,3,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
16,putusan_270_Pid_Sus_2023_PN_Sby,270/Pid.Sus/2023/PNSby,None,pasal 114 ayat (1); pasal 112 ayat (1); Pasal ...,Samsul Huda Bin Mudaim (alm),1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
17,putusan_1068_Pid_Sus_2024_PN_Sby,1068/Pid.Sus/2024/PNSby,8\nAgustus 2024,Pasal 112 ayat (1); Pasal 132 ayat (1); pasal ...,WIRANTO FAJAR WIBOWO BIN AGUNG BUDI; ADI WAHON...,2,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
18,putusan_1276_Pid_Sus_2024_PN_Sby,1276/Pid.Sus/2024/PNSby,4\nSeptember 2024,Pasal 114 ayat (1); Pasal 112 ayat (1); Pasal ...,GALU RINEKSO,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
19,putusan_1629_Pid_Sus_2024_PN_Sby,1629/Pid.Sus/2024/PNSby,17 Desember 2024,Pasal 112 ayat (1); pasal 1 ayat (1); pasal 8 ...,YAYAN MARDIANTO anak dari TOTOK SUWITO,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
20,putusan_1741_Pid_Sus_2024_PN_Sby,1741/Pid.Sus/2024/PNSby,None,pasal 114 ayat (1); pasal 112 ayat (1); pasal ...,Budi Darmawan Bin Sudarmaji (alm),1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
21,putusan_1751_Pid_Sus_2024_PN_Sby,1751/Pid.Sus/2024/PNSby,None,Pasal 25; Pasal 112 ayat (1); pasal 84 ayat (2...,Toliful Ilmi Bin Doholil,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
22,putusan_1846_Pid_Sus_2024_PN_Sby,1846/Pid.Sus/2024/PNSby,None,Pasal 114 ayat (1); Pasal 112 Ayat (1); Pasal ...,AMIRUL HAMZAH Bin MALIK,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
23,putusan_1901_Pid_Sus_2024_PN_Sby,1901/Pid.Sus/2024/PNSby,None,Pasal 114 Ayat (2); pasal 112 ayat (2); pasal ...,Masduqi Zakaria Bin Alimun (Alm),1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
24,putusan_1904_Pid_Sus_2024_PN_Sby,1904/Pid.Sus/2024/PNSby,None,Pasal 25; Pasal 114 ayat (1); pasal 84 ayat (2...,MIFTAHUL ROHMAN bin KOSIM,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
25,putusan_1968_Pid_Sus_2024_PN_Sby,1968/Pid.Sus/2024/PNSby,10 Desember 2024,Pasal 114 Ayat (1); Pasal 112 ayat (1); Pasal ...,Supriono Bin Sukamdi,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
26,putusan_2010_Pid_Sus_2024_PN_Sby,2010/Pid.Sus/2024/PNSby,None,Pasal 25; Pasal 138 ayat (2); Pasal 114 ayat (...,MUHAMMAD YASIN Bin SAMSUDIN (Alm),1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
27,putusan_2017_Pid_Sus_2024_PN_Sby,2017/Pid.Sus/2024/PNSby,None,Pasal 114 ayat (1); Pasal 112 ayat (1); Pasal ...,Moch Zainul Imam Bin Anwar,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
28,putusan_2050_Pid_Sus_2024_PN_Sby,2050/Pid.Sus/2024/PNSby,12 Desember 2024,Pasal 114 ayat (1); pasal 84 ayat (2); Pasal 1...,Amin Fauzi Primap Bin Sabirin,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
29,putusan_2054_Pid_Sus_2024_PN_Sby,2054/Pid.Sus/2024/PNSby,18\nDesember 2024,Pasal 114 ayat (1); Pasal 39 ayat (1); Pasal 4...,Yoyok Sulistiyo Bin Muchamad,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
30,putusan_2071_Pid_Sus_2024_PN_Sby,2071/Pid.Sus/2024/PNSby.,3\nDesember 2024,Pasal 114 ayat (2); pasal 112 ayat (2); pasal ...,PRAYOGO BAYU PAMUNGKAS Bin BAMBANG PRAPTO SUSILO,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
31,putusan_2127_Pid_Sus_2024_PN_Sby,2127/Pid.Sus/2024/PNSby,18 Desember 2024,Pasal 114 ayat (1); Pasal 112 ayat (1); Pasal ...,Indra Iswanto Bin Slamet,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
32,putusan_2302_Pid_Sus_2024_PN_Sby,2302/Pid.Sus/2024/PNSby,None,Pasal 127 Ayat (1); Pasal 112 ayat (1); Pasal ...,ACH. KARAFI PRATAMA Bin MAT JUHA,1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
33,putusan_2454_Pid_Sus_2024_PN_Sby,2454/Pid.Sus/2024/PNSby,None,Pasal 114 Ayat (1); Pasal 112 ayat (1),SOEDJIANTO ALIAS ATAK BIN TOHIR (alm),1,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
34,putusan_891_Pid_Sus_2024_PN_Sby,891/Pid.Sus/2024/PNSby,None,Pasal 112 ayat (1); Pasal 132 ayat (1); Pasal ...,Ahmad Dani Bin (Alm) Mujasit; Lucky Wahyu Sanj...,2,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
35,putusan_898_Pid_Sus_2024_PN_Sby,898/Pid.Sus/2024/PNSby,06 Agustus 2024,Pasal 114 Ayat (1); Pasal 127 ayat (1); Pasal ...,Risqi Nur Junianto Bin Ambrin,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
36,putusan_1668_Pid_Sus_2025_PN_Sby,1668/Pid.Sus/2025/PNSby,14 Oktober 2025,Pasal 114 ayat (2); pasal 112 ayat (2); pasal ...,FERNANDA BAGUS SASONGKO BIN JARNO,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
37,putusan_1773_Pid_Sus_2025_PN_Sby,1773/Pid.Sus/2025/PNSby,21 Oktober 2025,Pasal 56; Pasal 114 ayat (2); Pasal 39 ayat (1...,Yogas Ardinata Melarahmanda bin Supardi,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
38,putusan_1789_Pid_Sus_2025_PN_Sby,1789/Pid.Sus/2025/PNSby,20 Oktober 2025,Pasal 114 ayat (2); Pasal 112 ayat (2); Pasal ...,DESY RACHMA PUJI ASTUTI BINTI BAMBANG,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
39,putusan_1852_Pid_Sus_2025_PN_Sby,1852/Pid.Sus/2025/PNSby,21 Oktober 2025,Pasal 114 ayat (1); pasal 127 ayat (3); Pasal ...,Henry Anak Dari Heni Darmanto,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
40,putusan_1880_Pid_Sus_2025_PN_Sby,1880/Pid.Sus/2025/PNSby,21 Oktober 2025,Pasal 25; Pasal 114; Pasal 132 Ayat (1); Pasal...,CHAIRUL ANDRIANTO bin MOH SAPRANI; MOCH. RIZKY...,2,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
41,putusan_1895_Pid_Sus_2025_PN_Sby,1895/Pid.Sus/2025/PNSby,None,Pasal 114 ayat (1); Pasal 132 ayat (1); Pasal ...,LUKMAN Bin MURSIDI; OKKY HERMANTO Bin MATALI,2,Terdeteksi,Perlu diperiksa,Terdeteksi,Terdeteksi
42,putusan_1930_Pid_Sus_2025_PN_Sby,1930/Pid.Sus/2025/PNSby,23 Oktober 2025,Pasal 56; Pasal 114 ayat (1); Pasal 132 ayat (...,NUR ISKANDARSAH; ERWIN HERAWAN,2,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
43,putusan_1949_Pid_Sus_2025_PN_Sby,1949/Pid.Sus/2025/PN.Sby.,28 Oktober 2025,Pasal 114 ayat (1); Pasal 435; Pasal 138 ayat ...,FERLINDA SELVYA PUTRI NYUGIANTO Als. LINDA Bin...,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
44,putusan_1965_Pid_Sus_2025_PN_Sby,1965/Pid.Sus/2025/PNSby,14 Oktober 2025,Pasal 25; Pasal 112 ayat (1); Pasal 127 ayat (...,Arga Surya Bimantara Bin Sartono,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
45,putusan_2101_Pid_Sus_2025_PN_Sby,2101/Pid.Sus/2025/PNSby,27 Oktober 2025,Pasal 114 ayat (1); pasal 84 ayat (2); Pasal 1...,Yudharta Sapta Prasetya bin Harry Koesnandar,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
46,putusan_2109_Pid_Sus_2025_PN_Sby,2109/Pid.Sus/2025/PN.Sby,28 Oktober 2025,Pasal 114 ayat (1); Pasal 112 ayat (1); Pasal 1,Syaiful Romli Bin Mat Hafi,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
47,putusan_222_Pid_Sus_2025_PN_Sby,222/Pid.Sus/2025/PNSby,14 April 2025,Pasal 56; Pasal 114 Ayat (1); Pasal 39 ayat (1...,MOCH ROCHMAN bin MOCH YUNUS,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
48,putusan_482_Pid_Sus_2025_PN_Sby,482/Pid.Sus/2025/PN.Sby.,05 Mei 2025,Pasal 114 ayat (1); Pasal 132 ayat (1); pasal ...,AISAH alias ICHA Binti JAMIL ROBI; ANANG SUROT...,3,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi
49,putusan_579_Pid_Sus_2025_PN_Sby,579/Pid.Sus/2025/PNSby,07 Mei 2025,Pasal 114 ayat (1); pasal 111 ayat (1); pasal ...,ACHMAD NGGOPUR Bin SUIPUK KUSWANTO,1,Terdeteksi,Terdeteksi,Terdeteksi,Terdeteksi

In [88]:

# ============================================================
# EKSTRAKSI FINAL 50 PUTUSAN
# ============================================================

hasil_final = []

for nomor_urut, doc in enumerate(documents, start=1):

    teks = doc["isi_putusan"]
    nama_file = doc["nama_file"]

    # Ekstraksi nama terdakwa
    nama = ekstrak_nama_terdakwa(teks)

    # Terapkan koreksi nama yang sudah diverifikasi
    if nama_file in koreksi_nama:
        nama = koreksi_nama[nama_file]

    # Ekstraksi amar dan barang bukti
    hasil_amar = ekstrak_amar_dan_barang_bukti(teks)

    hasil_final.append({
        "no": nomor_urut,
        "nomor_putusan": ekstrak_nomor_putusan(teks),
        "lembaga_pengadilan": ekstrak_lembaga(teks),
        "nama_terdakwa": "; ".join(nama) if nama else None,
        "barang_bukti": hasil_amar["barang_bukti"],
        "amar_putusan": hasil_amar["amar_putusan"]
    })

# Membuat DataFrame final
df_final = pd.DataFrame(hasil_final)

# Validasi kelengkapan
print("TOTAL DOKUMEN:", len(df_final))

for kolom in df_final.columns:
    terisi = df_final[kolom].notna().sum()
    print(f"{kolom}: {terisi}/{len(df_final)}")

display(df_final.head())

# Simpan CSV
output_final = os.path.join(
    DATA_DIR,
    "dataset_putusan_ekstraksi.csv"
)

df_final.to_csv(
    output_final,
    index=False,
    encoding="utf-8-sig"
)

print("\nDataset tersimpan:", output_final)

TOTAL DOKUMEN: 50
no: 50/50
nomor_putusan: 50/50
lembaga_pengadilan: 50/50
nama_terdakwa: 50/50
barang_bukti: 50/50
amar_putusan: 50/50

,no,nomor_putusan,lembaga_pengadilan,nama_terdakwa,barang_bukti,amar_putusan
0,1,1024/Pid.Sus/2023/PNSby,Pengadilan Negeri Surabaya,Surya Aji Pratama Bin Darmawan; Satriyo Wahyun...,Menetapkan barang bukti berupa : \n- \n1 (satu...,M E N G A D I L I \n1. Menyatakan Terdakwa I S...
1,2,140/Pid.Sus/2023/PNSby,Pengadilan Negeri Surabaya,Andika Fajar Yulisetiawan Bin Abdul Choir,Menetapkan barang bukti berupa :\n-\n1 (satu) ...,M E N G A D I L I\n1.\nMenyatakan Terdakwa And...
2,3,1512/Pid.Sus/2023/PNSby,Pengadilan Negeri Surabaya,BAGUS IRYANTO als BAGUS Bin WIDYAN MULYADI,Menetapkan barang bukti berupa : \n- 1 (satu) ...,M E N G A D I L I : \n1. Menyatakan Terdakwa B...
3,4,1880/Pid.Sus/2023/PNSby,Pengadilan Negeri Surabaya,Ridwan Firmansyah Bin Rukman (Alm) Als Revan,Menetapkan barang bukti berupa :\n-\n1 (satu) ...,MENGADILI:\n1. Menyatakan Terdakwa Ridwan Firm...
4,5,1982/Pid.Sus/2023/PNSby,Pengadilan Negeri Surabaya,Eric Soesanto Prayitno Alias Eric Londo,Menetapkan barang bukti berupa : \n\n1 (satu)...,MENGADILI:\n1.\nMenyatakan Terdakwa Eric Soesa...

Dataset tersimpan: /content/Dataset-Narkotika_027_199/data/dataset_putusan_ekstraksi.csv