<a href="https://colab.research.google.com/github/shefiramarizcha62-sudo/Dataset-Narkotika_027_199/blob/crawling/04_ekstraksi_putusan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install -q pymupdf pandas

In [ ]:
import fitz
import os
import pandas as pd
from pathlib import Path

/usr/local/lib/python3.13/dist-packages/fitz/__init__.py:17: FutureWarning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.
  warnings.warn(

In [ ]:
import os

DRIVE_PATH = '/content/drive/MyDrive'

for root, dirs, files in os.walk(DRIVE_PATH):
    if os.path.basename(root) == 'CRAWLING':
        if 'PDF_Putusan' in dirs and 'TXT_Putusan' in dirs:
            BASE_DIR = root
            PDF_DIR = os.path.join(root, 'PDF_Putusan')
            TXT_DIR = os.path.join(root, 'TXT_Putusan')
            break

print("BASE DIR:", BASE_DIR)
print("PDF DIR:", PDF_DIR)
print("TXT DIR:", TXT_DIR)

BASE DIR: /content/drive/MyDrive/Semester 7/Information Retrieval/UTS - KELOMPOK/CRAWLING
PDF DIR: /content/drive/MyDrive/Semester 7/Information Retrieval/UTS - KELOMPOK/CRAWLING/PDF_Putusan
TXT DIR: /content/drive/MyDrive/Semester 7/Information Retrieval/UTS - KELOMPOK/CRAWLING/TXT_Putusan

In [ ]:
for tahun in ['2023', '2024', '2025']:
    folder = os.path.join(PDF_DIR, tahun)

    file_pdf = [
        f for f in os.listdir(folder)
        if f.lower().endswith('.pdf')
    ]

    print(f"{tahun}: {len(file_pdf)} PDF")

2023: 17 PDF
2024: 17 PDF
2025: 16 PDF

In [ ]:
!pip install -q pymupdf

In [ ]:
import fitz
import os

In [ ]:
hasil_ekstraksi = []

for tahun in ['2023', '2024', '2025']:

    folder_pdf = os.path.join(PDF_DIR, tahun)
    folder_txt = os.path.join(TXT_DIR, tahun)

    os.makedirs(folder_txt, exist_ok=True)

    file_pdf = sorted([
        f for f in os.listdir(folder_pdf)
        if f.lower().endswith('.pdf')
    ])

    print(f"\nMemproses tahun {tahun}: {len(file_pdf)} PDF")

    for nama_file in file_pdf:

        path_pdf = os.path.join(folder_pdf, nama_file)
        nama_txt = os.path.splitext(nama_file)[0] + '.txt'
        path_txt = os.path.join(folder_txt, nama_txt)

        try:
            with fitz.open(path_pdf) as dokumen:
                jumlah_halaman = len(dokumen)

                daftar_teks = []

                for nomor_halaman, halaman in enumerate(dokumen, start=1):
                    teks_halaman = halaman.get_text("text")

                    daftar_teks.append(
                        f"\n\n========== HALAMAN {nomor_halaman} ==========\n\n"
                        + teks_halaman
                    )

                teks = ''.join(daftar_teks)

            with open(path_txt, 'w', encoding='utf-8') as file:
                file.write(teks)

            status = 'Berhasil' if teks.strip() else 'Teks Kosong'

            hasil_ekstraksi.append({
                'Tahun': tahun,
                'Nama PDF': nama_file,
                'Nama TXT': nama_txt,
                'Jumlah Halaman': jumlah_halaman,
                'Jumlah Karakter': len(teks),
                'Status': status
            })

        except Exception as e:
            hasil_ekstraksi.append({
                'Tahun': tahun,
                'Nama PDF': nama_file,
                'Nama TXT': nama_txt,
                'Jumlah Halaman': 0,
                'Jumlah Karakter': 0,
                'Status': f'Gagal: {str(e)}'
            })

df_hasil = pd.DataFrame(hasil_ekstraksi)
display(df_hasil)

Memproses tahun 2023: 17 PDF

Memproses tahun 2024: 17 PDF

Memproses tahun 2025: 16 PDF

,Tahun,Nama PDF,Nama TXT,Jumlah Halaman,Jumlah Karakter,Status
0,2023,putusan_1024_Pid_Sus_2023_PN_Sby.pdf,putusan_1024_Pid_Sus_2023_PN_Sby.txt,60,192831,Berhasil
1,2023,putusan_1061_K_PDT_SUS_PHI_2026.pdf,putusan_1061_K_PDT_SUS_PHI_2026.txt,11,29485,Berhasil
2,2023,putusan_140_Pid_Sus_2023_PN_Sby.pdf,putusan_140_Pid_Sus_2023_PN_Sby.txt,21,63756,Berhasil
3,2023,putusan_1512_Pid_Sus_2023_PN_Sby.pdf,putusan_1512_Pid_Sus_2023_PN_Sby.txt,18,60540,Berhasil
4,2023,putusan_1880_Pid_Sus_2023_PN_Sby.pdf,putusan_1880_Pid_Sus_2023_PN_Sby.txt,63,202038,Berhasil
5,2023,putusan_1982_Pid_Sus_2023_PN_Sby.pdf,putusan_1982_Pid_Sus_2023_PN_Sby.txt,15,46114,Berhasil
6,2023,putusan_2031_Pid_Sus_2023_PN_Sby.pdf,putusan_2031_Pid_Sus_2023_PN_Sby.txt,16,47207,Berhasil
7,2023,putusan_2043_Pid_Sus_2023_PN_Sby.pdf,putusan_2043_Pid_Sus_2023_PN_Sby.txt,22,64909,Berhasil
8,2023,putusan_2047_Pid_Sus_2023_PN_Sby.pdf,putusan_2047_Pid_Sus_2023_PN_Sby.txt,26,81505,Berhasil
9,2023,putusan_2166_Pid_Sus_2023_PN_Sby.pdf,putusan_2166_Pid_Sus_2023_PN_Sby.txt,25,79517,Berhasil
10,2023,putusan_2189_Pid_Sus_2023_PN_Sby.pdf,putusan_2189_Pid_Sus_2023_PN_Sby.txt,27,82632,Berhasil
11,2023,putusan_2258_Pid_Sus_2023_PN_Sby.pdf,putusan_2258_Pid_Sus_2023_PN_Sby.txt,21,64463,Berhasil
12,2023,putusan_2260_Pid_Sus_2023_PN_Sby.pdf,putusan_2260_Pid_Sus_2023_PN_Sby.txt,18,54456,Berhasil
13,2023,putusan_2274_Pid_Sus_2023_PN_Sby.pdf,putusan_2274_Pid_Sus_2023_PN_Sby.txt,18,56571,Berhasil
14,2023,putusan_2325_Pid_Sus_2023_PN_Sby.pdf,putusan_2325_Pid_Sus_2023_PN_Sby.txt,24,74573,Berhasil
15,2023,putusan_2359_Pid_Sus_2023_PN_Sby.pdf,putusan_2359_Pid_Sus_2023_PN_Sby.txt,24,69972,Berhasil
16,2023,putusan_270_Pid_Sus_2023_PN_Sby.pdf,putusan_270_Pid_Sus_2023_PN_Sby.txt,17,53510,Berhasil
17,2024,putusan_1068_Pid_Sus_2024_PN_Sby.pdf,putusan_1068_Pid_Sus_2024_PN_Sby.txt,18,58777,Berhasil
18,2024,putusan_1276_Pid_Sus_2024_PN_Sby.pdf,putusan_1276_Pid_Sus_2024_PN_Sby.txt,19,56733,Berhasil
19,2024,putusan_1629_Pid_Sus_2024_PN_Sby.pdf,putusan_1629_Pid_Sus_2024_PN_Sby.txt,19,58463,Berhasil
20,2024,putusan_1741_Pid_Sus_2024_PN_Sby.pdf,putusan_1741_Pid_Sus_2024_PN_Sby.txt,16,50018,Berhasil
21,2024,putusan_1751_Pid_Sus_2024_PN_Sby.pdf,putusan_1751_Pid_Sus_2024_PN_Sby.txt,17,54631,Berhasil
22,2024,putusan_1846_Pid_Sus_2024_PN_Sby.pdf,putusan_1846_Pid_Sus_2024_PN_Sby.txt,19,61648,Berhasil
23,2024,putusan_1901_Pid_Sus_2024_PN_Sby.pdf,putusan_1901_Pid_Sus_2024_PN_Sby.txt,22,68680,Berhasil
24,2024,putusan_1904_Pid_Sus_2024_PN_Sby.pdf,putusan_1904_Pid_Sus_2024_PN_Sby.txt,24,74064,Berhasil
25,2024,putusan_1968_Pid_Sus_2024_PN_Sby.pdf,putusan_1968_Pid_Sus_2024_PN_Sby.txt,18,56557,Berhasil
26,2024,putusan_2017_Pid_Sus_2024_PN_Sby.pdf,putusan_2017_Pid_Sus_2024_PN_Sby.txt,21,64403,Berhasil
27,2024,putusan_2050_Pid_Sus_2024_PN_Sby.pdf,putusan_2050_Pid_Sus_2024_PN_Sby.txt,22,69288,Berhasil
28,2024,putusan_2054_Pid_Sus_2024_PN_Sby.pdf,putusan_2054_Pid_Sus_2024_PN_Sby.txt,18,55762,Berhasil
29,2024,putusan_2071_Pid_Sus_2024_PN_Sby.pdf,putusan_2071_Pid_Sus_2024_PN_Sby.txt,19,56687,Berhasil
30,2024,putusan_2127_Pid_Sus_2024_PN_Sby.pdf,putusan_2127_Pid_Sus_2024_PN_Sby.txt,25,83184,Berhasil
31,2024,putusan_219_K_MIL_2026.pdf,putusan_219_K_MIL_2026.txt,8,21451,Berhasil
32,2024,putusan_2302_Pid_Sus_2024_PN_Sby.pdf,putusan_2302_Pid_Sus_2024_PN_Sby.txt,20,61557,Berhasil
33,2024,putusan_891_Pid_Sus_2024_PN_Sby.pdf,putusan_891_Pid_Sus_2024_PN_Sby.txt,16,52241,Berhasil
34,2025,putusan_1668_Pid_Sus_2025_PN_Sby.pdf,putusan_1668_Pid_Sus_2025_PN_Sby.txt,26,77820,Berhasil
35,2025,putusan_1773_Pid_Sus_2025_PN_Sby.pdf,putusan_1773_Pid_Sus_2025_PN_Sby.txt,34,107233,Berhasil
36,2025,putusan_1789_Pid_Sus_2025_PN_Sby.pdf,putusan_1789_Pid_Sus_2025_PN_Sby.txt,23,70366,Berhasil
37,2025,putusan_1852_Pid_Sus_2025_PN_Sby.pdf,putusan_1852_Pid_Sus_2025_PN_Sby.txt,21,65741,Berhasil
38,2025,putusan_1880_Pid_Sus_2025_PN_Sby.pdf,putusan_1880_Pid_Sus_2025_PN_Sby.txt,27,83162,Berhasil
39,2025,putusan_1895_Pid_Sus_2025_PN_Sby.pdf,putusan_1895_Pid_Sus_2025_PN_Sby.txt,28,94522,Berhasil
40,2025,putusan_1930_Pid_Sus_2025_PN_Sby.pdf,putusan_1930_Pid_Sus_2025_PN_Sby.txt,44,144085,Berhasil
41,2025,putusan_1949_Pid_Sus_2025_PN_Sby.pdf,putusan_1949_Pid_Sus_2025_PN_Sby.txt,27,84023,Berhasil
42,2025,putusan_1965_Pid_Sus_2025_PN_Sby.pdf,putusan_1965_Pid_Sus_2025_PN_Sby.txt,18,54867,Berhasil
43,2025,putusan_2010_Pid_Sus_2024_PN_Sby.pdf,putusan_2010_Pid_Sus_2024_PN_Sby.txt,35,112545,Berhasil
44,2025,putusan_2101_Pid_Sus_2025_PN_Sby.pdf,putusan_2101_Pid_Sus_2025_PN_Sby.txt,20,67066,Berhasil
45,2025,putusan_2109_Pid_Sus_2025_PN_Sby.pdf,putusan_2109_Pid_Sus_2025_PN_Sby.txt,15,44800,Berhasil
46,2025,putusan_222_Pid_Sus_2025_PN_Sby.pdf,putusan_222_Pid_Sus_2025_PN_Sby.txt,33,105629,Berhasil
47,2025,putusan_2454_Pid_Sus_2024_PN_Sby.pdf,putusan_2454_Pid_Sus_2024_PN_Sby.txt,23,72048,Berhasil
48,2025,putusan_482_Pid_Sus_2025_PN_Sby.pdf,putusan_482_Pid_Sus_2025_PN_Sby.txt,50,162729,Berhasil
49,2025,putusan_579_Pid_Sus_2025_PN_Sby.pdf,putusan_579_Pid_Sus_2025_PN_Sby.txt,26,83227,Berhasil

6. Evaluasi Hasil

In [ ]:
print(df_hasil['Status'].value_counts())

Status
Berhasil    50
Name: count, dtype: int64

7. Simpan Hasil Ekstraksi Pdf to TXT

In [ ]:
df_hasil.to_csv(
    os.path.join(BASE_DIR, 'laporan_pdf_to_txt.csv'),
    index=False,
    encoding='utf-8-sig'
)

In [ ]:
file_txt = os.path.join(
    TXT_DIR,
    '2023',
    os.listdir(os.path.join(TXT_DIR, '2023'))[0]
)

with open(file_txt, 'r', encoding='utf-8') as f:
    print(f.read()[:2000])

========== HALAMAN 1 ==========

hkama
ahkamah Agung Repub
ahkamah Agung Republik Indonesia
mah Agung Republik Indonesia
blik Indonesi
Direktori Putusan Mahkamah Agung Republik Indonesia
putusan.mahkamahagung.go.id
Halaman 1 dari 60 Putusan Nomor 1024/Pid.Sus/2023/PN Sby

P U T U S A N
Nomor 1024/Pid.Sus/2023/PN Sby

DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA

Pengadilan Negeri Surabaya yang mengadili perkara pidana dengan
acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai
berikut dalam perkara Para Terdakwa :
Terdakwa 1
1.  Nama lengkap
: Surya Aji Pratama Bin Darmawan
2.  Tempat lahir
: Mojokerto
3.  Umur/Tanggal lahir
: 31 Tahun / 24 Mei 1992
4.  Jenis kelamin
: Laki-laki
5.  Kebangsaan
: Indonesia
6.  Tempat tinggal
: Dsn. Kalijaring, RT 004 / RW 007, Ds. Mlirip, Kec.
Jetis,
Kab.
Mojokerto
(sesuai
NIK
3516162405920006) atau bertempat tinggal di Jl.
Kebraon Indah Permai, Kel. Kebraon, Kec. Karang
Pilang, Kota Surabaya
7.  Agama
: Islam
8.  Pekerjaan
: Tukang batu

Terdakwa Surya Aji Pratama Bin Darmawan ditahan dalam tahanan rutan oleh:
1.  Penyidik sejak tanggal 4 Februari 2023 sampai dengan tanggal 23 Februari
2023
2.  Penyidik Perpanjangan Oleh Penuntut Umum sejak tanggal 24 Februari 2023
sampai dengan tanggal 4 April 2023
3.  Penuntut Umum sejak tanggal 4 April 2023 sampai dengan tanggal 23 April
2023
4.  Penuntut Umum Perpanjangan Oleh Ketua Pengadilan Negeri (Pasal 25)
sejak tanggal 24 April 2023 sampai dengan tanggal 23 Mei 2023
5.  Hakim Pengadilan Negeri sejak tanggal 15 Mei 2023 sampai dengan tanggal
13 Juni 2023
6.  Hakim Pengadilan Negeri Perpanjangan Oleh Ketua Pengadilan Negeri sejak
tanggal 14 Juni 2023 sampai dengan tanggal 12 Agustus 2023

Terdakwa 2
1.  Nama lengkap
: Satriyo Wahyuning Gusti als Tio Bin Eko Supriyadi
          Pid.I.A.3
Disclaimer
Kepaniteraan Mahkamah Agung Republik Indonesia berusaha untuk selalu mencantumkan informasi paling

periksa jumlah pdf dan txt

In [ ]:
import os

tahun_list = ['2023', '2024', '2025']

for tahun in tahun_list:
    folder_pdf = os.path.join(PDF_DIR, tahun)
    folder_txt = os.path.join(TXT_DIR, tahun)

    jumlah_pdf = len([
        f for f in os.listdir(folder_pdf)
        if f.lower().endswith('.pdf')
    ])

    jumlah_txt = len([
        f for f in os.listdir(folder_txt)
        if f.lower().endswith('.txt')
    ])

    print(f'{tahun}: PDF = {jumlah_pdf}, TXT = {jumlah_txt}')

2023: PDF = 17, TXT = 17
2024: PDF = 17, TXT = 17
2025: PDF = 16, TXT = 16

periksa seluruh txt

In [ ]:
hasil_validasi = []

for tahun in tahun_list:
    folder_txt = os.path.join(TXT_DIR, tahun)

    for nama_file in os.listdir(folder_txt):
        if not nama_file.lower().endswith('.txt'):
            continue

        path_txt = os.path.join(folder_txt, nama_file)

        with open(path_txt, 'r', encoding='utf-8') as f:
            teks = f.read()

        hasil_validasi.append({
            'Tahun': tahun,
            'Nama TXT': nama_file,
            'Jumlah Karakter': len(teks),
            'Jumlah Halaman': teks.count('========== HALAMAN'),
            'Status': 'Berisi teks' if teks.strip() else 'Kosong'
        })

df_validasi = pd.DataFrame(hasil_validasi)

display(df_validasi)

print('\nRingkasan:')
print(df_validasi['Status'].value_counts())
print('\nTotal TXT:', len(df_validasi))

,Tahun,Nama TXT,Jumlah Karakter,Jumlah Halaman,Status
0,2023,putusan_1024_Pid_Sus_2023_PN_Sby.txt,192831,60,Berisi teks
1,2023,putusan_1061_K_PDT_SUS_PHI_2026.txt,29485,11,Berisi teks
2,2023,putusan_140_Pid_Sus_2023_PN_Sby.txt,63756,21,Berisi teks
3,2023,putusan_1512_Pid_Sus_2023_PN_Sby.txt,60540,18,Berisi teks
4,2023,putusan_1880_Pid_Sus_2023_PN_Sby.txt,202038,63,Berisi teks
5,2023,putusan_1982_Pid_Sus_2023_PN_Sby.txt,46114,15,Berisi teks
6,2023,putusan_2031_Pid_Sus_2023_PN_Sby.txt,47207,16,Berisi teks
7,2023,putusan_2043_Pid_Sus_2023_PN_Sby.txt,64909,22,Berisi teks
8,2023,putusan_2047_Pid_Sus_2023_PN_Sby.txt,81505,26,Berisi teks
9,2023,putusan_2166_Pid_Sus_2023_PN_Sby.txt,79517,25,Berisi teks
10,2023,putusan_2189_Pid_Sus_2023_PN_Sby.txt,82632,27,Berisi teks
11,2023,putusan_2258_Pid_Sus_2023_PN_Sby.txt,64463,21,Berisi teks
12,2023,putusan_2260_Pid_Sus_2023_PN_Sby.txt,54456,18,Berisi teks
13,2023,putusan_2274_Pid_Sus_2023_PN_Sby.txt,56571,18,Berisi teks
14,2023,putusan_2325_Pid_Sus_2023_PN_Sby.txt,74573,24,Berisi teks
15,2023,putusan_2359_Pid_Sus_2023_PN_Sby.txt,69972,24,Berisi teks
16,2023,putusan_270_Pid_Sus_2023_PN_Sby.txt,53510,17,Berisi teks
17,2024,putusan_1068_Pid_Sus_2024_PN_Sby.txt,58777,18,Berisi teks
18,2024,putusan_1276_Pid_Sus_2024_PN_Sby.txt,56733,19,Berisi teks
19,2024,putusan_1629_Pid_Sus_2024_PN_Sby.txt,58463,19,Berisi teks
20,2024,putusan_1741_Pid_Sus_2024_PN_Sby.txt,50018,16,Berisi teks
21,2024,putusan_1751_Pid_Sus_2024_PN_Sby.txt,54631,17,Berisi teks
22,2024,putusan_1846_Pid_Sus_2024_PN_Sby.txt,61648,19,Berisi teks
23,2024,putusan_1901_Pid_Sus_2024_PN_Sby.txt,68680,22,Berisi teks
24,2024,putusan_1904_Pid_Sus_2024_PN_Sby.txt,74064,24,Berisi teks
25,2024,putusan_1968_Pid_Sus_2024_PN_Sby.txt,56557,18,Berisi teks
26,2024,putusan_2017_Pid_Sus_2024_PN_Sby.txt,64403,21,Berisi teks
27,2024,putusan_2050_Pid_Sus_2024_PN_Sby.txt,69288,22,Berisi teks
28,2024,putusan_2054_Pid_Sus_2024_PN_Sby.txt,55762,18,Berisi teks
29,2024,putusan_2071_Pid_Sus_2024_PN_Sby.txt,56687,19,Berisi teks
30,2024,putusan_2127_Pid_Sus_2024_PN_Sby.txt,83184,25,Berisi teks
31,2024,putusan_219_K_MIL_2026.txt,21451,8,Berisi teks
32,2024,putusan_2302_Pid_Sus_2024_PN_Sby.txt,61557,20,Berisi teks
33,2024,putusan_891_Pid_Sus_2024_PN_Sby.txt,52241,16,Berisi teks
34,2025,putusan_1668_Pid_Sus_2025_PN_Sby.txt,77820,26,Berisi teks
35,2025,putusan_1773_Pid_Sus_2025_PN_Sby.txt,107233,34,Berisi teks
36,2025,putusan_1789_Pid_Sus_2025_PN_Sby.txt,70366,23,Berisi teks
37,2025,putusan_1852_Pid_Sus_2025_PN_Sby.txt,65741,21,Berisi teks
38,2025,putusan_1880_Pid_Sus_2025_PN_Sby.txt,83162,27,Berisi teks
39,2025,putusan_1895_Pid_Sus_2025_PN_Sby.txt,94522,28,Berisi teks
40,2025,putusan_1930_Pid_Sus_2025_PN_Sby.txt,144085,44,Berisi teks
41,2025,putusan_1949_Pid_Sus_2025_PN_Sby.txt,84023,27,Berisi teks
42,2025,putusan_1965_Pid_Sus_2025_PN_Sby.txt,54867,18,Berisi teks
43,2025,putusan_2010_Pid_Sus_2024_PN_Sby.txt,112545,35,Berisi teks
44,2025,putusan_2101_Pid_Sus_2025_PN_Sby.txt,67066,20,Berisi teks
45,2025,putusan_2109_Pid_Sus_2025_PN_Sby.txt,44800,15,Berisi teks
46,2025,putusan_222_Pid_Sus_2025_PN_Sby.txt,105629,33,Berisi teks
47,2025,putusan_2454_Pid_Sus_2024_PN_Sby.txt,72048,23,Berisi teks
48,2025,putusan_482_Pid_Sus_2025_PN_Sby.txt,162729,50,Berisi teks
49,2025,putusan_579_Pid_Sus_2025_PN_Sby.txt,83227,26,Berisi teks

Ringkasan:
Status
Berisi teks    50
Name: count, dtype: int64

Total TXT: 50

validasi pdf dan txt

In [ ]:
import random
import os

random.seed(42)

sampel_pdf = []

for tahun in ['2023', '2024', '2025']:
    folder = os.path.join(PDF_DIR, tahun)

    daftar_pdf = sorted([
        f for f in os.listdir(folder)
        if f.lower().endswith('.pdf')
    ])

    jumlah_sampel = min(2 if tahun != '2025' else 1, len(daftar_pdf))

    pilihan = random.sample(daftar_pdf, jumlah_sampel)

    for nama in pilihan:
        sampel_pdf.append({
            'Tahun': tahun,
            'Nama PDF': nama
        })

df_sampel = pd.DataFrame(sampel_pdf)
display(df_sampel)

  Tahun                              Nama PDF
0  2023  putusan_1512_Pid_Sus_2023_PN_Sby.pdf
1  2023  putusan_1024_Pid_Sus_2023_PN_Sby.pdf
2  2024  putusan_1968_Pid_Sus_2024_PN_Sby.pdf
3  2024  putusan_1904_Pid_Sus_2024_PN_Sby.pdf
4  2025  putusan_1949_Pid_Sus_2025_PN_Sby.pdf

bandingkan pdf dan txt

In [ ]:
hasil_perbandingan = []

for data in sampel_pdf:

    tahun = data['Tahun']
    nama_pdf = data['Nama PDF']

    nama_txt = os.path.splitext(nama_pdf)[0] + '.txt'

    path_pdf = os.path.join(PDF_DIR, tahun, nama_pdf)
    path_txt = os.path.join(TXT_DIR, tahun, nama_txt)

    # Membaca teks PDF
    with fitz.open(path_pdf) as dokumen:
        jumlah_halaman_pdf = len(dokumen)

        teks_pdf = '\n'.join(
            halaman.get_text('text')
            for halaman in dokumen
        )

    # Membaca teks TXT
    with open(path_txt, 'r', encoding='utf-8') as file:
        teks_txt = file.read()

    hasil_perbandingan.append({
        'Tahun': tahun,
        'Nama PDF': nama_pdf,
        'Jumlah Karakter PDF': len(teks_pdf),
        'Jumlah Karakter TXT': len(teks_txt),
        'PDF Terbaca': bool(teks_pdf.strip()),
        'TXT Terbaca': bool(teks_txt.strip()),
        'Jumlah Halaman PDF': jumlah_halaman_pdf,
        'Penanda Halaman TXT': teks_txt.count('========== HALAMAN')
    })

df_perbandingan = pd.DataFrame(hasil_perbandingan)

display(df_perbandingan)

,Tahun,Nama PDF,Jumlah Karakter PDF,Jumlah Karakter TXT,PDF Terbaca,TXT Terbaca,Jumlah Halaman PDF,Penanda Halaman TXT
0,2023,putusan_1512_Pid_Sus_2023_PN_Sby.pdf,59918,60540,True,True,18,18
1,2023,putusan_1024_Pid_Sus_2023_PN_Sby.pdf,190739,192831,True,True,60,60
2,2024,putusan_1968_Pid_Sus_2024_PN_Sby.pdf,55935,56557,True,True,18,18
3,2024,putusan_1904_Pid_Sus_2024_PN_Sby.pdf,73232,74064,True,True,24,24
4,2025,putusan_1949_Pid_Sus_2025_PN_Sby.pdf,83086,84023,True,True,27,27

In [ ]:
df_validasi = pd.DataFrame(hasil_ekstraksi)

print("Total dokumen:", len(df_validasi))
print("\nStatus ekstraksi:")
print(df_validasi['Status'].value_counts())

print("\nJumlah dokumen berdasarkan tahun:")
print(df_validasi.groupby('Tahun').size())

Total dokumen: 50

Status ekstraksi:
Status
Berhasil    50
Name: count, dtype: int64

Jumlah dokumen berdasarkan tahun:
Tahun
2023    17
2024    17
2025    16
dtype: int64

laporan validasi

In [ ]:
df_validasi.to_csv(
    os.path.join(BASE_DIR, 'laporan_pdf_to_txt.csv'),
    index=False,
    encoding='utf-8-sig'
)